macro_rules! object_option_fields {
    ($callback:ident) => {
        $callback! {
            brim_object_gap => "brim_object_gap": OrcaFloat = OrcaFloat(0.0),
            brim_flow_ratio => "brim_flow_ratio": OrcaFloat = OrcaFloat(1.0),
            brim_use_efc_outline => "brim_use_efc_outline": OrcaBool = OrcaBool(false),
            brim_type => "brim_type": ProcessBrimType = ProcessBrimType::AutoBrim,
            brim_width => "brim_width": OrcaFloat = OrcaFloat(0.0),
            brim_ears_detection_length => "brim_ears_detection_length": OrcaFloat = OrcaFloat(1.0),
            brim_ears_max_angle => "brim_ears_max_angle": OrcaFloat = OrcaFloat(125.0),
            skirt_start_angle => "skirt_start_angle": OrcaFloat = OrcaFloat(-135.0),
            bridge_no_support => "bridge_no_support": OrcaBool = OrcaBool(false),
            elefant_foot_compensation => "elefant_foot_compensation": OrcaFloat = OrcaFloat(0.0),
            elefant_foot_compensation_layers => "elefant_foot_compensation_layers": OrcaInt = OrcaInt(1),
            elefant_foot_layers_density => "elefant_foot_layers_density": Percent = Percent(100.0),
            max_bridge_length => "max_bridge_length": OrcaFloat = OrcaFloat(10.0),
            line_width => "line_width": FloatOrPercent = FloatOrPercent::Float(0.0),
            interface_shells => "interface_shells": OrcaBool = OrcaBool(false),
            layer_height => "layer_height": OrcaFloat = OrcaFloat(0.2),
            mmu_segmented_region_max_width => "mmu_segmented_region_max_width": OrcaFloat = OrcaFloat(0.0),
            mmu_segmented_region_interlocking_depth => "mmu_segmented_region_interlocking_depth": OrcaFloat = OrcaFloat(0.0),
            raft_contact_distance => "raft_contact_distance": OrcaFloat = OrcaFloat(0.1),
            raft_expansion => "raft_expansion": OrcaFloat = OrcaFloat(1.5),
            raft_first_layer_density => "raft_first_layer_density": Percent = Percent(90.0),
            raft_first_layer_expansion => "raft_first_layer_expansion": OrcaFloat = OrcaFloat(2.0),
            raft_layers => "raft_layers": OrcaInt = OrcaInt(0),
            seam_position => "seam_position": ProcessSeamPosition = ProcessSeamPosition::Aligned,
            staggered_inner_seams => "staggered_inner_seams": OrcaBool = OrcaBool(false),
            slice_closing_radius => "slice_closing_radius": OrcaFloat = OrcaFloat(0.049),
            slicing_mode => "slicing_mode": ProcessSlicingMode = ProcessSlicingMode::Regular,
            enable_support => "enable_support": OrcaBool = OrcaBool(false),
            support_type => "support_type": ProcessSupportType = ProcessSupportType::NormalAuto,
            support_angle => "support_angle": OrcaFloat = OrcaFloat(0.0),
            support_on_build_plate_only => "support_on_build_plate_only": OrcaBool = OrcaBool(false),
            support_critical_regions_only => "support_critical_regions_only": OrcaBool = OrcaBool(false),
            support_remove_small_overhang => "support_remove_small_overhang": OrcaBool = OrcaBool(true),
            support_top_z_distance => "support_top_z_distance": OrcaFloat = OrcaFloat(0.2),
            support_bottom_z_distance => "support_bottom_z_distance": OrcaFloat = OrcaFloat(0.2),
            enforce_support_layers => "enforce_support_layers": OrcaInt = OrcaInt(0),
            support_filament => "support_filament": OrcaInt = OrcaInt(0),
            support_line_width => "support_line_width": FloatOrPercent = FloatOrPercent::Float(0.0),
            support_interface_not_for_body => "support_interface_not_for_body": OrcaBool = OrcaBool(true),
            support_interface_loop_pattern => "support_interface_loop_pattern": OrcaBool = OrcaBool(false),
            support_interface_filament => "support_interface_filament": OrcaInt = OrcaInt(0),
            support_interface_top_layers => "support_interface_top_layers": OrcaInt = OrcaInt(3),
            support_interface_bottom_layers => "support_interface_bottom_layers": OrcaInt = OrcaInt(0),
            support_interface_spacing => "support_interface_spacing": OrcaFloat = OrcaFloat(0.5),
            support_interface_speed => "support_interface_speed": OrcaFloat = OrcaFloat(80.0),
            support_base_pattern => "support_base_pattern": ProcessSupportBasePattern = ProcessSupportBasePattern::Default,
            support_interface_pattern => "support_interface_pattern": ProcessSupportInterfacePattern = ProcessSupportInterfacePattern::Auto,
            support_base_pattern_spacing => "support_base_pattern_spacing": OrcaFloat = OrcaFloat(2.5),
            support_expansion => "support_expansion": OrcaFloat = OrcaFloat(0.0),
            support_speed => "support_speed": OrcaFloat = OrcaFloat(80.0),
            support_style => "support_style": ProcessSupportStyle = ProcessSupportStyle::Default,
            set_other_flow_ratios => "set_other_flow_ratios": OrcaBool = OrcaBool(false),
            support_flow_ratio => "support_flow_ratio": OrcaFloat = OrcaFloat(1.0),
            support_interface_flow_ratio => "support_interface_flow_ratio": OrcaFloat = OrcaFloat(1.0),
            thick_bridges => "thick_bridges": OrcaBool = OrcaBool(false),
            thick_internal_bridges => "thick_internal_bridges": OrcaBool = OrcaBool(true),
            dont_filter_internal_bridges => "dont_filter_internal_bridges": ProcessInternalBridgeFilter = ProcessInternalBridgeFilter::Disabled,
            enable_extra_bridge_layer => "enable_extra_bridge_layer": ProcessExtraBridgeLayer = ProcessExtraBridgeLayer::Disabled,
            internal_bridge_density => "internal_bridge_density": Percent = Percent(100.0),
            support_threshold_angle => "support_threshold_angle": OrcaInt = OrcaInt(30),
            support_threshold_overlap => "support_threshold_overlap": FloatOrPercent = FloatOrPercent::Percent(Percent(50.0)),
            support_object_xy_distance => "support_object_xy_distance": OrcaFloat = OrcaFloat(0.35),
            support_object_first_layer_gap => "support_object_first_layer_gap": OrcaFloat = OrcaFloat(0.2),
            support_ironing => "support_ironing": OrcaBool = OrcaBool(false),
            support_ironing_pattern => "support_ironing_pattern": ProcessInfillPattern = ProcessInfillPattern::Rectilinear,
            support_ironing_flow => "support_ironing_flow": Percent = Percent(10.0),
            support_ironing_spacing => "support_ironing_spacing": OrcaFloat = OrcaFloat(0.1),
            xy_hole_compensation => "xy_hole_compensation": OrcaFloat = OrcaFloat(0.0),
            xy_contour_compensation => "xy_contour_compensation": OrcaFloat = OrcaFloat(0.0),
            flush_into_objects => "flush_into_objects": OrcaBool = OrcaBool(false),
            flush_into_infill => "flush_into_infill": OrcaBool = OrcaBool(false),
            flush_into_support => "flush_into_support": OrcaBool = OrcaBool(true),
            tree_support_branch_distance => "tree_support_branch_distance": OrcaFloat = OrcaFloat(5.0),
            tree_support_tip_diameter => "tree_support_tip_diameter": OrcaFloat = OrcaFloat(0.8),
            tree_support_branch_diameter => "tree_support_branch_diameter": OrcaFloat = OrcaFloat(5.0),
            tree_support_branch_angle => "tree_support_branch_angle": OrcaFloat = OrcaFloat(40.0),
            tree_support_branch_diameter_angle => "tree_support_branch_diameter_angle": OrcaFloat = OrcaFloat(5.0),
            tree_support_angle_slow => "tree_support_angle_slow": OrcaFloat = OrcaFloat(25.0),
            tree_support_wall_count => "tree_support_wall_count": OrcaInt = OrcaInt(0),
            tree_support_auto_brim => "tree_support_auto_brim": OrcaBool = OrcaBool(true),
            tree_support_brim_width => "tree_support_brim_width": OrcaFloat = OrcaFloat(3.0),
            detect_narrow_internal_solid_infill => "detect_narrow_internal_solid_infill": OrcaBool = OrcaBool(true),
            support_bottom_interface_spacing => "support_bottom_interface_spacing": OrcaFloat = OrcaFloat(0.5),
            wall_generator => "wall_generator": ProcessPerimeterGenerator = ProcessPerimeterGenerator::Arachne,
            wall_transition_length => "wall_transition_length": Percent = Percent(100.0),
            wall_transition_filter_deviation => "wall_transition_filter_deviation": Percent = Percent(25.0),
            wall_transition_angle => "wall_transition_angle": OrcaFloat = OrcaFloat(10.0),
            wall_distribution_count => "wall_distribution_count": OrcaInt = OrcaInt(1),
            min_feature_size => "min_feature_size": Percent = Percent(25.0),
            initial_layer_min_bead_width => "initial_layer_min_bead_width": Percent = Percent(85.0),
            min_bead_width => "min_bead_width": Percent = Percent(85.0),
            wall_maximum_resolution => "wall_maximum_resolution": OrcaFloat = OrcaFloat(0.5),
            wall_maximum_deviation => "wall_maximum_deviation": OrcaFloat = OrcaFloat(0.025),
            make_overhang_printable_angle => "make_overhang_printable_angle": OrcaFloat = OrcaFloat(55.0),
            make_overhang_printable_hole_size => "make_overhang_printable_hole_size": OrcaFloat = OrcaFloat(0.0),
            tree_support_branch_distance_organic => "tree_support_branch_distance_organic": OrcaFloat = OrcaFloat(1.0),
            tree_support_top_rate => "tree_support_top_rate": Percent = Percent(30.0),
            tree_support_branch_diameter_organic => "tree_support_branch_diameter_organic": OrcaFloat = OrcaFloat(2.0),
            tree_support_branch_angle_organic => "tree_support_branch_angle_organic": OrcaFloat = OrcaFloat(40.0),
            gap_fill_target => "gap_fill_target": ProcessGapFillTarget = ProcessGapFillTarget::Nowhere,
            min_length_factor => "min_length_factor": OrcaFloat = OrcaFloat(0.5),
            default_acceleration => "default_acceleration": OrcaFloat = OrcaFloat(500.0),
            outer_wall_acceleration => "outer_wall_acceleration": OrcaFloat = OrcaFloat(500.0),
            inner_wall_acceleration => "inner_wall_acceleration": OrcaFloat = OrcaFloat(10000.0),
            top_surface_acceleration => "top_surface_acceleration": OrcaFloat = OrcaFloat(500.0),
            initial_layer_acceleration => "initial_layer_acceleration": OrcaFloat = OrcaFloat(300.0),
            bridge_acceleration => "bridge_acceleration": FloatOrPercent = FloatOrPercent::Percent(Percent(50.0)),
            travel_acceleration => "travel_acceleration": OrcaFloat = OrcaFloat(10000.0),
            sparse_infill_acceleration => "sparse_infill_acceleration": FloatOrPercent = FloatOrPercent::Percent(Percent(100.0)),
            internal_solid_infill_acceleration => "internal_solid_infill_acceleration": FloatOrPercent = FloatOrPercent::Percent(Percent(100.0)),
            default_jerk => "default_jerk": OrcaFloat = OrcaFloat(0.0),
            outer_wall_jerk => "outer_wall_jerk": OrcaFloat = OrcaFloat(9.0),
            inner_wall_jerk => "inner_wall_jerk": OrcaFloat = OrcaFloat(9.0),
            infill_jerk => "infill_jerk": OrcaFloat = OrcaFloat(9.0),
            top_surface_jerk => "top_surface_jerk": OrcaFloat = OrcaFloat(9.0),
            initial_layer_jerk => "initial_layer_jerk": OrcaFloat = OrcaFloat(9.0),
            travel_jerk => "travel_jerk": OrcaFloat = OrcaFloat(12.0),
            precise_z_height => "precise_z_height": OrcaBool = OrcaBool(false),
            default_junction_deviation => "default_junction_deviation": OrcaFloat = OrcaFloat(0.0),
            interlocking_beam => "interlocking_beam": OrcaBool = OrcaBool(false),
            interlocking_beam_width => "interlocking_beam_width": OrcaFloat = OrcaFloat(0.8),
            interlocking_orientation => "interlocking_orientation": OrcaFloat = OrcaFloat(22.5),
            interlocking_beam_layer_count => "interlocking_beam_layer_count": OrcaInt = OrcaInt(2),
            interlocking_depth => "interlocking_depth": OrcaInt = OrcaInt(2),
            interlocking_boundary_avoidance => "interlocking_boundary_avoidance": OrcaInt = OrcaInt(2),
            calib_flowrate_topinfill_special_order => "calib_flowrate_topinfill_special_order": OrcaBool = OrcaBool(false),
        }
    };
}

pub(crate) use object_option_fields;

macro_rules! declare_object_option_order {
    ($($field:ident => $key:literal: $ty:ty = $default:expr),* $(,)?) => {
        pub(crate) const OBJECT_OPTION_DECLARATION_ORDER: [&str; 126] = [$($key),*];
    };
}

object_option_fields!(declare_object_option_order);
