use std::fmt;

const MAX_CONTEXT_LINE_BYTES: usize = 160;

pub(crate) enum GeneratorKind {
    Orca,
    Ares,
}

pub(crate) fn normalize_one_generator_line(
    bytes: &[u8],
    kind: GeneratorKind,
) -> Result<Vec<u8>, String> {
    let name = match kind {
        GeneratorKind::Orca => "OrcaSlicer",
        GeneratorKind::Ares => "Ares",
    };
    let pattern = regex::Regex::new(&format!(
        r"(?m)^; generated by {name} 2\.4\.2 on \d{{4}}-\d{{2}}-\d{{2}} at \d{{2}}:\d{{2}}:\d{{2}}$"
    ))
    .unwrap();
    let text = std::str::from_utf8(bytes).map_err(|error| error.to_string())?;
    let matches = pattern.find_iter(text).collect::<Vec<_>>();
    if matches.len() != 1 {
        return Err(format!(
            "expected one {name} generator line, found {}",
            matches.len()
        ));
    }
    let text = pattern
        .replace(text, "; generated by <SLICER> 2.4.2 on <TIMESTAMP>")
        .into_owned();
    Ok(text.into_bytes())
}

pub(crate) fn normalize_uninitialized_object_ids(
    bytes: &[u8],
    object_id: u32,
) -> Result<Vec<u8>, String> {
    let pattern =
        regex::Regex::new(r"(?m)^(; (?:stop )?printing object .+ id:)\d+( copy \d+)$").unwrap();
    let text = std::str::from_utf8(bytes).map_err(|error| error.to_string())?;
    Ok(pattern
        .replace_all(text, |captures: &regex::Captures<'_>| {
            format!("{}{object_id}{}", &captures[1], &captures[2])
        })
        .into_owned()
        .into_bytes())
}

pub(crate) struct Difference {
    byte_offset: usize,
    line: usize,
    column: usize,
    expected_len: usize,
    actual_len: usize,
    context: Vec<ContextLine>,
}

struct ContextLine {
    number: usize,
    expected: Option<String>,
    actual: Option<String>,
    same: bool,
}

pub(crate) fn first_difference(expected: &[u8], actual: &[u8]) -> Option<Difference> {
    let byte_offset = expected
        .iter()
        .zip(actual)
        .position(|(expected, actual)| expected != actual)
        .or_else(|| (expected.len() != actual.len()).then(|| expected.len().min(actual.len())))?;
    let common_prefix = &expected[..byte_offset.min(expected.len())];
    let line = common_prefix.iter().filter(|byte| **byte == b'\n').count() + 1;
    let column = common_prefix
        .iter()
        .rposition(|byte| *byte == b'\n')
        .map_or(byte_offset + 1, |newline| byte_offset - newline);
    let difference_line = line - 1;
    let context_start = difference_line.saturating_sub(1);
    let context = (context_start..=difference_line + 1)
        .filter_map(|line_index| {
            let expected_line = line_at(expected, line_index);
            let actual_line = line_at(actual, line_index);
            if expected_line.is_none() && actual_line.is_none() {
                return None;
            }
            Some(ContextLine {
                number: line_index + 1,
                expected: expected_line.map(render_line),
                actual: actual_line.map(render_line),
                same: expected_line == actual_line,
            })
        })
        .collect();

    Some(Difference {
        byte_offset,
        line,
        column,
        expected_len: expected.len(),
        actual_len: actual.len(),
        context,
    })
}

fn line_at(bytes: &[u8], target: usize) -> Option<&[u8]> {
    let mut line = 0;
    let mut start = 0;
    for (index, byte) in bytes.iter().enumerate() {
        if *byte != b'\n' {
            continue;
        }
        if line == target {
            return Some(&bytes[start..index]);
        }
        line += 1;
        start = index + 1;
    }
    (line == target && start < bytes.len()).then(|| &bytes[start..])
}

fn render_line(bytes: &[u8]) -> String {
    let mut rendered = String::from("\"");
    for byte in bytes.iter().take(MAX_CONTEXT_LINE_BYTES) {
        rendered.extend(std::ascii::escape_default(*byte).map(char::from));
    }
    if bytes.len() > MAX_CONTEXT_LINE_BYTES {
        rendered.push_str("...");
    }
    rendered.push('"');
    rendered
}

impl fmt::Display for Difference {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "first difference at byte {} (line {}, column {}; expected {} bytes, actual {} bytes)",
            self.byte_offset, self.line, self.column, self.expected_len, self.actual_len
        )?;
        if !self.context.is_empty() {
            write!(formatter, "\ncontext:")?;
        }
        for line in &self.context {
            write!(formatter, "\n  line {}: ", line.number)?;
            if line.same {
                write!(formatter, "{}", line.expected.as_deref().unwrap_or("<EOF>"))?;
            } else {
                write!(
                    formatter,
                    "expected {}; actual {}",
                    line.expected.as_deref().unwrap_or("<EOF>"),
                    line.actual.as_deref().unwrap_or("<EOF>")
                )?;
            }
        }
        Ok(())
    }
}
