use crate::options::filament_config_export::FilamentConfigExports;

pub(crate) fn append_config_exports(header: &mut String, exports: &FilamentConfigExports) {
    append_config_export(
        header,
        "filament_adhesiveness_category",
        exports.filament_adhesiveness_category.as_deref(),
    );
    append_config_export(
        header,
        "cooling_tube_retraction",
        exports.cooling_tube_retraction.as_deref(),
    );
    append_config_export(
        header,
        "cooling_tube_length",
        exports.cooling_tube_length.as_deref(),
    );
    append_config_export(
        header,
        "high_current_on_filament_swap",
        exports.high_current_on_filament_swap.as_deref(),
    );
    append_config_export(
        header,
        "parking_pos_retraction",
        exports.parking_pos_retraction.as_deref(),
    );
    append_config_export(
        header,
        "extra_loading_move",
        exports.extra_loading_move.as_deref(),
    );
    append_config_export(
        header,
        "machine_load_filament_time",
        exports.machine_load_filament_time.as_deref(),
    );
    append_config_export(
        header,
        "machine_tool_change_time",
        exports.machine_tool_change_time.as_deref(),
    );
    append_config_export(
        header,
        "machine_unload_filament_time",
        exports.machine_unload_filament_time.as_deref(),
    );
    append_config_export(
        header,
        "filament_loading_speed",
        exports.filament_loading_speed.as_deref(),
    );
    append_config_export(
        header,
        "filament_loading_speed_start",
        exports.filament_loading_speed_start.as_deref(),
    );
    append_config_export(
        header,
        "filament_unloading_speed",
        exports.filament_unloading_speed.as_deref(),
    );
    append_config_export(
        header,
        "filament_unloading_speed_start",
        exports.filament_unloading_speed_start.as_deref(),
    );
    append_config_export(
        header,
        "filament_toolchange_delay",
        exports.filament_toolchange_delay.as_deref(),
    );
    append_config_export(
        header,
        "filament_cooling_moves",
        exports.filament_cooling_moves.as_deref(),
    );
    append_config_export(
        header,
        "filament_cooling_initial_speed",
        exports.filament_cooling_initial_speed.as_deref(),
    );
    append_config_export(
        header,
        "filament_minimal_purge_on_wipe_tower",
        exports.filament_minimal_purge_on_wipe_tower.as_deref(),
    );
    append_config_export(
        header,
        "filament_cooling_before_tower",
        exports.filament_cooling_before_tower.as_deref(),
    );
    append_config_export(
        header,
        "filament_tower_interface_pre_extrusion_dist",
        exports
            .filament_tower_interface_pre_extrusion_dist
            .as_deref(),
    );
    append_config_export(
        header,
        "filament_tower_interface_pre_extrusion_length",
        exports
            .filament_tower_interface_pre_extrusion_length
            .as_deref(),
    );
    append_config_export(
        header,
        "filament_tower_ironing_area",
        exports.filament_tower_ironing_area.as_deref(),
    );
    append_config_export(
        header,
        "filament_tower_interface_purge_volume",
        exports.filament_tower_interface_purge_volume.as_deref(),
    );
    append_config_export(
        header,
        "filament_tower_interface_print_temp",
        exports.filament_tower_interface_print_temp.as_deref(),
    );
    append_config_export(
        header,
        "filament_cooling_final_speed",
        exports.filament_cooling_final_speed.as_deref(),
    );
    append_config_export(
        header,
        "filament_ramming_parameters",
        exports.filament_ramming_parameters.as_deref(),
    );
    append_config_export(
        header,
        "filament_multitool_ramming",
        exports.filament_multitool_ramming.as_deref(),
    );
    append_config_export(
        header,
        "filament_multitool_ramming_volume",
        exports.filament_multitool_ramming_volume.as_deref(),
    );
    append_config_export(
        header,
        "filament_multitool_ramming_flow",
        exports.filament_multitool_ramming_flow.as_deref(),
    );
    append_config_export(
        header,
        "filament_stamping_loading_speed",
        exports.filament_stamping_loading_speed.as_deref(),
    );
    append_config_export(
        header,
        "filament_stamping_distance",
        exports.filament_stamping_distance.as_deref(),
    );
    append_config_export(
        header,
        "wipe_tower_type",
        exports.wipe_tower_type.as_deref(),
    );
    append_config_export(
        header,
        "purge_in_prime_tower",
        exports.purge_in_prime_tower.as_deref(),
    );
    append_config_export(
        header,
        "enable_filament_ramming",
        exports.enable_filament_ramming.as_deref(),
    );
    append_config_export(
        header,
        "tool_change_on_wipe_tower",
        exports.tool_change_on_wipe_tower.as_deref(),
    );
    append_config_export(
        header,
        "wipe_tower_no_sparse_layers",
        exports.wipe_tower_no_sparse_layers.as_deref(),
    );
    append_config_export(
        header,
        "support_multi_bed_types",
        exports.support_multi_bed_types.as_deref(),
    );
    append_config_export(header, "wipe_tower_x", exports.wipe_tower_x.as_deref());
    append_config_export(header, "wipe_tower_y", exports.wipe_tower_y.as_deref());
    append_config_export(
        header,
        "prime_tower_width",
        exports.prime_tower_width.as_deref(),
    );
    append_config_export(
        header,
        "wipe_tower_rotation_angle",
        exports.wipe_tower_rotation_angle.as_deref(),
    );
    append_config_export(
        header,
        "prime_tower_brim_width",
        exports.prime_tower_brim_width.as_deref(),
    );
    append_config_export(
        header,
        "wipe_tower_bridging",
        exports.wipe_tower_bridging.as_deref(),
    );
    append_config_export(
        header,
        "wipe_tower_extra_flow",
        exports.wipe_tower_extra_flow.as_deref(),
    );
    append_config_export(
        header,
        "wipe_tower_cone_angle",
        exports.wipe_tower_cone_angle.as_deref(),
    );
    append_config_export(
        header,
        "wipe_tower_extra_spacing",
        exports.wipe_tower_extra_spacing.as_deref(),
    );
    append_config_export(
        header,
        "wipe_tower_max_purge_speed",
        exports.wipe_tower_max_purge_speed.as_deref(),
    );
    append_config_export(
        header,
        "wipe_tower_wall_type",
        exports.wipe_tower_wall_type.as_deref(),
    );
    append_config_export(
        header,
        "wipe_tower_extra_rib_length",
        exports.wipe_tower_extra_rib_length.as_deref(),
    );
    append_config_export(
        header,
        "wipe_tower_rib_width",
        exports.wipe_tower_rib_width.as_deref(),
    );
    append_config_export(
        header,
        "wipe_tower_fillet_wall",
        exports.wipe_tower_fillet_wall.as_deref(),
    );
    append_config_export(
        header,
        "wipe_tower_filament",
        exports.wipe_tower_filament.as_deref(),
    );
    append_config_export(
        header,
        "small_area_infill_flow_compensation_model",
        exports.small_area_infill_flow_compensation_model.as_deref(),
    );
    append_config_export(
        header,
        "filament_colour",
        exports.filament_colour.as_deref(),
    );
    append_config_export(
        header,
        "extruder_colour",
        exports.extruder_colour.as_deref(),
    );
    append_config_export(
        header,
        "filament_multi_colour",
        exports.filament_multi_colour.as_deref(),
    );
    append_config_export(
        header,
        "filament_colour_new",
        exports.filament_colour_new.as_deref(),
    );
    append_config_export(
        header,
        "filament_colour_type",
        exports.filament_colour_type.as_deref(),
    );
    append_config_export(
        header,
        "default_filament_colour",
        exports.default_filament_colour.as_deref(),
    );
    append_config_export(header, "filament_ids", exports.filament_ids.as_deref());
    append_config_export(
        header,
        "filament_soluble",
        exports.filament_soluble.as_deref(),
    );
    append_config_export(
        header,
        "filament_is_support",
        exports.filament_is_support.as_deref(),
    );
    append_config_export(
        header,
        "filament_printable",
        exports.filament_printable.as_deref(),
    );
    append_config_export(
        header,
        "filament_change_length",
        exports.filament_change_length.as_deref(),
    );
    append_config_export(
        header,
        "required_nozzle_HRC",
        exports.required_nozzle_hrc.as_deref(),
    );
    append_config_export(header, "filament_map", exports.filament_map.as_deref());
}

fn append_config_export(header: &mut String, key: &str, value: Option<&str>) {
    if let Some(value) = value {
        header.push_str(&format!("; {key} = {value}\n"));
    }
}
