use crate::gcode_format::{format_decimal, format_decimal_list, format_pipeline_stages};
use crate::{HardwareOptions, SliceError, SliceOptions, SlicingPipeline};

const NOTES_KEY: &str = "notes";
const FILAMENT_NOTES_KEY: &str = "filament_notes";
const PRINTER_NOTES_KEY: &str = "printer_notes";
const FILAMENT_DENSITY_KEY: &str = "filament_density";
const DEFAULT_FILAMENT_DENSITIES: &[f64] = &[0.0];

pub(crate) struct HeaderConfig<'a> {
    pub(crate) layer_height: f64,
    pub(crate) initial_layer_height: f64,
    pub(crate) hardware_options: &'a HardwareOptions,
}

pub(crate) fn should_skip_header_for_btt_thumbnail(options: &SliceOptions) -> bool {
    options
        .values()
        .get("thumbnails")
        .and_then(serde_json::Value::as_str)
        .is_some_and(|thumbnails| thumbnails.contains("BTT_TFT"))
}

pub(crate) fn format_header(
    pipeline: &SlicingPipeline,
    options: &SliceOptions,
    config: HeaderConfig<'_>,
) -> Result<String, SliceError> {
    let model = pipeline.model();
    let diagnostics = pipeline.diagnostics();
    let filament_type = options.filament_type()?;
    let filament_vendor = options.filament_vendor()?;
    let filament_display_type = options.filament_type_display(0)?.displayed;
    let filament_density = filament_density_values(options)?;

    let mut header = format!(
        "; generated by Ares
; input_format = {}
; triangle_count = {}
; layer_height = {}
; initial_layer_height = {}
; nozzle_diameter = {}
; filament_diameter = {}
; filament_density = {}
; filament_type = {}
; filament_vendor = {}
; filament_display_type = {}
; min_layer_height = {}
; max_layer_height = {}
; layer_count = {}
; option_count = {}
; pipeline_stages = {}
; total_segment_count = {}
; total_contour_count = {}
; total_perimeter_count = {}
; total_infill_count = {}
; total_skirt_path_count = {}
; total_brim_path_count = {}
; total_print_path_count = {}
; total_toolpath_move_count = {}
; total_extrusion_move_count = {}
; total_speed_move_count = {}
; total_extrusion_mm = {}
; empty_layer_count = {}
",
        model.format().as_gcode_value(),
        model.triangles().len(),
        format_decimal(config.layer_height),
        format_decimal(config.initial_layer_height),
        format_decimal_list(config.hardware_options.nozzle_diameters()),
        format_decimal_list(config.hardware_options.filament_diameters()),
        format_decimal_list(&filament_density),
        filament_type,
        filament_vendor,
        filament_display_type,
        format_decimal_list(config.hardware_options.min_layer_heights()),
        format_decimal_list(config.hardware_options.max_layer_heights()),
        diagnostics.layer_count(),
        diagnostics.option_count(),
        format_pipeline_stages(diagnostics.completed_stages()),
        diagnostics.total_segment_count(),
        diagnostics.total_contour_count(),
        diagnostics.total_perimeter_count(),
        diagnostics.total_infill_count(),
        diagnostics.total_skirt_path_count(),
        diagnostics.total_brim_path_count(),
        diagnostics.total_print_path_count(),
        diagnostics.total_toolpath_move_count(),
        diagnostics.total_extrusion_move_count(),
        diagnostics.total_speed_move_count(),
        format_decimal(diagnostics.total_extrusion_mm()),
        diagnostics.empty_layer_count()
    );
    let filament_config_exports = options.filament_config_exports()?;
    crate::gcode_config_header::append_config_exports(&mut header, &filament_config_exports);
    append_scalar_notes(&mut header, options, NOTES_KEY)?;
    append_filament_notes(&mut header, options)?;
    append_scalar_notes(&mut header, options, PRINTER_NOTES_KEY)?;
    Ok(header)
}

fn filament_density_values(options: &SliceOptions) -> Result<Vec<f64>, SliceError> {
    let Some(value) = options.values().get(FILAMENT_DENSITY_KEY) else {
        return Ok(DEFAULT_FILAMENT_DENSITIES.to_vec());
    };
    let values = crate::options::parsing::parse_numeric_vector(FILAMENT_DENSITY_KEY, value)?;
    if values
        .iter()
        .all(|value| value.is_finite() && *value >= 0.0)
    {
        Ok(values)
    } else {
        Err(SliceError::InvalidInput(format!(
            "{FILAMENT_DENSITY_KEY} contains invalid value"
        )))
    }
}

fn append_scalar_notes(
    header: &mut String,
    options: &SliceOptions,
    key: &str,
) -> Result<(), SliceError> {
    let Some(value) = options.values().get(key) else {
        return Ok(());
    };
    let serde_json::Value::String(notes) = value else {
        return Err(SliceError::InvalidInput(format!("{key} must be a string")));
    };
    append_note_text(header, key, notes);
    Ok(())
}

fn append_filament_notes(header: &mut String, options: &SliceOptions) -> Result<(), SliceError> {
    let Some(value) = options.values().get(FILAMENT_NOTES_KEY) else {
        return Ok(());
    };
    match value {
        serde_json::Value::String(notes) => append_note_text(header, FILAMENT_NOTES_KEY, notes),
        serde_json::Value::Array(values) => {
            for value in values {
                let Some(notes) = value.as_str() else {
                    return Err(SliceError::InvalidInput(format!(
                        "{FILAMENT_NOTES_KEY} must contain strings"
                    )));
                };
                append_note_text(header, FILAMENT_NOTES_KEY, notes);
            }
        }
        _ => {
            return Err(SliceError::InvalidInput(format!(
                "{FILAMENT_NOTES_KEY} must be a string vector"
            )));
        }
    }
    Ok(())
}

fn append_note_text(header: &mut String, key: &str, notes: &str) {
    if notes.is_empty() {
        return;
    }
    for line in notes.lines() {
        header.push_str(&format!("; {key} = {line}\n"));
    }
}
