#[path = "ksr_fdmtest_v4/golden.rs"]
mod golden;
// Diagnostic-only parsers and behavioral tests, never acceptance fallback.
#[path = "ksr_fdmtest_v4/semantic.rs"]
mod semantic;
#[path = "ksr_fdmtest_v4/tests.rs"]
mod tests;

use std::{fs, path::PathBuf};

use jiff::civil::DateTime;
use sha2::{Digest, Sha256};

const PROJECT_SHA256: &str = "698f40f13c9075b818abedd3d10f022fbb5d8200aed48fbdde651f6bfb21b8a9";
const REFERENCE_SHA256: &str = "3f2d028f82b6a50f5244f0bfdb193370975b21c55661575edbf98d78d8aa25e4";
const NORMALIZED_REFERENCE_SHA256: &str =
    "7d75d933168d4abb959750007832e725221d1caa94ed37ff7be797f0407fbab8";

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/ksr_fdmtest_v4")
        .join(name)
}

fn project() -> Vec<u8> {
    fs::read(fixture_path("ksr_fdmtest_v4.project.3mf")).unwrap()
}

fn reference() -> Vec<u8> {
    fs::read(fixture_path("ksr_fdmtest_v4.gcode")).unwrap()
}

fn sha256(bytes: &[u8]) -> String {
    Sha256::digest(bytes)
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

fn count_bytes(haystack: &[u8], needle: &[u8]) -> usize {
    haystack
        .windows(needle.len())
        .filter(|window| *window == needle)
        .count()
}

fn compare_actual(actual: &[u8]) {
    // Normalize BOTH sides: the strict comparator must see the same
    // per-run identity class on reference and actual, or the id lines
    // can never match (reference keeps its numeric ids while the
    // actual is rewritten to <ID>).
    golden::compare_ordered_bytes_generator_only(
        &normalize_object_ids(&reference()),
        &normalize_object_ids(actual),
    )
    .unwrap_or_else(|error| panic!("{error}"));
}

/// `; (stop )?printing object <name> id:<N> copy <M>` — the id is
/// `PrintObject::get_id()` (an ObjectBase sequential counter seeded per
/// process). Two back-to-back OrcaSlicer CLI runs on the same fixture
/// produce different ids (verified 2026-09-15 on ksr_fdmtest_v4:
/// 4575657221408423936 vs the stored reference's 13965068898260364096),
/// so the semantic comparison normalizes the per-run id while the strict
/// comparator keeps comparing ids between mutations of one stream.

fn local_now_to_second() -> DateTime {
    let now = jiff::Zoned::now().datetime();
    DateTime::new(
        now.year(),
        now.month(),
        now.day(),
        now.hour(),
        now.minute(),
        now.second(),
        0,
    )
    .unwrap()
}

fn generated_at(bytes: &[u8]) -> DateTime {
    let prefix = "; generated by Ares 2.4.2 on ";
    let line = std::str::from_utf8(bytes)
        .unwrap()
        .lines()
        .find_map(|line| line.strip_prefix(prefix))
        .unwrap();
    line.replace(" at ", " ").parse().unwrap()
}
fn normalize_object_ids(bytes: &[u8]) -> Vec<u8> {
    let text = String::from_utf8_lossy(bytes);
    let object_id = regex::Regex::new(r"(; (?:stop )?printing object .+ id:)\d+( copy )").unwrap();
    object_id
        .replace_all(&text, "${1}<ID>${2}")
        .into_owned()
        .into_bytes()
}
