#[path = "ksr_fdmtest_v4/golden.rs"]
mod golden;
#[path = "ksr_fdmtest_v4/semantic.rs"]
mod semantic;

use std::{fs, io::Cursor, path::PathBuf};

use golden::{
    GeneratorKind, first_difference, normalize_one_generator_line,
    normalize_uninitialized_object_ids,
};
use jiff::civil::DateTime;
use sha2::{Digest, Sha256};

const PROJECT_SHA256: &str = "698f40f13c9075b818abedd3d10f022fbb5d8200aed48fbdde651f6bfb21b8a9";
const REFERENCE_SHA256: &str = "10aec9a156849f59929b578429a764a61453996a5834056f600c0adbb5d6a1b3";
const NORMALIZED_REFERENCE_SHA256: &str =
    "c61202df3fa26ffcb3064f2dbc02e06a89f95565b8325b31029ec4ed6cedcdc4";

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/ksr_fdmtest_v4")
        .join(name)
}

fn project() -> Vec<u8> {
    fs::read(fixture_path("ksr_fdmtest_v4.project.3mf")).unwrap()
}

fn reference() -> Vec<u8> {
    fs::read(fixture_path("ksr_fdmtest_v4.gcode")).unwrap()
}

fn sha256(bytes: &[u8]) -> String {
    Sha256::digest(bytes)
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

fn count_bytes(haystack: &[u8], needle: &[u8]) -> usize {
    haystack
        .windows(needle.len())
        .filter(|window| *window == needle)
        .count()
}

#[test]
fn fixture_contract_is_stable() {
    let project = project();
    let reference = reference();

    assert_eq!(sha256(&project), PROJECT_SHA256);
    assert_eq!(sha256(&reference), REFERENCE_SHA256);
    assert_eq!(
        zip::ZipArchive::new(Cursor::new(project)).unwrap().len(),
        15
    );
    assert_eq!(
        reference.iter().filter(|byte| **byte == b'\n').count(),
        269_330
    );
    assert_eq!(count_bytes(&reference, b"; CHANGE_LAYER\n"), 460);

    let normalized = normalize_one_generator_line(&reference, GeneratorKind::Orca).unwrap();
    assert_eq!(sha256(&normalized), NORMALIZED_REFERENCE_SHA256);
}

#[test]
fn generator_normalization_changes_only_the_validated_line() {
    let orca = b"before\n; generated by OrcaSlicer 2.4.2 on 2026-07-10 at 11:16:09\nafter\n";
    let ares = b"before\n; generated by Ares 2.4.2 on 2030-12-31 at 23:59:58\nafter\n";
    let expected = b"before\n; generated by <SLICER> 2.4.2 on <TIMESTAMP>\nafter\n";

    assert_eq!(
        normalize_one_generator_line(orca, GeneratorKind::Orca).unwrap(),
        expected
    );
    assert_eq!(
        normalize_one_generator_line(ares, GeneratorKind::Ares).unwrap(),
        expected
    );
}

#[test]
fn uninitialized_orca_object_ids_are_replaced_with_the_project_identity() {
    let input = b"; printing object part id:13965068898260364096 copy 0\n; stop printing object part id:2 copy 0\nG1 X13965068898260364096\n";
    let expected =
        b"; printing object part id:2 copy 0\n; stop printing object part id:2 copy 0\nG1 X13965068898260364096\n";

    assert_eq!(
        normalize_uninitialized_object_ids(input, 2).unwrap(),
        expected
    );
}

#[test]
fn generator_normalization_requires_exactly_one_complete_utf8_line() {
    assert_eq!(
        normalize_one_generator_line(b"no generator line\n", GeneratorKind::Orca).unwrap_err(),
        "expected one OrcaSlicer generator line, found 0"
    );
    assert_eq!(
        normalize_one_generator_line(
            b"; generated by OrcaSlicer 2.4.2 on 2026-07-10 at 11:16:09\n; generated by OrcaSlicer 2.4.2 on 2026-07-10 at 11:16:10\n",
            GeneratorKind::Orca,
        )
        .unwrap_err(),
        "expected one OrcaSlicer generator line, found 2"
    );
    assert!(
        normalize_one_generator_line(
            b"prefix ; generated by OrcaSlicer 2.4.2 on 2026-07-10 at 11:16:09\n",
            GeneratorKind::Orca,
        )
        .is_err()
    );
    assert!(normalize_one_generator_line(&[0xff], GeneratorKind::Orca).is_err());
}

#[test]
fn first_difference_reports_bounded_three_line_context() {
    let expected = b"line1\nline2\nline3\nline4\nline5\n";
    let actual = b"line1\nline2\nLINE3\nline4\nline5\n";

    let difference = first_difference(expected, actual).unwrap().to_string();

    assert_eq!(
        difference,
        "first difference at byte 12 (line 3, column 1; expected 30 bytes, actual 30 bytes)\ncontext:\n  line 2: \"line2\"\n  line 3: expected \"line3\"; actual \"LINE3\"\n  line 4: \"line4\""
    );
    assert!(first_difference(expected, expected).is_none());
}

#[test]
fn first_difference_truncates_long_context_lines() {
    let expected = format!("before\n{}x\nafter\n", "a".repeat(10_000));
    let actual = format!("before\n{}y\nafter\n", "a".repeat(10_000));

    let difference = first_difference(expected.as_bytes(), actual.as_bytes())
        .unwrap()
        .to_string();

    assert!(difference.len() < 1_024);
    assert_eq!(
        difference
            .lines()
            .filter(|line| line.starts_with("  line "))
            .count(),
        3
    );
}
#[test]
fn project_matches_orca_242_semantically() {
    let project = project();
    let temp = tempfile::tempdir().unwrap();
    let output = temp.path().join("actual.gcode");
    let before = local_now_to_second();
    assert_cmd::Command::cargo_bin("ares")
        .unwrap()
        .args([
            "slice",
            "-o",
            output.to_str().unwrap(),
            fixture_path("ksr_fdmtest_v4.project.3mf").to_str().unwrap(),
        ])
        .assert()
        .success();
    let after = local_now_to_second();
    let actual = std::fs::read(output).unwrap();
    let generated_at = generated_at(&actual);
    assert!(
        (before..=after).contains(&generated_at),
        "generator timestamp {generated_at} was outside {before}..={after}"
    );
    compare_actual(&project, &actual);
}

#[test]
#[ignore = "invoked by the Playwright browser parity test"]
fn browser_output_matches_orca_242_semantically() {
    let project = project();
    let path = std::env::var_os("ARES_BROWSER_GCODE").unwrap();
    let actual = fs::read(path).unwrap();
    compare_actual(&project, &actual);
}

fn compare_actual(project: &[u8], actual: &[u8]) {
    let project = ares_core::load_project(project).unwrap();
    let [project_object] = project.objects() else {
        panic!("KSR fixture must contain exactly one project object");
    };
    let expected = normalize_one_generator_line(&reference(), GeneratorKind::Orca).unwrap();
    let expected = normalize_uninitialized_object_ids(&expected, project_object.id()).unwrap();
    let actual = normalize_one_generator_line(actual, GeneratorKind::Ares).unwrap();
    let actual =
        normalize_uninitialized_object_ids(actual.as_slice(), project_object.id()).unwrap();
    let comparison = if std::env::var_os("ARES_BROWSER_GCODE").is_some() {
        semantic::compare_cross_target(&expected, &actual)
    } else {
        semantic::compare(&expected, &actual)
    };
    comparison.unwrap_or_else(|error| panic!("{error}"));
}

fn local_now_to_second() -> DateTime {
    let now = jiff::Zoned::now().datetime();
    DateTime::new(
        now.year(),
        now.month(),
        now.day(),
        now.hour(),
        now.minute(),
        now.second(),
        0,
    )
    .unwrap()
}

fn generated_at(bytes: &[u8]) -> DateTime {
    let prefix = "; generated by Ares 2.4.2 on ";
    let line = std::str::from_utf8(bytes)
        .unwrap()
        .lines()
        .find_map(|line| line.strip_prefix(prefix))
        .unwrap();
    line.replace(" at ", " ").parse().unwrap()
}
