use super::*;

#[tokio::test]
async fn intersecting_bed_exclude_area_rejects_slice() {
    let err = slice_with_bed_exclude_area(json!({
        "bed_exclude_area": "-0.5x-0.5,0.5x-0.5,0.5x0.5,-0.5x0.5"
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("bed_exclude_area"), "{err}");
    assert!(err.to_string().contains("intersects"), "{err}");
}

#[tokio::test]
async fn non_intersecting_bed_exclude_area_keeps_slice_output() {
    let output = slice_with_bed_exclude_area(json!({
        "bed_exclude_area": "20x20,21x20,21x21,20x21"
    }))
    .await
    .unwrap();
    let output = String::from_utf8(output).unwrap();

    assert!(output.contains("; generated by Ares"));
    assert!(output.lines().any(|line| line == "; option_count = 4"));
}

#[tokio::test]
async fn default_bed_exclude_area_is_inactive() {
    let output = slice_with_bed_exclude_area(json!({
        "bed_exclude_area": "0x0"
    }))
    .await
    .unwrap();
    let output = String::from_utf8(output).unwrap();

    assert!(output.contains("; generated by Ares"));
    assert!(output.lines().any(|line| line == "; layer_count = 2"));
}

#[tokio::test]
async fn json_point_array_bed_exclude_area_is_accepted() {
    let output = slice_with_bed_exclude_area(json!({
        "bed_exclude_area": [[20.0, 20.0], [21.0, 20.0], [21.0, 21.0], [20.0, 21.0]]
    }))
    .await
    .unwrap();
    let output = String::from_utf8(output).unwrap();

    assert!(output.contains("; generated by Ares"));
}

#[tokio::test]
async fn malformed_bed_exclude_area_reaches_slice_error() {
    for value in [
        json!("20x20,"),
        json!("20x20,not-a-point,21x21"),
        json!([[20.0], [21.0, 20.0], [21.0, 21.0]]),
        json!({"x": 20.0, "y": 20.0}),
    ] {
        let err = slice_with_bed_exclude_area(json!({
            "bed_exclude_area": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains("bed_exclude_area"), "{err}");
    }
}

async fn slice_with_bed_exclude_area(extra: serde_json::Value) -> Result<Vec<u8>, SliceError> {
    let mut options = json!({
        "sparse_infill_density": 0,
        "filament_max_volumetric_speed": 0.0,
        "slow_down_for_layer_cooling": false
    });
    let extra = extra.as_object().expect("test options must be an object");
    for (key, value) in extra {
        options[key] = value.clone();
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(options).unwrap(),
    )
    .await
}
