use super::*;
use serde_json::json;

#[tokio::test]
async fn btt_thumbnail_suppresses_generated_header_block_only() {
    let output = slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(json!({
            "thumbnails": "7x8/btt_tft",
            "sparse_infill_density": 0
        }))
        .unwrap(),
    )
    .await
    .unwrap();
    let output = String::from_utf8(output).unwrap();

    assert!(!output.contains("; generated by Ares"));
    assert!(!output.contains("; input_format = stl"));
    assert!(!output.contains("; total_print_path_count = "));
    assert!(output.contains("G21\n"));
    assert!(output.contains(";LAYER_CHANGE\n;LAYER:0\n"));
    assert!(output.lines().any(|line| line.starts_with("G1 X")));
}

#[tokio::test]
async fn non_btt_thumbnail_preserves_generated_header() {
    let output = slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(json!({
            "thumbnails": "7x8/png",
            "sparse_infill_density": 0
        }))
        .unwrap(),
    )
    .await
    .unwrap();
    let output = String::from_utf8(output).unwrap();

    assert!(output.contains("; generated by Ares"));
    assert!(output.contains("; input_format = stl"));
    assert!(output.contains("; total_print_path_count = "));
    assert!(output.contains(";LAYER_CHANGE\n;LAYER:0\n"));
}
