use super::*;

#[tokio::test]
async fn machine_start_gcode_replaces_auxiliary_fan_placeholders_before_layers() {
    let output = slice_custom_gcode_output(json!({
        "machine_start_gcode": "M900 A[max_additional_fan] B[first_x_layer_fan_speed] C[close_additional_fan_first_x_layers] D[additional_fan_full_speed_layer]",
        "additional_cooling_fan_speed": 70,
        "first_x_layer_fan_speed": 12.5,
        "close_additional_fan_first_x_layers": 3,
        "additional_fan_full_speed_layer": 8
    }))
    .await
    .unwrap();

    assert_line_before(&output, "M900 A70 B12.5 C3 D8", ";LAYER_CHANGE");
}

#[tokio::test]
async fn machine_start_gcode_keeps_unknown_placeholders() {
    let output = slice_custom_gcode_output(json!({
        "machine_start_gcode": "M900 X[unknown_placeholder] Y[max_additional_fan]",
        "additional_cooling_fan_speed": 70
    }))
    .await
    .unwrap();

    assert_line_before(&output, "M900 X[unknown_placeholder] Y70", ";LAYER_CHANGE");
}

#[tokio::test]
async fn invalid_machine_start_gcode_reaches_slice_error() {
    let err = slice_custom_gcode_output(json!({
        "machine_start_gcode": ["M900"]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("machine_start_gcode"));
}

#[tokio::test]
async fn absent_or_empty_machine_start_gcode_is_noop() {
    let absent = slice_custom_gcode_output(json!({})).await.unwrap();
    let empty = slice_custom_gcode_output(json!({
        "machine_start_gcode": ""
    }))
    .await
    .unwrap();

    assert_eq!(without_option_count(&absent), without_option_count(&empty));
}

#[tokio::test]
async fn file_start_gcode_is_emitted_before_header() {
    let output = slice_custom_gcode_output(json!({
        "file_start_gcode": ";FILE-TOP"
    }))
    .await
    .unwrap();

    assert!(output.starts_with(";FILE-TOP\n; generated by Ares"));
}

#[tokio::test]
async fn file_start_gcode_replaces_reserved_placeholders() {
    let output = slice_custom_gcode_output(json!({
        "file_start_gcode": ";TIME {print_time_sec}\n;FILAMENT {used_filament_length}"
    }))
    .await
    .unwrap();
    let lines = output.lines().take(3).collect::<Vec<_>>();

    assert_eq!(lines[2], "; generated by Ares");
    assert_two_decimal_positive_suffix(lines[0], ";TIME ");
    assert_two_decimal_non_negative_suffix(lines[1], ";FILAMENT ");
    assert!(!output.contains("@PRINT_TIME_SEC@"));
    assert!(!output.contains("@USED_FILAMENT_LENGTH@"));
}

#[tokio::test]
async fn file_start_gcode_keeps_unknown_placeholders() {
    let output = slice_custom_gcode_output(json!({
        "file_start_gcode": ";KNOWN {print_time_sec}\n;UNKNOWN {future_placeholder}"
    }))
    .await
    .unwrap();
    let lines = output.lines().take(3).collect::<Vec<_>>();

    assert_two_decimal_positive_suffix(lines[0], ";KNOWN ");
    assert_eq!(lines[1], ";UNKNOWN {future_placeholder}");
    assert_eq!(lines[2], "; generated by Ares");
    assert!(!output.contains("@PRINT_TIME_SEC@"));
}

#[tokio::test]
async fn line_numbering_applies_after_file_start_stat_placeholder_replacement() {
    let output = slice_custom_gcode_output(json!({
        "file_start_gcode": ";TIME {print_time_sec}\n;FILAMENT {used_filament_length}",
        "gcode_add_line_number": true
    }))
    .await
    .unwrap();
    let lines = output.lines().take(2).collect::<Vec<_>>();

    assert_two_decimal_positive_suffix(lines[0], "N1 ;TIME ");
    assert_two_decimal_non_negative_suffix(lines[1], "N2 ;FILAMENT ");
    assert!(!output.contains("@PRINT_TIME_SEC@"));
    assert!(!output.contains("@USED_FILAMENT_LENGTH@"));
}

#[tokio::test]
async fn file_start_gcode_rejects_invalid_values() {
    let err = slice_custom_gcode_output(json!({
        "file_start_gcode": ["; invalid"]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("file_start_gcode"));
}

#[tokio::test]
async fn file_start_gcode_absent_or_empty_is_noop() {
    let absent = slice_custom_gcode_output(json!({})).await.unwrap();
    let empty = slice_custom_gcode_output(json!({
        "file_start_gcode": ""
    }))
    .await
    .unwrap();

    assert_eq!(without_option_count(&absent), without_option_count(&empty));
}

#[tokio::test]
async fn machine_end_gcode_emits_after_completion_commands_before_m2() {
    let output = slice_custom_gcode_output(json!({
        "machine_end_gcode": ";END [layer_num] [layer_z]",
        "activate_chamber_temp_control": true,
        "chamber_temperature": 45,
        "activate_air_filtration": true,
        "activate_air_filtration_during_print": false,
        "activate_air_filtration_on_completion": true,
        "complete_print_exhaust_fan_speed": 80,
        "auxiliary_fan": true,
        "additional_cooling_fan_speed": 70,
        "close_fan_the_first_x_layers": 0
    }))
    .await
    .unwrap();

    assert_line_after(&output, ";END 2 0.4", "M141 S0;set chamber_temperature");
    assert_line_after(&output, ";END 2 0.4", "M106 P3 S204");
    assert_line_after(&output, ";END 2 0.4", "M106 P2 S0");
    assert_line_before(&output, ";END 2 0.4", "M2");
}

#[tokio::test]
async fn machine_end_gcode_replaces_brace_finish_placeholders() {
    let output = slice_custom_gcode_output(json!({
        "machine_end_gcode": ";END-BRACE {layer_num} {layer_z} {max_layer_z} {filament_extruder_id}"
    }))
    .await
    .unwrap();

    assert_line_before(&output, ";END-BRACE 2 0.4 0.4 0", "M2");
}

#[tokio::test]
async fn machine_end_gcode_replaces_bracket_finish_placeholders() {
    let output = slice_custom_gcode_output(json!({
        "machine_end_gcode": ";END-BRACKET [layer_num] [layer_z] [max_layer_z] [filament_extruder_id]"
    }))
    .await
    .unwrap();

    assert_line_before(&output, ";END-BRACKET 2 0.4 0.4 0", "M2");
}

#[tokio::test]
async fn machine_end_gcode_keeps_unknown_conditionals_and_expression_placeholders() {
    let output = slice_custom_gcode_output(json!({
        "machine_end_gcode": "{if total_toolchanges > 0}\n;END {layer_num+1} [future] [layer_num]\n{endif}"
    }))
    .await
    .unwrap();

    assert_line_before(
        &output,
        "{if total_toolchanges > 0}",
        ";END {layer_num+1} [future] 2",
    );
    assert_line_before(&output, ";END {layer_num+1} [future] 2", "{endif}");
    assert_line_before(&output, "{endif}", "M2");
}

#[tokio::test]
async fn machine_end_gcode_rejects_invalid_values() {
    let err = slice_custom_gcode_output(json!({
        "machine_end_gcode": ["; invalid"]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("machine_end_gcode"));
}

#[tokio::test]
async fn machine_end_gcode_absent_or_empty_is_noop() {
    let absent = slice_custom_gcode_output(json!({})).await.unwrap();
    let empty = slice_custom_gcode_output(json!({
        "machine_end_gcode": ""
    }))
    .await
    .unwrap();

    assert_eq!(without_option_count(&absent), without_option_count(&empty));
}

#[tokio::test]
async fn filament_end_gcode_emits_after_completion_commands_before_machine_end_gcode() {
    let output = slice_custom_gcode_output(json!({
        "filament_end_gcode": [";FILAMENT-END [layer_num] [layer_z]"],
        "machine_end_gcode": ";MACHINE-END",
        "activate_chamber_temp_control": true,
        "chamber_temperature": 45,
        "activate_air_filtration": true,
        "activate_air_filtration_during_print": false,
        "activate_air_filtration_on_completion": true,
        "complete_print_exhaust_fan_speed": 80,
        "auxiliary_fan": true,
        "additional_cooling_fan_speed": 70,
        "close_fan_the_first_x_layers": 0
    }))
    .await
    .unwrap();

    assert_line_after(
        &output,
        ";FILAMENT-END 2 0.4",
        "M141 S0;set chamber_temperature",
    );
    assert_line_after(&output, ";FILAMENT-END 2 0.4", "M106 P3 S204");
    assert_line_after(&output, ";FILAMENT-END 2 0.4", "M106 P2 S0");
    assert_line_before(&output, ";FILAMENT-END 2 0.4", ";MACHINE-END");
    assert_line_before(&output, ";MACHINE-END", "M2");
}

#[tokio::test]
async fn filament_end_gcode_emits_before_m2_without_machine_end_gcode() {
    let output = slice_custom_gcode_output(json!({
        "filament_end_gcode": ";FILAMENT-END"
    }))
    .await
    .unwrap();

    assert_line_before(&output, ";FILAMENT-END", "M2");
}

#[tokio::test]
async fn filament_end_gcode_replaces_brace_finish_placeholders() {
    let output = slice_custom_gcode_output(json!({
        "filament_end_gcode": [";FE-BRACE {layer_num} {layer_z} {max_layer_z} {filament_extruder_id}"]
    }))
    .await
    .unwrap();

    assert_line_before(&output, ";FE-BRACE 2 0.4 0.4 0", "M2");
}

#[tokio::test]
async fn filament_end_gcode_replaces_bracket_finish_placeholders() {
    let output = slice_custom_gcode_output(json!({
        "filament_end_gcode": [";FE-BRACKET [layer_num] [layer_z] [max_layer_z] [filament_extruder_id]"]
    }))
    .await
    .unwrap();

    assert_line_before(&output, ";FE-BRACKET 2 0.4 0.4 0", "M2");
}

#[tokio::test]
async fn filament_end_gcode_keeps_unknown_conditionals_and_expression_placeholders() {
    let output = slice_custom_gcode_output(json!({
        "filament_end_gcode": ["{if filament_extruder_id == 0}\n;FE {layer_num+1} [future] [layer_num]\n{endif}"]
    }))
    .await
    .unwrap();

    assert_line_before(
        &output,
        "{if filament_extruder_id == 0}",
        ";FE {layer_num+1} [future] 2",
    );
    assert_line_before(&output, ";FE {layer_num+1} [future] 2", "{endif}");
    assert_line_before(&output, "{endif}", "M2");
}

#[tokio::test]
async fn filament_end_gcode_rejects_invalid_values() {
    let err = slice_custom_gcode_output(json!({
        "filament_end_gcode": ["; ok", 7]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("filament_end_gcode"));
}

#[tokio::test]
async fn filament_end_gcode_absent_empty_and_empty_array_are_noop() {
    let absent = slice_custom_gcode_output(json!({})).await.unwrap();
    let empty = slice_custom_gcode_output(json!({
        "filament_end_gcode": ""
    }))
    .await
    .unwrap();
    let empty_array = slice_custom_gcode_output(json!({
        "filament_end_gcode": []
    }))
    .await
    .unwrap();

    assert_eq!(without_option_count(&absent), without_option_count(&empty));
    assert_eq!(
        without_option_count(&absent),
        without_option_count(&empty_array)
    );
}

async fn slice_custom_gcode_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let options = merged_options(
        json!({
            "layer_height": 0.2,
            "initial_layer_height": 0.2,
            "sparse_infill_density": 0
        }),
        extra,
    );
    slice(square_pyramid_ascii_stl(), options)
        .await
        .map(|bytes| String::from_utf8(bytes).unwrap())
}

fn without_option_count(output: &str) -> String {
    output
        .lines()
        .filter(|line| !line.starts_with("; option_count = "))
        .collect::<Vec<_>>()
        .join("\n")
}

fn assert_line_before(output: &str, first: &str, second: &str) {
    let lines = output.lines().collect::<Vec<_>>();
    let first_index = lines.iter().position(|line| *line == first).unwrap();
    let second_index = lines.iter().position(|line| *line == second).unwrap();
    assert!(
        first_index < second_index,
        "{first_index} !< {second_index}"
    );
}

fn assert_line_after(output: &str, first: &str, second: &str) {
    assert_line_before(output, second, first);
}

fn assert_two_decimal_positive_suffix(line: &str, prefix: &str) {
    let value = line.strip_prefix(prefix).unwrap();
    assert_two_decimal_number(value);
    assert!(value.parse::<f64>().unwrap() > 0.0);
}

fn assert_two_decimal_non_negative_suffix(line: &str, prefix: &str) {
    let value = line.strip_prefix(prefix).unwrap();
    assert_two_decimal_number(value);
    assert!(value.parse::<f64>().unwrap() >= 0.0);
}

fn assert_two_decimal_number(value: &str) {
    let (whole, fractional) = value.split_once('.').unwrap();
    assert!(!whole.is_empty());
    assert_eq!(fractional.len(), 2);
    value.parse::<f64>().unwrap();
}

fn merged_options(base: serde_json::Value, extra: serde_json::Value) -> SliceOptions {
    let mut base = base.as_object().unwrap().clone();
    for (key, value) in extra.as_object().unwrap() {
        base.insert(key.clone(), value.clone());
    }
    serde_json::from_value(serde_json::Value::Object(base)).unwrap()
}
