use super::*;

#[tokio::test]
async fn extruder_colour_header_reuses_filament_colour_serialization() {
    let output = extruder_colour_output(json!({
        "extruder_colour": ["#000000", "#ffffff"],
        "filament_colour": ["#111111", "#222222"]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_colour = #111111;#222222")
    );
    assert!(
        output
            .lines()
            .any(|line| line == "; extruder_colour = #111111;#222222")
    );
}

#[tokio::test]
async fn absent_extruder_colour_preserves_existing_header() {
    let output = extruder_colour_output(json!({
        "filament_colour": ["#111111", "#222222"]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_colour = #111111;#222222")
    );
    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; extruder_colour = "))
    );
}

#[tokio::test]
async fn extruder_colour_without_filament_colour_emits_no_alias() {
    let output = extruder_colour_output(json!({
        "extruder_colour": ["#000000", "#ffffff"]
    }))
    .await
    .unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; extruder_colour = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn extruder_colour_header_stays_between_filament_colour_and_multi_colour() {
    let output = extruder_colour_output(json!({
        "extruder_colour": ["#000000"],
        "filament_colour": ["#111111"],
        "filament_multi_colour": ["#333333"]
    }))
    .await
    .unwrap();

    let lines = output.lines().collect::<Vec<_>>();
    let filament_colour = line_index(&lines, "; filament_colour = #111111");
    let extruder_colour = line_index(&lines, "; extruder_colour = #111111");
    let filament_multi_colour = line_index(&lines, "; filament_multi_colour = #333333");

    assert!(filament_colour < extruder_colour);
    assert!(extruder_colour < filament_multi_colour);
}

#[tokio::test]
async fn complex_extruder_colour_header_uses_filament_colour_quoting() {
    let output = extruder_colour_output({
        let mut extra = serde_json::Map::new();
        extra.insert("extruder_colour".to_owned(), json!(["#000000"]));
        extra.insert(
            "filament_colour".to_owned(),
            serde_json::Value::Array(vec![
                json!("warm white"),
                json!("line\\nblue"),
                serde_json::Value::String("quote\"black".to_owned()),
            ]),
        );
        serde_json::Value::Object(extra)
    })
    .await
    .unwrap();

    assert!(output.lines().any(|line| {
        line == "; extruder_colour = \"warm white\";\"line\\\\nblue\";\"quote\\\"black\""
    }));
}

#[tokio::test]
async fn invalid_filament_colour_still_fails_when_extruder_colour_is_present() {
    let err = extruder_colour_output(json!({
        "extruder_colour": ["#000000"],
        "filament_colour": [7]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("filament_colour"));
}

async fn extruder_colour_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}

fn line_index(lines: &[&str], expected: &str) -> usize {
    lines.iter().position(|line| *line == expected).unwrap()
}
