use super::*;

#[tokio::test]
async fn single_true_filament_is_support_reaches_gcode_config_header() {
    let output = filament_is_support_output(json!({
        "filament_is_support": [true]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_is_support = 1")
    );
}

#[tokio::test]
async fn multiple_filament_is_support_values_reach_gcode_config_header() {
    let output = filament_is_support_output(json!({
        "filament_is_support": [true, false]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_is_support = 1,0")
    );
}

#[tokio::test]
async fn false_filament_is_support_reaches_gcode_config_header() {
    let output = filament_is_support_output(json!({
        "filament_is_support": [false]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_is_support = 0")
    );
}

#[tokio::test]
async fn absent_filament_is_support_preserves_header() {
    let output = filament_is_support_output(json!({})).await.unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; filament_is_support = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn filament_is_support_still_drives_display_type() {
    let output = filament_is_support_output(json!({
        "filament_type": ["PLA"],
        "filament_is_support": [true]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_display_type = Sup.PLA")
    );
    assert!(
        output
            .lines()
            .any(|line| line == "; filament_is_support = 1")
    );
}

#[tokio::test]
async fn invalid_filament_is_support_values_reach_slice_error() {
    for value in [
        json!(true),
        json!("true"),
        json!([1]),
        json!(["true"]),
        json!([{"value": true}]),
        json!([null]),
        serde_json::Value::Null,
    ] {
        let err = filament_is_support_output(json!({
            "filament_is_support": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains("filament_is_support"));
    }
}

#[tokio::test]
async fn invalid_filament_is_support_is_rejected_when_header_is_skipped() {
    let err = filament_is_support_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "filament_is_support": [1]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("filament_is_support"));
}

async fn filament_is_support_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
