use super::*;

#[tokio::test]
async fn single_filament_cooling_initial_speed_reaches_gcode_config_header() {
    let output = filament_cooling_initial_speed_output(json!({
        "filament_cooling_initial_speed": [2.2]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_cooling_initial_speed = 2.2")
    );
}

#[tokio::test]
async fn multiple_filament_cooling_initial_speed_values_reach_gcode_config_header() {
    let output = filament_cooling_initial_speed_output(json!({
        "filament_cooling_initial_speed": [0.0, 2.2, 3.4]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_cooling_initial_speed = 0,2.2,3.4")
    );
}

#[tokio::test]
async fn zero_filament_cooling_initial_speed_reaches_gcode_config_header() {
    let output = filament_cooling_initial_speed_output(json!({
        "filament_cooling_initial_speed": [0.0]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_cooling_initial_speed = 0")
    );
}

#[tokio::test]
async fn empty_filament_cooling_initial_speed_vector_reaches_empty_header_value() {
    let output = filament_cooling_initial_speed_output(json!({
        "filament_cooling_initial_speed": []
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_cooling_initial_speed = ")
    );
}

#[tokio::test]
async fn absent_filament_cooling_initial_speed_preserves_header() {
    let output = filament_cooling_initial_speed_output(json!({}))
        .await
        .unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; filament_cooling_initial_speed = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_filament_cooling_initial_speed_values_reach_slice_error() {
    for value in [
        json!(2.2),
        json!("2.2"),
        json!(true),
        json!({"value": 2.2}),
        json!([true]),
        json!(["2.2"]),
        json!([-0.001]),
        json!([{"value": 2.2}]),
        serde_json::Value::Null,
    ] {
        let err = filament_cooling_initial_speed_output(json!({
            "filament_cooling_initial_speed": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains("filament_cooling_initial_speed"));
    }
}

#[tokio::test]
async fn invalid_filament_cooling_initial_speed_is_rejected_when_header_is_skipped() {
    let err = filament_cooling_initial_speed_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "filament_cooling_initial_speed": [-0.001]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("filament_cooling_initial_speed"));
}

async fn filament_cooling_initial_speed_output(
    extra: serde_json::Value,
) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
