use super::*;

#[tokio::test]
async fn single_filament_cooling_moves_reaches_gcode_config_header() {
    let output = filament_cooling_moves_output(json!({
        "filament_cooling_moves": [4]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_cooling_moves = 4")
    );
}

#[tokio::test]
async fn multiple_filament_cooling_moves_values_reach_gcode_config_header() {
    let output = filament_cooling_moves_output(json!({
        "filament_cooling_moves": [0, 4, 20]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_cooling_moves = 0,4,20")
    );
}

#[tokio::test]
async fn zero_filament_cooling_moves_reaches_gcode_config_header() {
    let output = filament_cooling_moves_output(json!({
        "filament_cooling_moves": [0]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_cooling_moves = 0")
    );
}

#[tokio::test]
async fn empty_filament_cooling_moves_vector_reaches_empty_header_value() {
    let output = filament_cooling_moves_output(json!({
        "filament_cooling_moves": []
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_cooling_moves = ")
    );
}

#[tokio::test]
async fn absent_filament_cooling_moves_preserves_header() {
    let output = filament_cooling_moves_output(json!({})).await.unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; filament_cooling_moves = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_filament_cooling_moves_values_reach_slice_error() {
    for value in [
        json!(4),
        json!("4"),
        json!(true),
        json!({"value": 4}),
        json!([true]),
        json!(["4"]),
        json!([-1]),
        json!([21]),
        json!([4.5]),
        json!([2147483648_i64]),
        json!([{"value": 4}]),
        serde_json::Value::Null,
    ] {
        let err = filament_cooling_moves_output(json!({
            "filament_cooling_moves": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains("filament_cooling_moves"));
    }
}

#[tokio::test]
async fn invalid_filament_cooling_moves_is_rejected_when_header_is_skipped() {
    let err = filament_cooling_moves_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "filament_cooling_moves": [21]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("filament_cooling_moves"));
}

async fn filament_cooling_moves_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
