use super::*;

#[tokio::test]
async fn zero_filament_adhesiveness_category_reaches_gcode_config_header() {
    let output = filament_adhesiveness_category_output(json!({
        "filament_adhesiveness_category": [0]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_adhesiveness_category = 0")
    );
}

#[tokio::test]
async fn multiple_filament_adhesiveness_category_values_reach_gcode_config_header() {
    let output = filament_adhesiveness_category_output(json!({
        "filament_adhesiveness_category": [0, 2, 7]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_adhesiveness_category = 0,2,7")
    );
}

#[tokio::test]
async fn absent_filament_adhesiveness_category_preserves_header() {
    let output = filament_adhesiveness_category_output(json!({}))
        .await
        .unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; filament_adhesiveness_category = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_filament_adhesiveness_category_values_reach_slice_error() {
    for value in [
        json!(0),
        json!("0"),
        json!([true]),
        json!(["0"]),
        json!([-1]),
        json!([1.5]),
        json!([2147483648_i64]),
        serde_json::Value::Null,
    ] {
        let err = filament_adhesiveness_category_output(json!({
            "filament_adhesiveness_category": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains("filament_adhesiveness_category"));
    }
}

#[tokio::test]
async fn invalid_filament_adhesiveness_category_is_rejected_when_header_is_skipped() {
    let err = filament_adhesiveness_category_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "filament_adhesiveness_category": [-1]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("filament_adhesiveness_category"));
}

async fn filament_adhesiveness_category_output(
    extra: serde_json::Value,
) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
