use super::*;

#[tokio::test]
async fn single_filament_map_reaches_gcode_config_header() {
    let output = filament_map_output(json!({
        "filament_map": [1]
    }))
    .await
    .unwrap();

    assert!(output.lines().any(|line| line == "; filament_map = 1"));
}

#[tokio::test]
async fn multiple_filament_map_values_reach_gcode_config_header() {
    let output = filament_map_output(json!({
        "filament_map": [2, 1, 3]
    }))
    .await
    .unwrap();

    assert!(output.lines().any(|line| line == "; filament_map = 2,1,3"));
}

#[tokio::test]
async fn filament_map_preserves_zero_and_negative_values_from_config_serialization() {
    let output = filament_map_output(json!({
        "filament_map": [0, -1]
    }))
    .await
    .unwrap();

    assert!(output.lines().any(|line| line == "; filament_map = 0,-1"));
}

#[tokio::test]
async fn absent_filament_map_preserves_header() {
    let output = filament_map_output(json!({})).await.unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; filament_map = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_filament_map_values_reach_slice_error() {
    for value in [
        json!(1),
        json!("1"),
        json!([true]),
        json!(["1"]),
        json!([1.5]),
        json!([2147483648_i64]),
        serde_json::Value::Null,
    ] {
        let err = filament_map_output(json!({
            "filament_map": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains("filament_map"));
    }
}

#[tokio::test]
async fn invalid_filament_map_is_rejected_when_header_is_skipped() {
    let err = filament_map_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "filament_map": [1.5]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("filament_map"));
}

async fn filament_map_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
