use super::*;

#[tokio::test]
async fn single_true_filament_soluble_reaches_gcode_config_header() {
    let output = filament_soluble_output(json!({
        "filament_soluble": [true]
    }))
    .await
    .unwrap();

    assert!(output.lines().any(|line| line == "; filament_soluble = 1"));
}

#[tokio::test]
async fn multiple_filament_soluble_values_reach_gcode_config_header() {
    let output = filament_soluble_output(json!({
        "filament_soluble": [true, false]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_soluble = 1,0")
    );
}

#[tokio::test]
async fn false_filament_soluble_reaches_gcode_config_header() {
    let output = filament_soluble_output(json!({
        "filament_soluble": [false]
    }))
    .await
    .unwrap();

    assert!(output.lines().any(|line| line == "; filament_soluble = 0"));
}

#[tokio::test]
async fn absent_filament_soluble_preserves_header() {
    let output = filament_soluble_output(json!({})).await.unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; filament_soluble = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_filament_soluble_values_reach_slice_error() {
    for value in [json!(true), json!("1"), json!([1]), json!(["true"])] {
        let err = filament_soluble_output(json!({
            "filament_soluble": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains("filament_soluble"));
    }
}

#[tokio::test]
async fn invalid_filament_soluble_is_rejected_when_header_is_skipped() {
    let err = filament_soluble_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "filament_soluble": [1]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("filament_soluble"));
}

async fn filament_soluble_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
