use super::*;

const FILAMENT_STAMPING_KEYS: [&str; 2] = [
    "filament_stamping_loading_speed",
    "filament_stamping_distance",
];

#[tokio::test]
async fn filament_stamping_values_reach_gcode_config_header() {
    let output = filament_stamping_output(json!({
        "filament_stamping_loading_speed": [1.5],
        "filament_stamping_distance": [12.25]
    }))
    .await
    .unwrap();

    for expected in [
        "; filament_stamping_loading_speed = 1.5",
        "; filament_stamping_distance = 12.25",
    ] {
        assert!(output.lines().any(|line| line == expected), "{expected}");
    }
}

#[tokio::test]
async fn multiple_filament_stamping_values_reach_gcode_config_header() {
    let output = filament_stamping_output(json!({
        "filament_stamping_loading_speed": [0.0, 1.5, 3.25],
        "filament_stamping_distance": [0.0, 12.25]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_stamping_loading_speed = 0,1.5,3.25")
    );
    assert!(
        output
            .lines()
            .any(|line| line == "; filament_stamping_distance = 0,12.25")
    );
}

#[tokio::test]
async fn zero_filament_stamping_values_reach_gcode_config_header() {
    let output = filament_stamping_output(json!({
        "filament_stamping_loading_speed": [0.0],
        "filament_stamping_distance": [0.0]
    }))
    .await
    .unwrap();

    for expected in [
        "; filament_stamping_loading_speed = 0",
        "; filament_stamping_distance = 0",
    ] {
        assert!(output.lines().any(|line| line == expected), "{expected}");
    }
}

#[tokio::test]
async fn empty_filament_stamping_vectors_reach_empty_header_values() {
    let output = filament_stamping_output(json!({
        "filament_stamping_loading_speed": [],
        "filament_stamping_distance": []
    }))
    .await
    .unwrap();

    for expected in [
        "; filament_stamping_loading_speed = ",
        "; filament_stamping_distance = ",
    ] {
        assert!(output.lines().any(|line| line == expected), "{expected}");
    }
}

#[tokio::test]
async fn filament_stamping_follows_multitool_ramming_flow_in_header_order() {
    let output = filament_stamping_output(json!({
        "filament_multitool_ramming_flow": [8.25],
        "filament_stamping_loading_speed": [1.5],
        "filament_stamping_distance": [12.25],
        "filament_colour": ["#123456"]
    }))
    .await
    .unwrap();
    let lines = output.lines().collect::<Vec<_>>();
    let ramming_flow_index = lines
        .iter()
        .position(|line| *line == "; filament_multitool_ramming_flow = 8.25")
        .unwrap();

    assert_eq!(
        lines.get(ramming_flow_index + 1),
        Some(&"; filament_stamping_loading_speed = 1.5")
    );
    assert_eq!(
        lines.get(ramming_flow_index + 2),
        Some(&"; filament_stamping_distance = 12.25")
    );
    assert_eq!(
        lines.get(ramming_flow_index + 3),
        Some(&"; filament_colour = #123456")
    );
}

#[tokio::test]
async fn absent_filament_stamping_values_preserve_header() {
    let output = filament_stamping_output(json!({})).await.unwrap();

    for key in FILAMENT_STAMPING_KEYS {
        assert!(
            !output
                .lines()
                .any(|line| line.starts_with(&format!("; {key} = "))),
            "{key}"
        );
    }
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_filament_stamping_values_reach_slice_error() {
    for (key, value) in [
        ("filament_stamping_loading_speed", json!(1.5)),
        ("filament_stamping_loading_speed", json!("1.5")),
        ("filament_stamping_loading_speed", json!([-0.001])),
        ("filament_stamping_loading_speed", json!([true])),
        ("filament_stamping_loading_speed", json!([{"value": 1.5}])),
        ("filament_stamping_loading_speed", serde_json::Value::Null),
        ("filament_stamping_distance", json!(12.25)),
        ("filament_stamping_distance", json!("12.25")),
        ("filament_stamping_distance", json!([-0.001])),
        ("filament_stamping_distance", json!([true])),
        ("filament_stamping_distance", json!({"value": 12.25})),
        ("filament_stamping_distance", serde_json::Value::Null),
    ] {
        let err = filament_stamping_output(json!({
            key: value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains(key));
    }
}

#[tokio::test]
async fn invalid_filament_stamping_is_rejected_when_header_is_skipped() {
    let err = filament_stamping_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "filament_stamping_distance": [-0.001]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("filament_stamping_distance"));
}

async fn filament_stamping_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
