use super::*;

#[tokio::test]
async fn single_filament_tower_interface_pre_extrusion_dist_reaches_gcode_config_header() {
    let output = filament_tower_interface_pre_extrusion_dist_output(json!({
        "filament_tower_interface_pre_extrusion_dist": [10.0]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_tower_interface_pre_extrusion_dist = 10")
    );
}

#[tokio::test]
async fn multiple_filament_tower_interface_pre_extrusion_dist_values_reach_gcode_config_header() {
    let output = filament_tower_interface_pre_extrusion_dist_output(json!({
        "filament_tower_interface_pre_extrusion_dist": [0.0, 10.0, 12.5]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_tower_interface_pre_extrusion_dist = 0,10,12.5")
    );
}

#[tokio::test]
async fn zero_filament_tower_interface_pre_extrusion_dist_reaches_gcode_config_header() {
    let output = filament_tower_interface_pre_extrusion_dist_output(json!({
        "filament_tower_interface_pre_extrusion_dist": [0.0]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_tower_interface_pre_extrusion_dist = 0")
    );
}

#[tokio::test]
async fn empty_filament_tower_interface_pre_extrusion_dist_vector_reaches_empty_header_value() {
    let output = filament_tower_interface_pre_extrusion_dist_output(json!({
        "filament_tower_interface_pre_extrusion_dist": []
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_tower_interface_pre_extrusion_dist = ")
    );
}

#[tokio::test]
async fn filament_tower_interface_pre_extrusion_dist_sits_between_cooling_before_tower_and_final_speed()
 {
    let output = filament_tower_interface_pre_extrusion_dist_output(json!({
        "filament_minimal_purge_on_wipe_tower": [15.0],
        "filament_cooling_before_tower": [10.0],
        "filament_tower_interface_pre_extrusion_dist": [8.5],
        "filament_cooling_final_speed": [3.4]
    }))
    .await
    .unwrap();
    let lines = output.lines().collect::<Vec<_>>();
    let minimal_purge_index = lines
        .iter()
        .position(|line| *line == "; filament_minimal_purge_on_wipe_tower = 15")
        .unwrap();

    assert_eq!(
        lines.get(minimal_purge_index + 1),
        Some(&"; filament_cooling_before_tower = 10")
    );
    assert_eq!(
        lines.get(minimal_purge_index + 2),
        Some(&"; filament_tower_interface_pre_extrusion_dist = 8.5")
    );
    assert_eq!(
        lines.get(minimal_purge_index + 3),
        Some(&"; filament_cooling_final_speed = 3.4")
    );
}

#[tokio::test]
async fn absent_filament_tower_interface_pre_extrusion_dist_preserves_header() {
    let output = filament_tower_interface_pre_extrusion_dist_output(json!({}))
        .await
        .unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; filament_tower_interface_pre_extrusion_dist = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_filament_tower_interface_pre_extrusion_dist_values_reach_slice_error() {
    for value in [
        json!(10.0),
        json!("10"),
        json!(true),
        json!({"value": 10.0}),
        json!([true]),
        json!(["10"]),
        json!([-0.001]),
        json!([{"value": 10.0}]),
        serde_json::Value::Null,
    ] {
        let err = filament_tower_interface_pre_extrusion_dist_output(json!({
            "filament_tower_interface_pre_extrusion_dist": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(
            err.to_string()
                .contains("filament_tower_interface_pre_extrusion_dist")
        );
    }
}

#[tokio::test]
async fn invalid_filament_tower_interface_pre_extrusion_dist_is_rejected_when_header_is_skipped() {
    let err = filament_tower_interface_pre_extrusion_dist_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "filament_tower_interface_pre_extrusion_dist": [-0.001]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(
        err.to_string()
            .contains("filament_tower_interface_pre_extrusion_dist")
    );
}

async fn filament_tower_interface_pre_extrusion_dist_output(
    extra: serde_json::Value,
) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
