use super::*;

#[tokio::test]
async fn single_filament_toolchange_delay_reaches_gcode_config_header() {
    let output = filament_toolchange_delay_output(json!({
        "filament_toolchange_delay": [1.5]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_toolchange_delay = 1.5")
    );
}

#[tokio::test]
async fn multiple_filament_toolchange_delay_values_reach_gcode_config_header() {
    let output = filament_toolchange_delay_output(json!({
        "filament_toolchange_delay": [0.0, 2.25, 3.5]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_toolchange_delay = 0,2.25,3.5")
    );
}

#[tokio::test]
async fn zero_filament_toolchange_delay_reaches_gcode_config_header() {
    let output = filament_toolchange_delay_output(json!({
        "filament_toolchange_delay": [0.0]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_toolchange_delay = 0")
    );
}

#[tokio::test]
async fn empty_filament_toolchange_delay_vector_reaches_empty_header_value() {
    let output = filament_toolchange_delay_output(json!({
        "filament_toolchange_delay": []
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_toolchange_delay = ")
    );
}

#[tokio::test]
async fn absent_filament_toolchange_delay_preserves_header() {
    let output = filament_toolchange_delay_output(json!({})).await.unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; filament_toolchange_delay = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_filament_toolchange_delay_values_reach_slice_error() {
    for value in [
        json!(1.5),
        json!("1.5"),
        json!([true]),
        json!(["1.5"]),
        json!([-0.001]),
        json!([{"value": 1.5}]),
        serde_json::Value::Null,
    ] {
        let err = filament_toolchange_delay_output(json!({
            "filament_toolchange_delay": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains("filament_toolchange_delay"));
    }
}

#[tokio::test]
async fn invalid_filament_toolchange_delay_is_rejected_when_header_is_skipped() {
    let err = filament_toolchange_delay_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "filament_toolchange_delay": [-0.001]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("filament_toolchange_delay"));
}

async fn filament_toolchange_delay_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
