use super::*;

const FILAMENT_LOAD_UNLOAD_SPEED_KEYS: [&str; 4] = [
    "filament_loading_speed",
    "filament_loading_speed_start",
    "filament_unloading_speed",
    "filament_unloading_speed_start",
];

#[tokio::test]
async fn filament_load_unload_speeds_reach_gcode_config_header() {
    let output = filament_load_unload_speed_output(json!({
        "filament_loading_speed": [28.0],
        "filament_loading_speed_start": [3.0],
        "filament_unloading_speed": [90.0],
        "filament_unloading_speed_start": [100.0]
    }))
    .await
    .unwrap();

    for expected in [
        "; filament_loading_speed = 28",
        "; filament_loading_speed_start = 3",
        "; filament_unloading_speed = 90",
        "; filament_unloading_speed_start = 100",
    ] {
        assert!(output.lines().any(|line| line == expected), "{expected}");
    }
}

#[tokio::test]
async fn multiple_filament_load_unload_speed_values_reach_gcode_config_header() {
    let output = filament_load_unload_speed_output(json!({
        "filament_loading_speed": [28.0, 32.5, 0.125],
        "filament_unloading_speed": [90.0, 80.5]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_loading_speed = 28,32.5,0.125")
    );
    assert!(
        output
            .lines()
            .any(|line| line == "; filament_unloading_speed = 90,80.5")
    );
}

#[tokio::test]
async fn zero_filament_load_unload_speed_reaches_gcode_config_header() {
    let output = filament_load_unload_speed_output(json!({
        "filament_loading_speed_start": [0.0]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_loading_speed_start = 0")
    );
}

#[tokio::test]
async fn empty_filament_load_unload_speed_vector_reaches_empty_header_value() {
    let output = filament_load_unload_speed_output(json!({
        "filament_loading_speed": []
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_loading_speed = ")
    );
}

#[tokio::test]
async fn absent_filament_load_unload_speeds_preserve_header() {
    let output = filament_load_unload_speed_output(json!({})).await.unwrap();

    for key in FILAMENT_LOAD_UNLOAD_SPEED_KEYS {
        assert!(
            !output
                .lines()
                .any(|line| line.starts_with(&format!("; {key} = "))),
            "{key}"
        );
    }
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_filament_load_unload_speed_values_reach_slice_error() {
    for (key, value) in [
        ("filament_loading_speed", json!(28.0)),
        ("filament_loading_speed_start", json!("3")),
        ("filament_unloading_speed", json!([true])),
        ("filament_unloading_speed_start", json!(["100"])),
        ("filament_loading_speed", json!([-0.001])),
        ("filament_unloading_speed", json!([{"value": 90.0}])),
        ("filament_loading_speed_start", serde_json::Value::Null),
    ] {
        let err = filament_load_unload_speed_output(json!({
            key: value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains(key));
    }
}

#[tokio::test]
async fn invalid_filament_load_unload_speed_is_rejected_when_header_is_skipped() {
    let err = filament_load_unload_speed_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "filament_unloading_speed": [-0.001]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("filament_unloading_speed"));
}

async fn filament_load_unload_speed_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
