use super::*;

#[tokio::test]
async fn single_filament_tower_ironing_area_reaches_gcode_config_header() {
    let output = filament_tower_ironing_area_output(json!({
        "filament_tower_ironing_area": [4.0]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_tower_ironing_area = 4")
    );
}

#[tokio::test]
async fn multiple_filament_tower_ironing_area_values_reach_gcode_config_header() {
    let output = filament_tower_ironing_area_output(json!({
        "filament_tower_ironing_area": [0.0, 4.0, 6.25]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_tower_ironing_area = 0,4,6.25")
    );
}

#[tokio::test]
async fn zero_filament_tower_ironing_area_reaches_gcode_config_header() {
    let output = filament_tower_ironing_area_output(json!({
        "filament_tower_ironing_area": [0.0]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_tower_ironing_area = 0")
    );
}

#[tokio::test]
async fn empty_filament_tower_ironing_area_vector_reaches_empty_header_value() {
    let output = filament_tower_ironing_area_output(json!({
        "filament_tower_ironing_area": []
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_tower_ironing_area = ")
    );
}

#[tokio::test]
async fn filament_tower_ironing_area_sits_between_pre_extrusion_length_and_final_speed() {
    let output = filament_tower_ironing_area_output(json!({
        "filament_tower_interface_pre_extrusion_dist": [8.5],
        "filament_tower_interface_pre_extrusion_length": [0.75],
        "filament_tower_ironing_area": [4.0],
        "filament_cooling_final_speed": [3.4]
    }))
    .await
    .unwrap();
    let lines = output.lines().collect::<Vec<_>>();
    let dist_index = lines
        .iter()
        .position(|line| *line == "; filament_tower_interface_pre_extrusion_dist = 8.5")
        .unwrap();

    assert_eq!(
        lines.get(dist_index + 1),
        Some(&"; filament_tower_interface_pre_extrusion_length = 0.75")
    );
    assert_eq!(
        lines.get(dist_index + 2),
        Some(&"; filament_tower_ironing_area = 4")
    );
    assert_eq!(
        lines.get(dist_index + 3),
        Some(&"; filament_cooling_final_speed = 3.4")
    );
}

#[tokio::test]
async fn absent_filament_tower_ironing_area_preserves_header() {
    let output = filament_tower_ironing_area_output(json!({})).await.unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; filament_tower_ironing_area = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_filament_tower_ironing_area_values_reach_slice_error() {
    for value in [
        json!(4.0),
        json!("4"),
        json!(true),
        json!({"value": 4.0}),
        json!([true]),
        json!(["4"]),
        json!([-0.001]),
        json!([{"value": 4.0}]),
        serde_json::Value::Null,
    ] {
        let err = filament_tower_ironing_area_output(json!({
            "filament_tower_ironing_area": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains("filament_tower_ironing_area"));
    }
}

#[tokio::test]
async fn invalid_filament_tower_ironing_area_is_rejected_when_header_is_skipped() {
    let err = filament_tower_ironing_area_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "filament_tower_ironing_area": [-0.001]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("filament_tower_ironing_area"));
}

async fn filament_tower_ironing_area_output(
    extra: serde_json::Value,
) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
