use super::*;

#[tokio::test]
async fn filament_colour_reaches_gcode_config_header() {
    let output = filament_colour_output(json!({
        "filament_colour": ["#111111", "#222222"]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_colour = #111111;#222222")
    );
}

#[tokio::test]
async fn absent_filament_colour_preserves_header() {
    let output = filament_colour_output(json!({})).await.unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; filament_colour = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn complex_filament_colour_values_use_orca_string_serialization() {
    let output = filament_colour_output({
        let mut extra = serde_json::Map::new();
        extra.insert(
            "filament_colour".to_owned(),
            serde_json::Value::Array(vec![
                json!("warm white"),
                json!("line\\nblue"),
                serde_json::Value::String("quote\"black".to_owned()),
            ]),
        );
        serde_json::Value::Object(extra)
    })
    .await
    .unwrap();

    assert!(
        output.lines().any(|line| line
            == "; filament_colour = \"warm white\";\"line\\\\nblue\";\"quote\\\"black\"")
    );
}

#[tokio::test]
async fn empty_single_filament_colour_is_quoted_like_orca() {
    let output = filament_colour_output(json!({
        "filament_colour": [""]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_colour = \"\"")
    );
}

#[tokio::test]
async fn invalid_filament_colour_values_reach_slice_error() {
    for value in [json!("#111111"), json!([7]), json!([true])] {
        let err = filament_colour_output(json!({
            "filament_colour": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains("filament_colour"));
    }
}

#[tokio::test]
async fn invalid_filament_colour_is_rejected_when_header_is_skipped() {
    let err = filament_colour_output(json!({
        "thumbnails": "7x8/btt_tft",
        "filament_colour": [7]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("filament_colour"));
}

async fn filament_colour_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
