use super::*;

#[tokio::test]
async fn single_filament_tower_interface_print_temp_reaches_gcode_config_header() {
    let output = filament_tower_interface_print_temp_output(json!({
        "filament_tower_interface_print_temp": [220]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_tower_interface_print_temp = 220")
    );
}

#[tokio::test]
async fn sentinel_filament_tower_interface_print_temp_reaches_gcode_config_header() {
    let output = filament_tower_interface_print_temp_output(json!({
        "filament_tower_interface_print_temp": [-1]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_tower_interface_print_temp = -1")
    );
}

#[tokio::test]
async fn multiple_filament_tower_interface_print_temp_values_reach_gcode_config_header() {
    let output = filament_tower_interface_print_temp_output(json!({
        "filament_tower_interface_print_temp": [-1, 0, 220, 235]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_tower_interface_print_temp = -1,0,220,235")
    );
}

#[tokio::test]
async fn empty_filament_tower_interface_print_temp_vector_reaches_empty_header_value() {
    let output = filament_tower_interface_print_temp_output(json!({
        "filament_tower_interface_print_temp": []
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_tower_interface_print_temp = ")
    );
}

#[tokio::test]
async fn filament_tower_interface_print_temp_sits_between_purge_volume_and_final_speed() {
    let output = filament_tower_interface_print_temp_output(json!({
        "filament_tower_ironing_area": [4.0],
        "filament_tower_interface_purge_volume": [20.0],
        "filament_tower_interface_print_temp": [220],
        "filament_cooling_final_speed": [3.4]
    }))
    .await
    .unwrap();
    let lines = output.lines().collect::<Vec<_>>();
    let ironing_index = lines
        .iter()
        .position(|line| *line == "; filament_tower_ironing_area = 4")
        .unwrap();

    assert_eq!(
        lines.get(ironing_index + 1),
        Some(&"; filament_tower_interface_purge_volume = 20")
    );
    assert_eq!(
        lines.get(ironing_index + 2),
        Some(&"; filament_tower_interface_print_temp = 220")
    );
    assert_eq!(
        lines.get(ironing_index + 3),
        Some(&"; filament_cooling_final_speed = 3.4")
    );
}

#[tokio::test]
async fn absent_filament_tower_interface_print_temp_preserves_header() {
    let output = filament_tower_interface_print_temp_output(json!({}))
        .await
        .unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; filament_tower_interface_print_temp = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_filament_tower_interface_print_temp_values_reach_slice_error() {
    for value in [
        json!(220),
        json!(220.5),
        json!("220"),
        json!(true),
        json!({"value": 220}),
        json!([220.5]),
        json!([true]),
        json!(["220"]),
        json!([-2]),
        json!([{"value": 220}]),
        serde_json::Value::Null,
    ] {
        let err = filament_tower_interface_print_temp_output(json!({
            "filament_tower_interface_print_temp": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(
            err.to_string()
                .contains("filament_tower_interface_print_temp")
        );
    }
}

#[tokio::test]
async fn invalid_filament_tower_interface_print_temp_is_rejected_when_header_is_skipped() {
    let err = filament_tower_interface_print_temp_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "filament_tower_interface_print_temp": [-2]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(
        err.to_string()
            .contains("filament_tower_interface_print_temp")
    );
}

async fn filament_tower_interface_print_temp_output(
    extra: serde_json::Value,
) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
