use super::*;

#[tokio::test]
async fn single_filament_ramming_parameters_reaches_gcode_config_header() {
    let output = filament_ramming_parameters_output(json!({
        "filament_ramming_parameters": ["120 100 6.6 6.8"]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_ramming_parameters = \"120 100 6.6 6.8\"")
    );
}

#[tokio::test]
async fn multiple_filament_ramming_parameters_reach_gcode_config_header() {
    let output = filament_ramming_parameters_output(json!({
        "filament_ramming_parameters": ["ram-a", "ram-b"]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_ramming_parameters = ram-a;ram-b")
    );
}

#[tokio::test]
async fn empty_filament_ramming_parameters_vector_reaches_empty_header_value() {
    let output = filament_ramming_parameters_output(json!({
        "filament_ramming_parameters": []
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_ramming_parameters = ")
    );
}

#[tokio::test]
async fn empty_single_filament_ramming_parameter_is_quoted_like_orca() {
    let output = filament_ramming_parameters_output(json!({
        "filament_ramming_parameters": [""]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_ramming_parameters = \"\"")
    );
}

#[tokio::test]
async fn complex_filament_ramming_parameters_use_orca_string_serialization() {
    let output = filament_ramming_parameters_output({
        let mut extra = serde_json::Map::new();
        extra.insert(
            "filament_ramming_parameters".to_owned(),
            serde_json::Value::Array(vec![
                json!("120 100"),
                json!("segment;semi"),
                json!("line\\nram"),
                serde_json::Value::String("quote\"ram".to_owned()),
            ]),
        );
        serde_json::Value::Object(extra)
    })
    .await
    .unwrap();

    assert!(output.lines().any(|line| {
        line == "; filament_ramming_parameters = \"120 100\";segment;semi;\"line\\\\nram\";\"quote\\\"ram\""
    }));
}

#[tokio::test]
async fn filament_ramming_parameters_follows_final_speed_in_header_order() {
    let output = filament_ramming_parameters_output(json!({
        "filament_tower_interface_print_temp": [220],
        "filament_cooling_final_speed": [3.4],
        "filament_ramming_parameters": ["120 100"]
    }))
    .await
    .unwrap();
    let lines = output.lines().collect::<Vec<_>>();
    let print_temp_index = lines
        .iter()
        .position(|line| *line == "; filament_tower_interface_print_temp = 220")
        .unwrap();

    assert_eq!(
        lines.get(print_temp_index + 1),
        Some(&"; filament_cooling_final_speed = 3.4")
    );
    assert_eq!(
        lines.get(print_temp_index + 2),
        Some(&"; filament_ramming_parameters = \"120 100\"")
    );
}

#[tokio::test]
async fn absent_filament_ramming_parameters_preserves_header() {
    let output = filament_ramming_parameters_output(json!({})).await.unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; filament_ramming_parameters = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_filament_ramming_parameters_values_reach_slice_error() {
    for value in [
        json!("120 100"),
        json!(120),
        json!(true),
        json!({"value": "120 100"}),
        json!([120]),
        json!([true]),
        json!([{"value": "120 100"}]),
        serde_json::Value::Null,
    ] {
        let err = filament_ramming_parameters_output(json!({
            "filament_ramming_parameters": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains("filament_ramming_parameters"));
    }
}

#[tokio::test]
async fn invalid_filament_ramming_parameters_is_rejected_when_header_is_skipped() {
    let err = filament_ramming_parameters_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "filament_ramming_parameters": [120]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("filament_ramming_parameters"));
}

async fn filament_ramming_parameters_output(
    extra: serde_json::Value,
) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
