use super::*;

#[tokio::test]
async fn single_filament_id_reaches_gcode_config_header() {
    let output = filament_ids_output(json!({
        "filament_ids": ["PLA-ID"]
    }))
    .await
    .unwrap();

    assert!(output.lines().any(|line| line == "; filament_ids = PLA-ID"));
}

#[tokio::test]
async fn multiple_filament_ids_reach_gcode_config_header() {
    let output = filament_ids_output(json!({
        "filament_ids": ["PLA-ID", "PETG-ID"]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_ids = PLA-ID;PETG-ID")
    );
}

#[tokio::test]
async fn absent_filament_ids_preserves_header() {
    let output = filament_ids_output(json!({})).await.unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; filament_ids = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn filament_ids_empty_single_value_is_quoted_like_orca() {
    let output = filament_ids_output(json!({
        "filament_ids": [""]
    }))
    .await
    .unwrap();

    assert!(output.lines().any(|line| line == "; filament_ids = \"\""));
}

#[tokio::test]
async fn complex_filament_ids_values_use_orca_string_serialization() {
    let output = filament_ids_output({
        let mut extra = serde_json::Map::new();
        extra.insert(
            "filament_ids".to_owned(),
            serde_json::Value::Array(vec![
                json!("PLA Basic"),
                json!("line\\nid"),
                serde_json::Value::String("quote\"id".to_owned()),
            ]),
        );
        serde_json::Value::Object(extra)
    })
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_ids = \"PLA Basic\";\"line\\\\nid\";\"quote\\\"id\"")
    );
}

#[tokio::test]
async fn invalid_filament_ids_values_reach_slice_error() {
    for value in [json!("PLA-ID"), json!([7]), json!([true])] {
        let err = filament_ids_output(json!({
            "filament_ids": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains("filament_ids"));
    }
}

#[tokio::test]
async fn invalid_filament_ids_is_rejected_when_header_is_skipped() {
    let err = filament_ids_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "filament_ids": [7]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("filament_ids"));
}

async fn filament_ids_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
