use super::*;

#[tokio::test]
async fn single_filament_colour_new_reaches_gcode_config_header() {
    let output = filament_colour_new_output(json!({
        "filament_colour_new": [1.0]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_colour_new = 1")
    );
}

#[tokio::test]
async fn multiple_filament_colour_new_values_reach_gcode_config_header() {
    let output = filament_colour_new_output(json!({
        "filament_colour_new": [1.0, 2.5, 0.125]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_colour_new = 1,2.5,0.125")
    );
}

#[tokio::test]
async fn zero_filament_colour_new_reaches_gcode_config_header() {
    let output = filament_colour_new_output(json!({
        "filament_colour_new": [0.0]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_colour_new = 0")
    );
}

#[tokio::test]
async fn absent_filament_colour_new_preserves_header() {
    let output = filament_colour_new_output(json!({})).await.unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; filament_colour_new = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_filament_colour_new_values_reach_slice_error() {
    for value in [
        json!(1.0),
        json!("1"),
        json!([true]),
        json!(["1"]),
        json!([-0.001]),
        json!([{"value": 1.0}]),
        serde_json::Value::Null,
    ] {
        let err = filament_colour_new_output(json!({
            "filament_colour_new": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains("filament_colour_new"));
    }
}

#[tokio::test]
async fn invalid_filament_colour_new_is_rejected_when_header_is_skipped() {
    let err = filament_colour_new_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "filament_colour_new": [-0.001]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("filament_colour_new"));
}

async fn filament_colour_new_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
