use super::*;

#[tokio::test]
async fn single_filament_minimal_purge_reaches_gcode_config_header() {
    let output = filament_minimal_purge_output(json!({
        "filament_minimal_purge_on_wipe_tower": [15.0]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_minimal_purge_on_wipe_tower = 15")
    );
}

#[tokio::test]
async fn multiple_filament_minimal_purge_values_reach_gcode_config_header() {
    let output = filament_minimal_purge_output(json!({
        "filament_minimal_purge_on_wipe_tower": [0.0, 15.0, 22.5]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_minimal_purge_on_wipe_tower = 0,15,22.5")
    );
}

#[tokio::test]
async fn zero_filament_minimal_purge_reaches_gcode_config_header() {
    let output = filament_minimal_purge_output(json!({
        "filament_minimal_purge_on_wipe_tower": [0.0]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_minimal_purge_on_wipe_tower = 0")
    );
}

#[tokio::test]
async fn empty_filament_minimal_purge_vector_reaches_empty_header_value() {
    let output = filament_minimal_purge_output(json!({
        "filament_minimal_purge_on_wipe_tower": []
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_minimal_purge_on_wipe_tower = ")
    );
}

#[tokio::test]
async fn filament_minimal_purge_sits_between_initial_and_final_cooling_speed() {
    let output = filament_minimal_purge_output(json!({
        "filament_cooling_initial_speed": [2.2],
        "filament_minimal_purge_on_wipe_tower": [15.0],
        "filament_cooling_final_speed": [3.4]
    }))
    .await
    .unwrap();
    let lines = output.lines().collect::<Vec<_>>();
    let initial_index = lines
        .iter()
        .position(|line| *line == "; filament_cooling_initial_speed = 2.2")
        .unwrap();

    assert_eq!(
        lines.get(initial_index + 1),
        Some(&"; filament_minimal_purge_on_wipe_tower = 15")
    );
    assert_eq!(
        lines.get(initial_index + 2),
        Some(&"; filament_cooling_final_speed = 3.4")
    );
}

#[tokio::test]
async fn absent_filament_minimal_purge_preserves_header() {
    let output = filament_minimal_purge_output(json!({})).await.unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; filament_minimal_purge_on_wipe_tower = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_filament_minimal_purge_values_reach_slice_error() {
    for value in [
        json!(15.0),
        json!("15"),
        json!(true),
        json!({"value": 15.0}),
        json!([true]),
        json!(["15"]),
        json!([-0.001]),
        json!([{"value": 15.0}]),
        serde_json::Value::Null,
    ] {
        let err = filament_minimal_purge_output(json!({
            "filament_minimal_purge_on_wipe_tower": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(
            err.to_string()
                .contains("filament_minimal_purge_on_wipe_tower")
        );
    }
}

#[tokio::test]
async fn invalid_filament_minimal_purge_is_rejected_when_header_is_skipped() {
    let err = filament_minimal_purge_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "filament_minimal_purge_on_wipe_tower": [-0.001]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(
        err.to_string()
            .contains("filament_minimal_purge_on_wipe_tower")
    );
}

async fn filament_minimal_purge_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
