use super::*;

const FILAMENT_MULTITOOL_RAMMING_KEYS: [&str; 3] = [
    "filament_multitool_ramming",
    "filament_multitool_ramming_volume",
    "filament_multitool_ramming_flow",
];

#[tokio::test]
async fn filament_multitool_ramming_values_reach_gcode_config_header() {
    let output = filament_multitool_ramming_output(json!({
        "filament_multitool_ramming": [true],
        "filament_multitool_ramming_volume": [10.0],
        "filament_multitool_ramming_flow": [12.5]
    }))
    .await
    .unwrap();

    for expected in [
        "; filament_multitool_ramming = 1",
        "; filament_multitool_ramming_volume = 10",
        "; filament_multitool_ramming_flow = 12.5",
    ] {
        assert!(output.lines().any(|line| line == expected), "{expected}");
    }
}

#[tokio::test]
async fn multiple_filament_multitool_ramming_values_reach_gcode_config_header() {
    let output = filament_multitool_ramming_output(json!({
        "filament_multitool_ramming": [true, false],
        "filament_multitool_ramming_volume": [0.0, 10.0, 22.5],
        "filament_multitool_ramming_flow": [0.0, 8.25]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_multitool_ramming = 1,0")
    );
    assert!(
        output
            .lines()
            .any(|line| line == "; filament_multitool_ramming_volume = 0,10,22.5")
    );
    assert!(
        output
            .lines()
            .any(|line| line == "; filament_multitool_ramming_flow = 0,8.25")
    );
}

#[tokio::test]
async fn false_filament_multitool_ramming_reaches_gcode_config_header() {
    let output = filament_multitool_ramming_output(json!({
        "filament_multitool_ramming": [false]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; filament_multitool_ramming = 0")
    );
}

#[tokio::test]
async fn empty_filament_multitool_ramming_vectors_reach_empty_header_values() {
    let output = filament_multitool_ramming_output(json!({
        "filament_multitool_ramming": [],
        "filament_multitool_ramming_volume": [],
        "filament_multitool_ramming_flow": []
    }))
    .await
    .unwrap();

    for expected in [
        "; filament_multitool_ramming = ",
        "; filament_multitool_ramming_volume = ",
        "; filament_multitool_ramming_flow = ",
    ] {
        assert!(output.lines().any(|line| line == expected), "{expected}");
    }
}

#[tokio::test]
async fn filament_multitool_ramming_follows_ramming_parameters_in_header_order() {
    let output = filament_multitool_ramming_output(json!({
        "filament_ramming_parameters": ["120 100"],
        "filament_multitool_ramming": [true],
        "filament_multitool_ramming_volume": [10.0],
        "filament_multitool_ramming_flow": [12.5],
        "filament_colour": ["#123456"]
    }))
    .await
    .unwrap();
    let lines = output.lines().collect::<Vec<_>>();
    let ramming_index = lines
        .iter()
        .position(|line| *line == "; filament_ramming_parameters = \"120 100\"")
        .unwrap();

    assert_eq!(
        lines.get(ramming_index + 1),
        Some(&"; filament_multitool_ramming = 1")
    );
    assert_eq!(
        lines.get(ramming_index + 2),
        Some(&"; filament_multitool_ramming_volume = 10")
    );
    assert_eq!(
        lines.get(ramming_index + 3),
        Some(&"; filament_multitool_ramming_flow = 12.5")
    );
    assert_eq!(
        lines.get(ramming_index + 4),
        Some(&"; filament_colour = #123456")
    );
}

#[tokio::test]
async fn absent_filament_multitool_ramming_values_preserve_header() {
    let output = filament_multitool_ramming_output(json!({})).await.unwrap();

    for key in FILAMENT_MULTITOOL_RAMMING_KEYS {
        assert!(
            !output
                .lines()
                .any(|line| line.starts_with(&format!("; {key} = "))),
            "{key}"
        );
    }
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_filament_multitool_ramming_values_reach_slice_error() {
    for (key, value) in [
        ("filament_multitool_ramming", json!(true)),
        ("filament_multitool_ramming", json!([1])),
        ("filament_multitool_ramming", json!(["true"])),
        ("filament_multitool_ramming", json!([{"value": true}])),
        ("filament_multitool_ramming", serde_json::Value::Null),
        ("filament_multitool_ramming_volume", json!(10.0)),
        ("filament_multitool_ramming_volume", json!("10")),
        ("filament_multitool_ramming_volume", json!([-0.001])),
        ("filament_multitool_ramming_volume", json!([true])),
        ("filament_multitool_ramming_flow", json!({"value": 12.5})),
        ("filament_multitool_ramming_flow", json!(["12.5"])),
        ("filament_multitool_ramming_flow", serde_json::Value::Null),
    ] {
        let err = filament_multitool_ramming_output(json!({
            key: value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains(key));
    }
}

#[tokio::test]
async fn invalid_filament_multitool_ramming_is_rejected_when_header_is_skipped() {
    let err = filament_multitool_ramming_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "filament_multitool_ramming_volume": [-0.001]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(
        err.to_string()
            .contains("filament_multitool_ramming_volume")
    );
}

async fn filament_multitool_ramming_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
