use super::*;

const MMU_SCALAR_CONFIG_KEYS: [&str; 8] = [
    "cooling_tube_retraction",
    "cooling_tube_length",
    "high_current_on_filament_swap",
    "parking_pos_retraction",
    "extra_loading_move",
    "machine_load_filament_time",
    "machine_tool_change_time",
    "machine_unload_filament_time",
];

#[tokio::test]
async fn mmu_scalar_config_values_reach_gcode_config_header() {
    let output = mmu_scalar_config_output(json!({
        "cooling_tube_retraction": 91.5,
        "cooling_tube_length": 5.0,
        "high_current_on_filament_swap": true,
        "parking_pos_retraction": 92.0,
        "extra_loading_move": -2.25,
        "machine_load_filament_time": 1.5,
        "machine_tool_change_time": 2.0,
        "machine_unload_filament_time": 3.25
    }))
    .await
    .unwrap();

    for expected in [
        "; cooling_tube_retraction = 91.5",
        "; cooling_tube_length = 5",
        "; high_current_on_filament_swap = 1",
        "; parking_pos_retraction = 92",
        "; extra_loading_move = -2.25",
        "; machine_load_filament_time = 1.5",
        "; machine_tool_change_time = 2",
        "; machine_unload_filament_time = 3.25",
    ] {
        assert!(output.lines().any(|line| line == expected), "{expected}");
    }
}

#[tokio::test]
async fn zero_and_false_mmu_scalar_config_values_reach_gcode_config_header() {
    let output = mmu_scalar_config_output(json!({
        "cooling_tube_retraction": 0.0,
        "cooling_tube_length": 0.0,
        "high_current_on_filament_swap": false,
        "parking_pos_retraction": 0.0,
        "extra_loading_move": 0.0,
        "machine_load_filament_time": 0.0,
        "machine_tool_change_time": 0.0,
        "machine_unload_filament_time": 0.0
    }))
    .await
    .unwrap();

    for expected in [
        "; cooling_tube_retraction = 0",
        "; cooling_tube_length = 0",
        "; high_current_on_filament_swap = 0",
        "; parking_pos_retraction = 0",
        "; extra_loading_move = 0",
        "; machine_load_filament_time = 0",
        "; machine_tool_change_time = 0",
        "; machine_unload_filament_time = 0",
    ] {
        assert!(output.lines().any(|line| line == expected), "{expected}");
    }
}

#[tokio::test]
async fn mmu_scalar_config_follows_adhesiveness_before_loading_speed_order() {
    let output = mmu_scalar_config_output(json!({
        "filament_adhesiveness_category": [7],
        "cooling_tube_retraction": 91.5,
        "cooling_tube_length": 5.0,
        "high_current_on_filament_swap": true,
        "parking_pos_retraction": 92.0,
        "extra_loading_move": -2.0,
        "machine_load_filament_time": 1.0,
        "machine_tool_change_time": 2.0,
        "machine_unload_filament_time": 3.0,
        "filament_loading_speed": [28.0]
    }))
    .await
    .unwrap();
    let lines = output.lines().collect::<Vec<_>>();
    let adhesiveness_index = lines
        .iter()
        .position(|line| *line == "; filament_adhesiveness_category = 7")
        .unwrap();

    assert_eq!(
        lines.get(adhesiveness_index + 1),
        Some(&"; cooling_tube_retraction = 91.5")
    );
    assert_eq!(
        lines.get(adhesiveness_index + 2),
        Some(&"; cooling_tube_length = 5")
    );
    assert_eq!(
        lines.get(adhesiveness_index + 3),
        Some(&"; high_current_on_filament_swap = 1")
    );
    assert_eq!(
        lines.get(adhesiveness_index + 4),
        Some(&"; parking_pos_retraction = 92")
    );
    assert_eq!(
        lines.get(adhesiveness_index + 5),
        Some(&"; extra_loading_move = -2")
    );
    assert_eq!(
        lines.get(adhesiveness_index + 6),
        Some(&"; machine_load_filament_time = 1")
    );
    assert_eq!(
        lines.get(adhesiveness_index + 7),
        Some(&"; machine_tool_change_time = 2")
    );
    assert_eq!(
        lines.get(adhesiveness_index + 8),
        Some(&"; machine_unload_filament_time = 3")
    );
    assert_eq!(
        lines.get(adhesiveness_index + 9),
        Some(&"; filament_loading_speed = 28")
    );
}

#[tokio::test]
async fn absent_mmu_scalar_config_values_preserve_header() {
    let output = mmu_scalar_config_output(json!({})).await.unwrap();

    for key in MMU_SCALAR_CONFIG_KEYS {
        assert!(
            !output
                .lines()
                .any(|line| line.starts_with(&format!("; {key} = "))),
            "{key}"
        );
    }
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_mmu_scalar_config_values_reach_slice_error() {
    for (key, value) in [
        ("cooling_tube_retraction", json!(-0.001)),
        ("cooling_tube_retraction", json!("91.5")),
        ("cooling_tube_length", json!([5.0])),
        ("high_current_on_filament_swap", json!(1)),
        ("high_current_on_filament_swap", json!("true")),
        ("high_current_on_filament_swap", json!([true])),
        ("parking_pos_retraction", serde_json::Value::Null),
        ("extra_loading_move", json!("2")),
        ("extra_loading_move", json!([2.0])),
        ("machine_load_filament_time", json!(-1.0)),
        ("machine_tool_change_time", json!({"value": 2.0})),
        ("machine_unload_filament_time", json!(false)),
    ] {
        let err = mmu_scalar_config_output(json!({
            key: value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains(key));
    }
}

#[tokio::test]
async fn invalid_mmu_scalar_config_is_rejected_when_header_is_skipped() {
    let err = mmu_scalar_config_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "machine_tool_change_time": -1.0
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("machine_tool_change_time"));
}

async fn mmu_scalar_config_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
