use super::*;

#[tokio::test]
async fn prime_tower_width_reaches_gcode_config_header() {
    let output = prime_tower_width_output(json!({
        "prime_tower_width": 60.0
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; prime_tower_width = 60")
    );
    assert_eq!(
        output
            .lines()
            .filter(|line| line.starts_with("; prime_tower_width = "))
            .count(),
        1
    );
}

#[tokio::test]
async fn prime_tower_width_minimum_and_decimal_values_reach_gcode_config_header() {
    let minimum = prime_tower_width_output(json!({
        "prime_tower_width": 2.0
    }))
    .await
    .unwrap();
    assert!(
        minimum
            .lines()
            .any(|line| line == "; prime_tower_width = 2")
    );

    let decimal = prime_tower_width_output(json!({
        "prime_tower_width": 12.5
    }))
    .await
    .unwrap();
    assert!(
        decimal
            .lines()
            .any(|line| line == "; prime_tower_width = 12.5")
    );
}

#[tokio::test]
async fn prime_tower_width_follows_coordinates_and_precedes_rotation() {
    let output = prime_tower_width_output(json!({
        "support_multi_bed_types": true,
        "wipe_tower_x": [15.0],
        "wipe_tower_y": [220.0],
        "prime_tower_width": 60.0,
        "wipe_tower_rotation_angle": 12.0,
        "wipe_tower_bridging": 10.0
    }))
    .await
    .unwrap();
    let lines = output.lines().collect::<Vec<_>>();
    let support_index = lines
        .iter()
        .position(|line| *line == "; support_multi_bed_types = 1")
        .unwrap();

    assert_eq!(
        lines.get(support_index + 1),
        Some(&"; wipe_tower_x = 15.000")
    );
    assert_eq!(
        lines.get(support_index + 2),
        Some(&"; wipe_tower_y = 220.000")
    );
    assert_eq!(
        lines.get(support_index + 3),
        Some(&"; prime_tower_width = 60")
    );
    assert_eq!(
        lines.get(support_index + 4),
        Some(&"; wipe_tower_rotation_angle = 12")
    );
    assert_eq!(
        lines.get(support_index + 5),
        Some(&"; wipe_tower_bridging = 10")
    );
}

#[tokio::test]
async fn absent_prime_tower_width_preserves_header() {
    let output = prime_tower_width_output(json!({})).await.unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; prime_tower_width = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn legacy_wipe_tower_width_reaches_prime_tower_width_header() {
    let output = prime_tower_width_output(json!({
        "wipe_tower_width": 64.0
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; prime_tower_width = 64")
    );
    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; wipe_tower_width = "))
    );
}

#[tokio::test]
async fn obsolete_wipe_tower_per_color_wipe_remains_ignored() {
    let output = prime_tower_width_output(json!({
        "wipe_tower_per_color_wipe": 12.0
    }))
    .await
    .unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; wipe_tower_per_color_wipe = "))
    );
}

#[tokio::test]
async fn invalid_prime_tower_width_values_reach_slice_error() {
    for value in [
        json!(1.999),
        json!("60"),
        json!([60.0]),
        json!(true),
        json!({"value": 60.0}),
        serde_json::Value::Null,
    ] {
        let err = prime_tower_width_output(json!({
            "prime_tower_width": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains("prime_tower_width"));
    }
}

#[tokio::test]
async fn invalid_prime_tower_width_is_rejected_when_header_is_skipped() {
    let err = prime_tower_width_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "prime_tower_width": 1.999
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("prime_tower_width"));
}

async fn prime_tower_width_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
