use super::*;

#[tokio::test]
async fn by_object_print_sequence_is_rejected_before_gcode_output() {
    for extra in [
        json!({ "print_sequence": "by object" }),
        json!({
            "print_sequence": "by object",
            "extruder_clearance_radius": 40.0
        }),
    ] {
        let err = slice_with_print_sequence(extra).await.unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains("print_sequence"), "{err}");
        assert!(err.to_string().contains("by object"), "{err}");
    }
}

#[tokio::test]
async fn by_object_print_sequence_is_rejected_before_model_loading() {
    let err = slice(
        b"not a model",
        serde_json::from_value(json!({ "print_sequence": "by object" })).unwrap(),
    )
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("print_sequence"), "{err}");
    assert!(err.to_string().contains("by object"), "{err}");
}

#[tokio::test]
async fn by_layer_and_by_default_print_sequence_keep_layer_ordered_output() {
    for sequence in ["by layer", "by default"] {
        let output = slice_with_print_sequence(json!({
            "print_sequence": sequence,
            "extruder_clearance_radius": 40.0
        }))
        .await
        .unwrap();
        let output = String::from_utf8(output).unwrap();

        assert!(output.contains("; generated by Ares"), "{sequence}");
        assert!(
            output.lines().any(|line| line == "; layer_count = 2"),
            "{sequence}"
        );
    }
}

#[tokio::test]
async fn invalid_print_sequence_boundary_values_reach_slice_error() {
    for (key, extra) in [
        ("printer_technology", json!({ "printer_technology": 7 })),
        (
            "extruder_clearance_radius",
            json!({
                "print_sequence": "by layer",
                "extruder_clearance_radius": -1.0
            }),
        ),
        (
            "print_sequence",
            json!({
                "print_sequence": "sequential",
                "extruder_clearance_radius": 40.0
            }),
        ),
    ] {
        let err = slice_with_print_sequence(extra).await.unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)), "{key}");
        assert!(err.to_string().contains(key), "{key}: {err}");
    }
}

#[tokio::test]
async fn unsupported_print_sequence_without_clearance_preserves_min_object_distance_branch() {
    let output = slice_with_print_sequence(json!({ "print_sequence": "sequential" }))
        .await
        .unwrap();
    let output = String::from_utf8(output).unwrap();

    assert!(output.contains("; generated by Ares"));
}

async fn slice_with_print_sequence(extra: serde_json::Value) -> Result<Vec<u8>, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
}
