use super::*;

#[tokio::test]
async fn zero_required_nozzle_hrc_reaches_gcode_config_header() {
    let output = required_nozzle_hrc_output(json!({
        "required_nozzle_HRC": [0]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; required_nozzle_HRC = 0")
    );
}

#[tokio::test]
async fn multiple_required_nozzle_hrc_values_reach_gcode_config_header() {
    let output = required_nozzle_hrc_output(json!({
        "required_nozzle_HRC": [0, 60, 500]
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; required_nozzle_HRC = 0,60,500")
    );
}

#[tokio::test]
async fn absent_required_nozzle_hrc_preserves_header() {
    let output = required_nozzle_hrc_output(json!({})).await.unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; required_nozzle_HRC = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_required_nozzle_hrc_values_reach_slice_error() {
    for value in [
        json!(0),
        json!("0"),
        json!([true]),
        json!(["0"]),
        json!([-1]),
        json!([501]),
        json!([1.5]),
        json!([2147483648_i64]),
        serde_json::Value::Null,
    ] {
        let err = required_nozzle_hrc_output(json!({
            "required_nozzle_HRC": value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains("required_nozzle_HRC"));
    }
}

#[tokio::test]
async fn invalid_required_nozzle_hrc_is_rejected_when_header_is_skipped() {
    let err = required_nozzle_hrc_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "required_nozzle_HRC": [501]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("required_nozzle_HRC"));
}

async fn required_nozzle_hrc_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
