use super::*;

const KEY: &str = "small_area_infill_flow_compensation_model";

#[tokio::test]
async fn small_area_flow_model_reaches_gcode_config_header() {
    let output = small_area_flow_model_output(json!({
        KEY: ["0,0", "\n0.2,0.4444", "\n10,1"]
    }))
    .await
    .unwrap();

    assert!(output.lines().any(|line| {
        line == "; small_area_infill_flow_compensation_model = 0,0;0.2,0.4444;10,1"
    }));
}

#[tokio::test]
async fn small_area_flow_model_string_input_reaches_gcode_config_header() {
    let output = small_area_flow_model_output(json!({
        KEY: "0,0\n0.5,0.5;2,1"
    }))
    .await
    .unwrap();

    assert!(
        output
            .lines()
            .any(|line| line == "; small_area_infill_flow_compensation_model = 0,0;0.5,0.5;2,1")
    );
}

#[tokio::test]
async fn spaced_small_area_flow_model_entries_use_orca_string_serialization() {
    let output = small_area_flow_model_output(serde_json::Value::Object({
        let mut extra = serde_json::Map::new();
        extra.insert(
            KEY.to_owned(),
            serde_json::Value::Array(vec![json!("0,0"), json!("0.5, 0.5"), json!("2, 1")]),
        );
        extra
    }))
    .await
    .unwrap();

    assert!(output.lines().any(|line| {
        line == "; small_area_infill_flow_compensation_model = 0,0;\"0.5, 0.5\";\"2, 1\""
    }));
}

#[tokio::test]
async fn small_area_flow_model_follows_wipe_tower_config_in_header_order() {
    let output = small_area_flow_model_output(json!({
        "support_multi_bed_types": true,
        "wipe_tower_wall_type": "rib",
        "wipe_tower_extra_rib_length": 11.0,
        "wipe_tower_rib_width": 8.0,
        "wipe_tower_fillet_wall": true,
        "wipe_tower_filament": 2,
        KEY: ["0,0", "\n0.2,0.4444", "\n10,1"],
        "filament_colour": ["#123456"]
    }))
    .await
    .unwrap();
    let lines = output.lines().collect::<Vec<_>>();
    let support_multi_bed_index = lines
        .iter()
        .position(|line| *line == "; support_multi_bed_types = 1")
        .unwrap();

    assert_eq!(
        lines.get(support_multi_bed_index + 1),
        Some(&"; wipe_tower_wall_type = rib")
    );
    assert_eq!(
        lines.get(support_multi_bed_index + 2),
        Some(&"; wipe_tower_extra_rib_length = 11")
    );
    assert_eq!(
        lines.get(support_multi_bed_index + 3),
        Some(&"; wipe_tower_rib_width = 8")
    );
    assert_eq!(
        lines.get(support_multi_bed_index + 4),
        Some(&"; wipe_tower_fillet_wall = 1")
    );
    assert_eq!(
        lines.get(support_multi_bed_index + 5),
        Some(&"; wipe_tower_filament = 2")
    );
    assert_eq!(
        lines.get(support_multi_bed_index + 6),
        Some(&"; small_area_infill_flow_compensation_model = 0,0;0.2,0.4444;10,1")
    );
    assert_eq!(
        lines.get(support_multi_bed_index + 7),
        Some(&"; filament_colour = #123456")
    );
}

#[tokio::test]
async fn absent_small_area_flow_model_preserves_header() {
    let output = small_area_flow_model_output(json!({})).await.unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; small_area_infill_flow_compensation_model = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_small_area_flow_model_values_reach_slice_error() {
    for value in [
        json!("0,0"),
        json!("0,0\n0.5,0.5"),
        json!([]),
        json!([""]),
        json!(["0,0"]),
        json!(["length factor", "\n0.2,0.4444"]),
        json!(["0,0", "\n0.5,0.5"]),
        json!(120),
        json!(true),
        json!({"value": "0,0"}),
        json!([120]),
        json!([true]),
        json!([{"value": "0,0"}]),
        serde_json::Value::Null,
    ] {
        let err = small_area_flow_model_output(json!({
            KEY: value
        }))
        .await
        .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains(KEY));
    }
}

#[tokio::test]
async fn invalid_small_area_flow_model_is_rejected_when_header_is_skipped() {
    let err = small_area_flow_model_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        KEY: [""]
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains(KEY));
}

async fn small_area_flow_model_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
