use super::*;

#[tokio::test]
async fn wipe_tower_coordinates_reach_gcode_config_header() {
    let output = wipe_tower_coordinate_output(json!({
        "wipe_tower_x": [12.3456, 99.0],
        "wipe_tower_y": [220.0, 221.0]
    }))
    .await
    .unwrap();

    assert!(output.lines().any(|line| line == "; wipe_tower_x = 12.346"));
    assert!(
        output
            .lines()
            .any(|line| line == "; wipe_tower_y = 220.000")
    );
    assert_eq!(
        output
            .lines()
            .filter(|line| line.starts_with("; wipe_tower_x = "))
            .count(),
        1
    );
    assert_eq!(
        output
            .lines()
            .filter(|line| line.starts_with("; wipe_tower_y = "))
            .count(),
        1
    );
    assert!(
        !output
            .lines()
            .any(|line| line == "; wipe_tower_x = 12.3456,99")
    );
    assert!(
        !output
            .lines()
            .any(|line| line == "; wipe_tower_y = 220,221")
    );
}

#[tokio::test]
async fn zero_and_negative_wipe_tower_coordinates_reach_gcode_config_header() {
    let output = wipe_tower_coordinate_output(json!({
        "wipe_tower_x": [0.0],
        "wipe_tower_y": [-5.5]
    }))
    .await
    .unwrap();

    assert!(output.lines().any(|line| line == "; wipe_tower_x = 0.000"));
    assert!(output.lines().any(|line| line == "; wipe_tower_y = -5.500"));
}

#[tokio::test]
async fn wipe_tower_coordinates_precede_rotation_in_header_order() {
    let output = wipe_tower_coordinate_output(json!({
        "support_multi_bed_types": true,
        "wipe_tower_x": [15.0],
        "wipe_tower_y": [220.0],
        "wipe_tower_rotation_angle": 12.0,
        "wipe_tower_bridging": 10.0,
        "wipe_tower_wall_type": "rib",
        "small_area_infill_flow_compensation_model": ["0,0", "\n0.2,0.4444", "\n10,1"]
    }))
    .await
    .unwrap();
    let lines = output.lines().collect::<Vec<_>>();
    let support_index = lines
        .iter()
        .position(|line| *line == "; support_multi_bed_types = 1")
        .unwrap();

    assert_eq!(
        lines.get(support_index + 1),
        Some(&"; wipe_tower_x = 15.000")
    );
    assert_eq!(
        lines.get(support_index + 2),
        Some(&"; wipe_tower_y = 220.000")
    );
    assert_eq!(
        lines.get(support_index + 3),
        Some(&"; wipe_tower_rotation_angle = 12")
    );
    assert_eq!(
        lines.get(support_index + 4),
        Some(&"; wipe_tower_bridging = 10")
    );
}

#[tokio::test]
async fn absent_wipe_tower_coordinates_preserve_header() {
    let output = wipe_tower_coordinate_output(json!({})).await.unwrap();

    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; wipe_tower_x = "))
    );
    assert!(
        !output
            .lines()
            .any(|line| line.starts_with("; wipe_tower_y = "))
    );
    assert!(output.lines().any(|line| line == "; generated by Ares"));
}

#[tokio::test]
async fn invalid_wipe_tower_coordinate_values_reach_slice_error() {
    for (key, value) in [
        ("wipe_tower_x", json!(15.0)),
        ("wipe_tower_x", json!("15")),
        ("wipe_tower_x", json!([])),
        ("wipe_tower_x", json!([true])),
        ("wipe_tower_x", json!([{"value": 15.0}])),
        ("wipe_tower_x", serde_json::Value::Null),
        ("wipe_tower_y", json!(220.0)),
        ("wipe_tower_y", json!("220")),
        ("wipe_tower_y", json!([])),
        ("wipe_tower_y", json!([true])),
        ("wipe_tower_y", json!([{"value": 220.0}])),
        ("wipe_tower_y", serde_json::Value::Null),
    ] {
        let err = wipe_tower_coordinate_output(json!({ key: value }))
            .await
            .unwrap_err();

        assert!(matches!(err, SliceError::InvalidInput(_)));
        assert!(err.to_string().contains(key));
    }
}

#[tokio::test]
async fn invalid_wipe_tower_coordinate_is_rejected_when_header_is_skipped() {
    let err = wipe_tower_coordinate_output(json!({
        "thumbnails": "7x8/BTT_TFT",
        "wipe_tower_x": []
    }))
    .await
    .unwrap_err();

    assert!(matches!(err, SliceError::InvalidInput(_)));
    assert!(err.to_string().contains("wipe_tower_x"));
}

async fn wipe_tower_coordinate_output(extra: serde_json::Value) -> Result<String, SliceError> {
    let mut options = serde_json::Map::new();
    options.insert("sparse_infill_density".to_owned(), json!(0));
    options.insert("filament_max_volumetric_speed".to_owned(), json!(0.0));
    for (key, value) in extra.as_object().unwrap() {
        options.insert(key.clone(), value.clone());
    }

    slice(
        square_pyramid_ascii_stl(),
        serde_json::from_value(serde_json::Value::Object(options)).unwrap(),
    )
    .await
    .map(|bytes| String::from_utf8(bytes).unwrap())
}
