use crate::{SliceError, options::ProjectSettings};

use super::select::select_stride;

macro_rules! select_wrapped_field {
    ($field:expr, $indices:expr, $key:literal) => {{
        let selected = select_stride(&$field.0, $indices, 1, $key)?;
        $field.0 = selected;
    }};
}

macro_rules! select_vec_field {
    ($field:expr, $indices:expr, $key:literal) => {{
        let selected = select_stride(&$field, $indices, 1, $key)?;
        $field = selected;
    }};
}

pub(super) fn materialize(
    settings: &mut ProjectSettings,
    indices: &[usize],
) -> Result<(), SliceError> {
    select_wrapped_field!(
        settings.filament.print.activate_air_filtration,
        indices,
        "activate_air_filtration"
    );
    select_wrapped_field!(
        settings.filament.print.activate_air_filtration_during_print,
        indices,
        "activate_air_filtration_during_print"
    );
    select_wrapped_field!(
        settings
            .filament
            .print
            .activate_air_filtration_on_completion,
        indices,
        "activate_air_filtration_on_completion"
    );
    select_wrapped_field!(
        settings.filament.print.complete_print_exhaust_fan_speed,
        indices,
        "complete_print_exhaust_fan_speed"
    );
    select_wrapped_field!(
        settings.filament.print.during_print_exhaust_fan_speed,
        indices,
        "during_print_exhaust_fan_speed"
    );
    select_vec_field!(
        settings.filament.gcode.filament_adaptive_volumetric_speed,
        indices,
        "filament_adaptive_volumetric_speed"
    );
    select_vec_field!(
        settings.filament.gcode.filament_cooling_before_tower,
        indices,
        "filament_cooling_before_tower"
    );
    select_vec_field!(
        settings
            .filament
            .retract_overrides
            .filament_deretraction_speed,
        indices,
        "filament_deretraction_speed"
    );
    select_wrapped_field!(
        settings.filament.gcode.filament_extruder_variant,
        indices,
        "filament_extruder_variant"
    );
    select_vec_field!(
        settings.filament.gcode.filament_flow_ratio,
        indices,
        "filament_flow_ratio"
    );
    select_vec_field!(
        settings.filament.gcode.filament_flush_temp,
        indices,
        "filament_flush_temp"
    );
    select_vec_field!(
        settings.filament.gcode.filament_flush_volumetric_speed,
        indices,
        "filament_flush_volumetric_speed"
    );
    select_vec_field!(
        settings.filament.region.filament_ironing_flow,
        indices,
        "filament_ironing_flow"
    );
    select_vec_field!(
        settings.filament.region.filament_ironing_inset,
        indices,
        "filament_ironing_inset"
    );
    select_vec_field!(
        settings.filament.region.filament_ironing_spacing,
        indices,
        "filament_ironing_spacing"
    );
    select_vec_field!(
        settings.filament.region.filament_ironing_speed,
        indices,
        "filament_ironing_speed"
    );
    select_vec_field!(
        settings
            .filament
            .retract_overrides
            .filament_long_retractions_when_cut,
        indices,
        "filament_long_retractions_when_cut"
    );
    select_wrapped_field!(
        settings.filament.gcode.filament_max_volumetric_speed,
        indices,
        "filament_max_volumetric_speed"
    );
    select_vec_field!(
        settings
            .filament
            .retract_overrides
            .filament_retract_before_wipe,
        indices,
        "filament_retract_before_wipe"
    );
    select_vec_field!(
        settings
            .filament
            .retract_overrides
            .filament_retract_lift_above,
        indices,
        "filament_retract_lift_above"
    );
    select_vec_field!(
        settings
            .filament
            .retract_overrides
            .filament_retract_lift_below,
        indices,
        "filament_retract_lift_below"
    );
    select_vec_field!(
        settings
            .filament
            .retract_overrides
            .filament_retract_lift_enforce,
        indices,
        "filament_retract_lift_enforce"
    );
    select_vec_field!(
        settings
            .filament
            .retract_overrides
            .filament_retract_restart_extra,
        indices,
        "filament_retract_restart_extra"
    );
    select_vec_field!(
        settings
            .filament
            .retract_overrides
            .filament_retract_when_changing_layer,
        indices,
        "filament_retract_when_changing_layer"
    );
    select_vec_field!(
        settings
            .filament
            .retract_overrides
            .filament_retraction_distances_when_cut,
        indices,
        "filament_retraction_distances_when_cut"
    );
    select_vec_field!(
        settings
            .filament
            .retract_overrides
            .filament_retraction_length,
        indices,
        "filament_retraction_length"
    );
    select_vec_field!(
        settings
            .filament
            .retract_overrides
            .filament_retraction_minimum_travel,
        indices,
        "filament_retraction_minimum_travel"
    );
    select_vec_field!(
        settings
            .filament
            .retract_overrides
            .filament_retraction_speed,
        indices,
        "filament_retraction_speed"
    );
    select_vec_field!(
        settings.filament.retract_overrides.filament_wipe,
        indices,
        "filament_wipe"
    );
    select_vec_field!(
        settings.filament.retract_overrides.filament_wipe_distance,
        indices,
        "filament_wipe_distance"
    );
    select_vec_field!(
        settings.filament.retract_overrides.filament_z_hop,
        indices,
        "filament_z_hop"
    );
    select_vec_field!(
        settings.filament.retract_overrides.filament_z_hop_types,
        indices,
        "filament_z_hop_types"
    );
    select_vec_field!(
        settings.filament.gcode.long_retractions_when_ec,
        indices,
        "long_retractions_when_ec"
    );
    select_wrapped_field!(
        settings.filament.print.nozzle_temperature,
        indices,
        "nozzle_temperature"
    );
    select_wrapped_field!(
        settings.filament.print.nozzle_temperature_initial_layer,
        indices,
        "nozzle_temperature_initial_layer"
    );
    select_vec_field!(
        settings.filament.gcode.retraction_distances_when_ec,
        indices,
        "retraction_distances_when_ec"
    );
    select_wrapped_field!(
        settings.filament.gcode.volumetric_speed_coefficients,
        indices,
        "volumetric_speed_coefficients"
    );
    Ok(())
}
