mod helpers;

use crate::{
    FloatOrPercent, RawOverhangFanThreshold, RetractLiftEnforce, options::InternalBridgeFanSpeed,
};

pub(in crate::project_slice::gcode_emit) use helpers::first_nullable_float;

mod build;

#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub(in crate::project_slice::gcode_emit) struct MotionOptions {
    pub(in crate::project_slice::gcode_emit) filament_area: f64,
    pub(in crate::project_slice::gcode_emit) filament_flow_ratio: f64,
    pub(in crate::project_slice::gcode_emit) print_flow_ratio: f64,
    pub(in crate::project_slice::gcode_emit) max_volumetric_speed: f64,
    pub(in crate::project_slice::gcode_emit) travel_feedrate: f64,
    pub(in crate::project_slice::gcode_emit) first_layer_travel_feedrate: f64,
    pub(in crate::project_slice::gcode_emit) initial_layer_speed: f64,
    pub(in crate::project_slice::gcode_emit) initial_layer_infill_speed: f64,
    pub(in crate::project_slice::gcode_emit) inner_wall_speed: f64,
    pub(in crate::project_slice::gcode_emit) outer_wall_speed: f64,
    pub(in crate::project_slice::gcode_emit) small_perimeter_speed: f64,
    pub(in crate::project_slice::gcode_emit) small_perimeter_threshold: f64,
    pub(in crate::project_slice::gcode_emit) bridge_speed: f64,
    pub(in crate::project_slice::gcode_emit) internal_bridge_speed: f64,
    pub(in crate::project_slice::gcode_emit) sparse_infill_speed: f64,
    pub(in crate::project_slice::gcode_emit) skirt_speed: f64,
    pub(in crate::project_slice::gcode_emit) internal_solid_infill_speed: f64,
    pub(in crate::project_slice::gcode_emit) top_surface_speed: f64,
    pub(in crate::project_slice::gcode_emit) gap_infill_speed: f64,
    pub(in crate::project_slice::gcode_emit) support_speed: f64,
    pub(in crate::project_slice::gcode_emit) enable_overhang_speed: bool,
    pub(in crate::project_slice::gcode_emit) slowdown_for_curled_perimeters: bool,
    pub(in crate::project_slice::gcode_emit) overhang_speed_bands: [Option<FloatOrPercent>; 4],
    pub(in crate::project_slice::gcode_emit) enable_overhang_bridge_fan: bool,
    pub(in crate::project_slice::gcode_emit) overhang_fan_speed: u8,
    pub(in crate::project_slice::gcode_emit) overhang_fan_threshold: RawOverhangFanThreshold,
    pub(in crate::project_slice::gcode_emit) internal_bridge_fan_speed: InternalBridgeFanSpeed,
    pub(in crate::project_slice::gcode_emit) close_fan_first_layers: usize,
    pub(in crate::project_slice::gcode_emit) full_fan_speed_layer: usize,
    pub(in crate::project_slice::gcode_emit) initial_layer_acceleration: u32,
    pub(in crate::project_slice::gcode_emit) default_acceleration: u32,
    pub(in crate::project_slice::gcode_emit) outer_wall_acceleration: u32,
    pub(in crate::project_slice::gcode_emit) inner_wall_acceleration: u32,
    pub(in crate::project_slice::gcode_emit) bridge_acceleration: u32,
    pub(in crate::project_slice::gcode_emit) sparse_infill_acceleration: u32,
    pub(in crate::project_slice::gcode_emit) internal_solid_infill_acceleration: u32,
    pub(in crate::project_slice::gcode_emit) top_surface_acceleration: u32,
    pub(in crate::project_slice::gcode_emit) initial_layer_travel_acceleration: u32,
    pub(in crate::project_slice::gcode_emit) travel_acceleration: u32,
    pub(in crate::project_slice::gcode_emit) default_jerk: f64,
    pub(in crate::project_slice::gcode_emit) outer_wall_jerk: f64,
    pub(in crate::project_slice::gcode_emit) inner_wall_jerk: f64,
    pub(in crate::project_slice::gcode_emit) top_surface_jerk: f64,
    pub(in crate::project_slice::gcode_emit) infill_jerk: f64,
    pub(in crate::project_slice::gcode_emit) initial_layer_jerk: f64,
    pub(in crate::project_slice::gcode_emit) travel_jerk: f64,
    pub(in crate::project_slice::gcode_emit) max_jerk_x: f64,
    pub(in crate::project_slice::gcode_emit) max_jerk_y: f64,
    pub(in crate::project_slice::gcode_emit) max_jerk_z: f64,
    pub(in crate::project_slice::gcode_emit) max_jerk_e: f64,
    pub(in crate::project_slice::gcode_emit) gcode_flavor: crate::GCodeFlavor,
    pub(in crate::project_slice::gcode_emit) use_relative_e_distances: bool,
    pub(in crate::project_slice::gcode_emit) max_acceleration: u32,
    pub(in crate::project_slice::gcode_emit) max_travel_acceleration: u32,
    pub(in crate::project_slice::gcode_emit) accel_to_decel_enable: bool,
    pub(in crate::project_slice::gcode_emit) accel_to_decel_factor: f64,
    pub(in crate::project_slice::gcode_emit) retraction_length: f64,
    pub(in crate::project_slice::gcode_emit) deretraction_feedrate: f64,
    pub(in crate::project_slice::gcode_emit) z_hop: f64,
    pub(in crate::project_slice::gcode_emit) retract_lift_above: f64,
    pub(in crate::project_slice::gcode_emit) retract_lift_below: f64,
    pub(in crate::project_slice::gcode_emit) retract_lift_enforce: RetractLiftEnforce,
    pub(in crate::project_slice::gcode_emit) retraction_feedrate: f64,
    pub(in crate::project_slice::gcode_emit) wipe: bool,
    pub(in crate::project_slice::gcode_emit) wipe_distance: f64,
    pub(in crate::project_slice::gcode_emit) retraction_minimum_travel: f64,
    pub(in crate::project_slice::gcode_emit) reduce_infill_retraction: bool,
    pub(in crate::project_slice::gcode_emit) retract_before_wipe: f64,
    pub(in crate::project_slice::gcode_emit) role_based_wipe_speed: bool,
    pub(in crate::project_slice::gcode_emit) wipe_speed: f64,
    pub(in crate::project_slice::gcode_emit) wipe_on_loops: bool,
    pub(in crate::project_slice::gcode_emit) wall_loops: i32,
    pub(in crate::project_slice::gcode_emit) nozzle_diameter: f64,
    pub(in crate::project_slice::gcode_emit) retract_when_changing_layer: bool,
    pub(in crate::project_slice::gcode_emit) z_hop_type: crate::ZHopType,
    pub(in crate::project_slice::gcode_emit) travel_slope_radians: f64,
    pub(in crate::project_slice::gcode_emit) enable_arc_fitting: bool,
    pub(in crate::project_slice::gcode_emit) arc_fitting_tolerance: f64,
    pub(in crate::project_slice::gcode_emit) seam_gap: f64,
}
