use serde_json::{Map, Value, json};

pub(super) fn insert_known_sla_display_tilt_values(values: &mut Map<String, Value>) {
    for (key, value) in [
        ("absolute_correction", json!(0)),
        ("area_fill", json!(50)),
        ("bottle_cost", json!(0)),
        ("bottle_volume", json!(1000)),
        ("bottle_weight", json!(1)),
        ("display_height", json!(68)),
        ("display_mirror_x", json!(true)),
        ("display_mirror_y", json!(false)),
        ("display_orientation", json!("portrait")),
        ("display_pixels_x", json!(2560)),
        ("display_pixels_y", json!(1440)),
        ("display_width", json!(120)),
        ("default_sla_material_profile", json!("")),
        ("default_sla_print_profile", json!("")),
        ("elefant_foot_min_width", json!(0.2)),
        ("exposure_time", json!(10)),
        ("faded_layers", json!(10)),
        ("fast_tilt_time", json!(5)),
        ("gamma_correction", json!(1)),
        ("initial_exposure_time", json!(15)),
        ("material_colour", json!("#29B2B2")),
        ("material_correction", json!([1, 1, 1])),
        ("material_correction_x", json!(1)),
        ("material_correction_y", json!(1)),
        ("material_correction_z", json!(1)),
        ("material_density", json!(1)),
        ("material_print_speed", json!("fast")),
        ("material_type", json!("Tough")),
        ("material_vendor", json!("")),
        ("max_exposure_time", json!(100)),
        ("max_initial_exposure_time", json!(150)),
        ("min_exposure_time", json!(0)),
        ("min_initial_exposure_time", json!(0)),
        ("pad_around_object", json!(false)),
        ("pad_around_object_everywhere", json!(false)),
        ("pad_brim_size", json!(1.6)),
        ("pad_enable", json!(true)),
        ("pad_max_merge_distance", json!(50)),
        ("pad_object_connector_penetration", json!(0.3)),
        ("pad_object_connector_stride", json!(10)),
        ("pad_object_connector_width", json!(0.5)),
        ("pad_object_gap", json!(1)),
        ("pad_wall_height", json!(0)),
        ("pad_wall_slope", json!(90)),
        ("pad_wall_thickness", json!(2)),
        ("relative_correction", json!([1, 1])),
        ("relative_correction_x", json!(1)),
        ("relative_correction_y", json!(1)),
        ("relative_correction_z", json!(1)),
        ("slow_tilt_time", json!(8)),
        ("support_base_diameter", json!(4)),
        ("support_base_height", json!(1)),
        ("support_base_safety_distance", json!(1)),
        ("support_buildplate_only", json!(false)),
        ("support_critical_angle", json!(45)),
        ("support_head_front_diameter", json!(0.4)),
        ("support_head_penetration", json!(0.2)),
        ("support_head_width", json!(1)),
        ("support_max_bridge_length", json!(15)),
        ("support_max_bridges_on_pillar", json!(3)),
        ("support_max_pillar_link_distance", json!(10)),
        ("support_object_elevation", json!(5)),
        ("support_pillar_connection_mode", json!("dynamic")),
        ("support_pillar_diameter", json!(1)),
        ("support_pillar_widening_factor", json!(0)),
        ("support_points_density_relative", json!(100)),
        ("support_points_minimal_distance", json!(1)),
        ("support_small_pillar_diameter_percent", json!(50)),
        ("supports_enable", json!(true)),
        ("sla_material_settings_id", json!("")),
        ("sla_print_settings_id", json!("")),
        ("start_end_points", json!("30x-3,54x245")),
        ("template_custom_gcode", json!("")),
        ("time_lapse_gcode", json!("")),
        ("wrapping_detection_gcode", json!("")),
    ] {
        values.insert(key.to_owned(), value);
    }
}
