use serde_json::{Map, Value, json};

pub(super) fn insert_known_tail_values(values: &mut Map<String, Value>) {
    for (key, value) in [
        ("activate_chamber_temp_control", json!([false])),
        ("change_extrusion_role_gcode", json!("")),
        ("change_filament_gcode", json!("")),
        ("chamber_temperature", json!([0])),
        ("draft_shield", json!("disabled")),
        ("enable_prime_tower", json!(false)),
        ("file_start_gcode", json!("")),
        ("filament_start_gcode", json!([" "])),
        ("filament_change_extrusion_role_gcode", json!([""])),
        ("flush_into_infill", json!(false)),
        ("flush_into_objects", json!(false)),
        ("flush_into_support", json!(true)),
        ("flush_multiplier", json!([0.3])),
        (
            "flush_volumes_matrix",
            json!([
                0, 280, 280, 280, 280, 0, 280, 280, 280, 280, 0, 280, 280, 280, 280, 0
            ]),
        ),
        (
            "flush_volumes_vector",
            json!([140, 140, 140, 140, 140, 140, 140, 140]),
        ),
        ("internal_solid_infill_line_width", json!(0)),
        ("internal_solid_infill_speed", json!(100)),
        ("idle_temperature", json!([0])),
        ("independent_support_layer_height", json!(true)),
        ("min_skirt_length", json!(0)),
        ("minimum_sparse_infill_area", json!(15)),
        ("preheat_steps", json!(1)),
        ("preheat_time", json!(30)),
        ("prime_tower_brim_width", json!(3)),
        ("prime_tower_enable_framework", json!(false)),
        ("prime_volume", json!(45)),
        ("prime_tower_width", json!(60)),
        ("single_loop_draft_shield", json!(false)),
        ("slice_closing_radius", json!(0.049)),
        ("slicing_mode", json!("regular")),
        ("skirt_distance", json!(2)),
        ("skirt_height", json!(1)),
        ("skirt_loops", json!(1)),
        ("skirt_speed", json!(50)),
        ("skirt_start_angle", json!(-135)),
        ("skirt_type", json!("combined")),
        ("slow_down_layer_time", json!([5])),
        ("solid_infill_filament", json!(1)),
        ("spiral_finishing_flow_ratio", json!(0)),
        ("spiral_mode", json!(false)),
        ("spiral_mode_max_xy_smoothing", json!("200%")),
        ("spiral_mode_smooth", json!(false)),
        ("spiral_starting_flow_ratio", json!(0)),
        ("standby_temperature_delta", json!(-5)),
        ("support_air_filtration", json!(true)),
        ("support_angle", json!(0)),
        ("support_base_pattern", json!("default")),
        ("support_base_pattern_spacing", json!(2.5)),
        ("support_bottom_interface_spacing", json!(0.5)),
        ("support_bottom_z_distance", json!(0.2)),
        ("support_chamber_temp_control", json!(true)),
        ("support_critical_regions_only", json!(false)),
        ("support_expansion", json!(0)),
        ("support_filament", json!(0)),
        ("support_flow_ratio", json!(1)),
        ("support_interface_bottom_layers", json!(0)),
        ("support_interface_filament", json!(0)),
        ("support_interface_flow_ratio", json!(1)),
        ("support_interface_loop_pattern", json!(false)),
        ("support_interface_not_for_body", json!(true)),
        ("support_interface_pattern", json!("auto")),
        ("support_interface_spacing", json!(0.5)),
        ("support_interface_speed", json!(80)),
        ("support_interface_top_layers", json!(3)),
        ("support_speed", json!(80)),
        ("support_style", json!("default")),
        ("support_ironing", json!(false)),
        ("support_ironing_flow", json!(10)),
        ("support_ironing_pattern", json!("rectilinear")),
        ("support_ironing_spacing", json!(0.1)),
        ("support_line_width", json!(0)),
        ("support_material_interface_fan_speed", json!([-1])),
        ("support_multi_bed_types", json!(false)),
        ("support_object_first_layer_gap", json!(0.2)),
        ("support_object_xy_distance", json!(0.35)),
        ("support_on_build_plate_only", json!(false)),
        ("support_remove_small_overhang", json!(true)),
        ("support_threshold_angle", json!(30)),
        ("support_threshold_overlap", json!("50%")),
        ("support_top_z_distance", json!(0.2)),
        ("support_type", json!("normal(auto)")),
        ("thick_internal_bridges", json!(true)),
        ("thumbnails", json!("48x48/PNG,300x300/PNG")),
        ("thumbnails_format", json!("PNG")),
        ("timelapse_type", json!("0")),
        ("time_cost", json!(0)),
        ("tool_change_on_wipe_tower", json!(false)),
        ("top_bottom_infill_wall_overlap", json!(25)),
        ("bottom_surface_density", json!(100)),
        ("top_shell_layers", json!(4)),
        ("top_shell_thickness", json!(0.6)),
        ("top_surface_line_width", json!(0)),
        ("top_surface_density", json!(100)),
        ("top_surface_speed", json!(100)),
        ("travel_slope", json!([3])),
        ("travel_speed_z", json!(0)),
        ("tree_support_angle_slow", json!(25)),
        ("tree_support_auto_brim", json!(true)),
        ("tree_support_branch_angle", json!(40)),
        ("tree_support_branch_angle_organic", json!(40)),
        ("tree_support_branch_diameter", json!(5)),
        ("tree_support_branch_diameter_angle", json!(5)),
        ("tree_support_branch_diameter_organic", json!(2)),
        ("tree_support_branch_distance", json!(5)),
        ("tree_support_branch_distance_organic", json!(1)),
        ("tree_support_brim_width", json!(3)),
        ("tree_support_tip_diameter", json!(0.8)),
        ("tree_support_top_rate", json!(30)),
        ("tree_support_wall_count", json!(0)),
        ("tree_support_with_infill", json!(false)),
        ("use_relative_e_distances", json!(true)),
        ("wall_direction", json!("ccw")),
        ("wall_distribution_count", json!(1)),
        ("wall_filament", json!(1)),
        ("wall_generator", json!("arachne")),
        ("wall_loops", json!(2)),
        ("wall_maximum_deviation", json!(0.025)),
        ("wall_maximum_resolution", json!(0.5)),
        ("wall_sequence", json!("inner wall/outer wall")),
        ("wall_transition_angle", json!(10)),
        ("wall_transition_filter_deviation", json!(25)),
        ("wall_transition_length", json!(100)),
        ("wipe", json!([false])),
        ("wipe_distance", json!([1])),
        ("wipe_tower_bridging", json!(10)),
        ("wipe_tower_no_sparse_layers", json!(false)),
        ("wipe_tower_cone_angle", json!(30)),
        ("wipe_tower_extra_flow", json!(100)),
        ("wipe_tower_extra_rib_length", json!(0)),
        ("wipe_tower_extra_spacing", json!(100)),
        ("wipe_tower_filament", json!(0)),
        ("wipe_tower_fillet_wall", json!(true)),
        ("wipe_tower_max_purge_speed", json!(90)),
        ("wipe_tower_rib_width", json!(8)),
        ("wipe_tower_rotation_angle", json!(0)),
        ("wipe_tower_type", json!("type2")),
        ("wipe_tower_wall_type", json!("rib")),
        ("wipe_tower_x", json!([15])),
        ("wipe_tower_y", json!([220])),
        ("nozzle_flush_dataset", json!([0])),
        ("nozzle_hrc", json!(0)),
        ("nozzle_type", json!(["undefine"])),
        ("nozzle_volume", json!([0.0])),
        ("nozzle_height", json!(2.5)),
        ("nozzle_temperature", json!([200])),
        ("nozzle_temperature_initial_layer", json!([200])),
        ("nozzle_temperature_range_high", json!([240])),
        ("nozzle_temperature_range_low", json!([190])),
        ("support_object_skip_flush", json!(false)),
        ("symmetric_infill_y_axis", json!(false)),
        ("temperature_vitrification", json!([100])),
        ("wrapping_detection_layers", json!(20)),
        ("wrapping_exclude_area", json!("0x0")),
        ("xy_contour_compensation", json!(0)),
        ("xy_hole_compensation", json!(0)),
        ("z_offset", json!(0)),
        ("z_hop", json!([0.4])),
        ("z_hop_types", json!(["Slope Lift"])),
        ("zaa_dont_alternate_fill_direction", json!(false)),
        ("zaa_enabled", json!(false)),
        ("zaa_min_z", json!(0.05)),
        ("zaa_minimize_perimeter_height", json!(35)),
        ("emit_machine_limits_to_gcode", json!(true)),
        ("enable_support", json!(false)),
        ("enable_tower_interface_cooldown_during_tower", json!(false)),
        ("enable_tower_interface_features", json!(false)),
        ("detect_thin_wall", json!(false)),
        ("enforce_support_layers", json!(0)),
        ("has_scarf_joint_seam", json!(false)),
        ("head_wrap_detect_zone", json!("0x0")),
        ("high_current_on_filament_swap", json!(false)),
        ("hole_to_polyhole", json!(false)),
        ("hole_to_polyhole_threshold", json!(0.01)),
        ("hole_to_polyhole_twisted", json!(true)),
        ("hollowing_closing_distance", json!(2)),
        ("hollowing_enable", json!(false)),
        ("hollowing_min_thickness", json!(3)),
        ("hollowing_quality", json!(0.5)),
        ("host_type", json!("octoprint")),
        ("layer_change_gcode", json!("")),
        (
            "machine_start_gcode",
            json!("G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n"),
        ),
        ("machine_pause_gcode", json!("")),
        ("manual_filament_change", json!(false)),
        ("prime_tower_flat_ironing", json!(false)),
        ("prime_tower_infill_gap", json!(150)),
        ("prime_tower_skip_points", json!(true)),
        ("purge_in_prime_tower", json!(true)),
        ("silent_mode", json!(false)),
        ("single_extruder_multi_material", json!(true)),
        ("single_extruder_multi_material_priming", json!(false)),
        (
            "wiping_volumes_extruders",
            json!([70, 70, 70, 70, 70, 70, 70, 70, 70, 70]),
        ),
        ("small_area_infill_flow_compensation", json!(false)),
        (
            "small_area_infill_flow_compensation_model",
            json!([
                "0,0",
                "
0.2,0.4444",
                "
0.4,0.6145",
                "
0.6,0.7059",
                "
0.8,0.7619",
                "
1.5,0.8571",
                "
2,0.8889",
                "
3,0.9231",
                "
5,0.9520",
                "
10,1"
            ]),
        ),
    ] {
        values.insert(key.to_owned(), value);
    }
}
