use super::{OptionDefinition, OptionValueKind};

pub(super) const EARLY_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!(
        "absolute_correction",
        Float,
        "0",
        "PrintConfig.hpp:1841; PrintConfig.cpp:7344-7349",
    ),
    definition!(
        "accel_to_decel_enable",
        Bool,
        "true",
        "PrintConfig.hpp:1419; PrintConfig.cpp:3152-3157",
    ),
    definition!(
        "accel_to_decel_factor",
        Percent,
        "50",
        "PrintConfig.hpp:1420; PrintConfig.cpp:3159-3167",
    ),
    definition!(
        "activate_air_filtration",
        Bools,
        "false",
        "PrintConfig.cpp:1800-1804",
    ),
    definition!(
        "activate_air_filtration_during_print",
        Bools,
        "true",
        "PrintConfig.cpp:1807-1811",
    ),
    definition!(
        "activate_air_filtration_on_completion",
        Bools,
        "true",
        "PrintConfig.cpp:1813-1817",
    ),
    definition!(
        "activate_chamber_temp_control",
        Bools,
        "false",
        "PrintConfig.hpp:1636; PrintConfig.cpp:6448-6455",
    ),
    definition!(
        "adaptive_bed_mesh_margin",
        Float,
        "0",
        "PrintConfig.hpp:1644; PrintConfig.cpp:2195-2200",
    ),
    definition!(
        "adaptive_pressure_advance",
        Bools,
        "false",
        "PrintConfig.hpp:1305; PrintConfig.cpp:2264-2278",
    ),
    definition!(
        "adaptive_pressure_advance_bridges",
        Floats,
        "0",
        "PrintConfig.hpp:1308; PrintConfig.cpp:2313-2320",
    ),
    definition!(
        "adaptive_pressure_advance_model",
        Strings,
        "0,0,0\n0,0,0",
        "PrintConfig.hpp:1307; PrintConfig.cpp:2280-2303",
    ),
    definition!(
        "adaptive_pressure_advance_overhangs",
        Bools,
        "false",
        "PrintConfig.hpp:1306; PrintConfig.cpp:2305-2311",
    ),
    definition!(
        "additional_cooling_fan_speed",
        Ints,
        "0",
        "PrintConfig.hpp:1475; PrintConfig.cpp:4660-4668",
    ),
    definition!(
        "additional_fan_full_speed_layer",
        Ints,
        "0",
        "PrintConfig.hpp:1477; PrintConfig.cpp:4679-4686",
    ),
    definition!(
        "align_infill_direction_to_model",
        Bool,
        "false",
        "PrintConfig.hpp:1106; PrintConfig.cpp:2891-2896",
    ),
    definition!(
        "alternate_extra_wall",
        Bool,
        "false",
        "PrintConfig.hpp:1159; PrintConfig.cpp:4926-4933",
    ),
    definition!(
        "area_fill",
        Float,
        "50",
        "PrintConfig.hpp:1847; PrintConfig.cpp:7304-7310",
    ),
    definition!(
        "auxiliary_fan",
        Bool,
        "false",
        "PrintConfig.hpp:1404; PrintConfig.cpp:3704-3708",
    ),
    definition!(
        "bbl_calib_mark_logo",
        Bool,
        "true",
        "PrintConfig.hpp:1424; PrintConfig.cpp:5345-5349",
    ),
    definition!(
        "bbl_use_printhost",
        Bool,
        "false",
        "PrintConfig.cpp:792-797",
    ),
    definition!("bed_custom_model", String, "", "PrintConfig.cpp:711-715",),
    definition!("bed_custom_texture", String, "", "PrintConfig.cpp:705-709",),
    definition!("bed_exclude_area", Points, "0x0", "PrintConfig.cpp:696-703",),
    definition!(
        "bed_mesh_max",
        Point,
        "99999x99999",
        "PrintConfig.hpp:1642; PrintConfig.cpp:2174-2184",
    ),
    definition!(
        "bed_mesh_min",
        Point,
        "-99999x-99999",
        "PrintConfig.hpp:1641; PrintConfig.cpp:2162-2172",
    ),
    definition!(
        "bed_mesh_probe_distance",
        Point,
        "50x50",
        "PrintConfig.hpp:1643; PrintConfig.cpp:2186-2193",
    ),
    definition!(
        "bed_temperature_formula",
        Enum,
        "by_highest_temp",
        "PrintConfig.hpp:1340; PrintConfig.cpp:2503-2512",
    ),
    definition!(
        "before_layer_change_gcode",
        String,
        "",
        "PrintConfig.hpp:1294; PrintConfig.cpp:1110-1117",
    ),
    definition!(
        "best_object_pos",
        Point,
        "0.5x0.5",
        "PrintConfig.hpp:1541; PrintConfig.cpp:3698-3702",
    ),
    definition!(
        "bottle_cost",
        Float,
        "0",
        "PrintConfig.hpp:1811; PrintConfig.cpp:7418-7423",
    ),
    definition!(
        "bottle_volume",
        Float,
        "1000",
        "PrintConfig.hpp:1812; PrintConfig.cpp:7397-7402",
    ),
    definition!(
        "bottle_weight",
        Float,
        "1",
        "PrintConfig.hpp:1813; PrintConfig.cpp:7404-7409",
    ),
    definition!(
        "bottom_shell_layers",
        Int,
        "3",
        "PrintConfig.hpp:1079; PrintConfig.cpp:1119-1128",
    ),
    definition!(
        "bottom_shell_thickness",
        Float,
        "0",
        "PrintConfig.hpp:1080; PrintConfig.cpp:1130-1139",
    ),
    definition!(
        "bottom_solid_infill_flow_ratio",
        Float,
        "1",
        "PrintConfig.hpp:1194; PrintConfig.cpp:1297-1305",
    ),
    definition!(
        "bottom_surface_density",
        Percent,
        "100",
        "PrintConfig.hpp:1089; PrintConfig.cpp:6598-6607",
    ),
    definition!(
        "bottom_surface_pattern",
        Enum,
        "monotonic",
        "PrintConfig.hpp:87-98; PrintConfig.hpp:1091; PrintConfig.cpp:225-255; PrintConfig.cpp:2009-2016",
    ),
    definition!(
        "bridge_acceleration",
        FloatOrPercent,
        "50%",
        "PrintConfig.hpp:1047; PrintConfig.cpp:3104-3112",
    ),
    definition!(
        "bridge_angle",
        Float,
        "0",
        "PrintConfig.hpp:1081; PrintConfig.cpp:1213-1223",
    ),
    definition!(
        "bridge_density",
        Percent,
        "100",
        "PrintConfig.hpp:1189; PrintConfig.cpp:1237-1250",
    ),
    definition!("bridge_flow", Float, "1", "PrintConfig.cpp:1266-1274",),
    definition!(
        "bridge_no_support",
        Bool,
        "false",
        "PrintConfig.hpp:928; PrintConfig.cpp:1847-1853",
    ),
    definition!("bridge_speed", Float, "25", "PrintConfig.cpp:1572-1582",),
    definition!("brim_ears", Bool, "false", "PrintConfig.cpp:1665-1670",),
    definition!(
        "brim_ears_detection_length",
        Float,
        "1",
        "PrintConfig.hpp:925; PrintConfig.cpp:1684-1693",
    ),
    definition!(
        "brim_ears_max_angle",
        Float,
        "125",
        "PrintConfig.hpp:926; PrintConfig.cpp:1672-1682",
    ),
    definition!(
        "brim_flow_ratio",
        Float,
        "1",
        "PrintConfig.hpp:921; PrintConfig.cpp:1637-1646",
    ),
    definition!("brim_object_gap", Float, "0", "PrintConfig.cpp:1627-1635",),
    definition!("brim_type", Enum, "auto_brim", "PrintConfig.cpp:1604-1625",),
    definition!(
        "brim_use_efc_outline",
        Bool,
        "false",
        "PrintConfig.hpp:922; PrintConfig.cpp:1648-1656",
    ),
    definition!("brim_width", Float, "0", "PrintConfig.cpp:1594-1602",),
    definition!(
        "calib_flowrate_topinfill_special_order",
        Bool,
        "false",
        "PrintConfig.hpp:1070; PrintConfig.cpp:4156-4159",
    ),
    definition!(
        "chamber_temperature",
        Ints,
        "0",
        "PrintConfig.hpp:1637; PrintConfig.cpp:6457-6476",
    ),
    definition!(
        "change_extrusion_role_gcode",
        String,
        "",
        "PrintConfig.hpp:1393; PrintConfig.cpp:6525-6532",
    ),
    definition!(
        "change_filament_gcode",
        String,
        "",
        "PrintConfig.hpp:1392; PrintConfig.cpp:6516-6523",
    ),
    definition!(
        "close_additional_fan_first_x_layers",
        Ints,
        "1",
        "PrintConfig.hpp:1476; PrintConfig.cpp:4670-4677",
    ),
    definition!(
        "close_fan_the_first_x_layers",
        Ints,
        "1",
        "PrintConfig.cpp:1837-1845",
    ),
    definition!(
        "combine_brims",
        Bool,
        "false",
        "PrintConfig.hpp:1619; PrintConfig.cpp:1658-1663",
    ),
    definition!(
        "compatible_machine_expression_group",
        Strings,
        "",
        "PrintConfig.cpp:1734-1736",
    ),
    definition!(
        "compatible_printers",
        Strings,
        "",
        "PrintConfig.cpp:1695-1699",
    ),
    definition!(
        "compatible_printers_condition",
        String,
        "",
        "PrintConfig.cpp:1708-1715",
    ),
    definition!(
        "compatible_prints",
        Strings,
        "",
        "PrintConfig.cpp:1717-1721",
    ),
    definition!(
        "compatible_prints_condition",
        String,
        "",
        "PrintConfig.cpp:1723-1730",
    ),
    definition!(
        "compatible_process_expression_group",
        Strings,
        "",
        "PrintConfig.cpp:1737-1739",
    ),
];
