use super::{OptionDefinition, OptionValueKind};

pub(super) const LATE_TAIL_FINAL_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!("post_process", Strings, "",),
    definition!("precise_outer_wall", Bool, "true",),
    definition!("precise_z_height", Bool, "false",),
    definition!("preferred_orientation", Float, "0",),
    definition!("preheat_steps", Int, "1",),
    definition!("preheat_time", Float, "30",),
    definition!("preset_name", String, ""),
    definition!("preset_names", Strings, "",),
    definition!("pressure_advance", Floats, "0.02",),
    definition!("prime_tower_brim_width", Float, "3",),
    definition!("prime_tower_enable_framework", Bool, "false",),
    definition!("prime_tower_flat_ironing", Bool, "false",),
    definition!("prime_tower_infill_gap", Percent, "150",),
    definition!("prime_tower_skip_points", Bool, "true",),
    definition!("prime_tower_width", Float, "60",),
    definition!("prime_volume", Float, "45",),
    definition!("print_compatible_printers", Strings, "",),
    definition!("print_extruder_id", Ints, "1",),
    definition!("print_extruder_variant", Strings, "Direct Drive Standard",),
    definition!("print_flow_ratio", Float, "1"),
    definition!("print_host", String, ""),
    definition!("print_host_webui", String, ""),
    definition!("print_order", Enum, "default",),
    definition!("print_sequence", Enum, "by layer",),
    definition!("print_settings_id", String, ""),
    definition!("printable_area", Points, "0x0,200x0,200x200,0x200",),
    definition!("printable_height", Float, "100"),
    definition!("printer_agent", String, ""),
    definition!("printer_extruder_id", Ints, "1",),
    definition!("printer_extruder_variant", Strings, "Direct Drive Standard",),
    definition!("printer_model", String, "",),
    definition!("printer_notes", String, "",),
    definition!("printer_settings_id", String, "",),
    definition!("printer_structure", Enum, "undefine",),
    definition!("printer_technology", Enum, "FFF"),
    definition!("printer_variant", String, ""),
    definition!("printhost_apikey", String, ""),
    definition!("printhost_authorization_type", Enum, "key",),
    definition!("printhost_cafile", String, ""),
    definition!("printhost_password", String, ""),
    definition!("printhost_port", String, ""),
    definition!("printhost_ssl_ignore_revoke", Bool, "false",),
];
