use super::{OptionDefinition, OptionValueKind};

pub(super) const LATE_TAIL_AFTER_MATERIAL_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!(
        "max_bridge_length",
        Float,
        "10",
        "PrintConfig.hpp:932; PrintConfig.cpp:1931-1938",
    ),
    definition!(
        "max_exposure_time",
        Float,
        "100",
        "PrintConfig.hpp:1849; PrintConfig.cpp:7441-7447",
    ),
    definition!(
        "max_initial_exposure_time",
        Float,
        "150",
        "PrintConfig.hpp:1851; PrintConfig.cpp:7464-7470",
    ),
    definition!(
        "max_layer_height",
        Floats,
        "0",
        "PrintConfig.hpp:1536; PrintConfig.cpp:4601-4608",
    ),
    definition!(
        "max_resonance_avoidance_speed",
        Float,
        "120",
        "PrintConfig.hpp:1279; PrintConfig.cpp:4533-4539",
    ),
    definition!(
        "max_travel_detour_distance",
        FloatOrPercent,
        "0",
        "PrintConfig.hpp:1480; PrintConfig.cpp:911-921",
    ),
    definition!(
        "max_volumetric_extrusion_rate_slope",
        Float,
        "0",
        "PrintConfig.hpp:1362; PrintConfig.cpp:4610-4629",
    ),
    definition!(
        "max_volumetric_extrusion_rate_slope_segment_length",
        Float,
        "3.0",
        "PrintConfig.hpp:1363; PrintConfig.cpp:4631-4641",
    ),
    definition!(
        "min_bead_width",
        Percent,
        "85",
        "PrintConfig.hpp:1027; PrintConfig.cpp:7109-7119",
    ),
    definition!(
        "min_exposure_time",
        Float,
        "0",
        "PrintConfig.hpp:1848; PrintConfig.cpp:7433-7439",
    ),
    definition!(
        "min_feature_size",
        Percent,
        "25",
        "PrintConfig.hpp:1025; PrintConfig.cpp:7051-7060",
    ),
    definition!(
        "min_initial_exposure_time",
        Float,
        "0",
        "PrintConfig.hpp:1850; PrintConfig.cpp:7456-7462",
    ),
    definition!(
        "min_layer_height",
        Floats,
        "0.07",
        "PrintConfig.hpp:1538; PrintConfig.cpp:4697-4704",
    ),
    definition!(
        "min_length_factor",
        Float,
        "0.5",
        "PrintConfig.hpp:1039; PrintConfig.cpp:7062-7074",
    ),
    definition!(
        "min_resonance_avoidance_speed",
        Float,
        "70",
        "PrintConfig.hpp:1278; PrintConfig.cpp:4525-4531",
    ),
    definition!(
        "min_skirt_length",
        Float,
        "0",
        "PrintConfig.hpp:1558; PrintConfig.cpp:5618-5627",
    ),
    definition!(
        "min_width_top_surface",
        FloatOrPercent,
        "300%",
        "PrintConfig.hpp:1179; PrintConfig.cpp:1418-1431",
    ),
    definition!(
        "minimum_sparse_infill_area",
        Float,
        "15",
        "PrintConfig.hpp:1160; PrintConfig.cpp:5639-5646",
    ),
    definition!(
        "mmu_segmented_region_interlocking_depth",
        Float,
        "0",
        "PrintConfig.hpp:938; PrintConfig.cpp:4095-4104",
    ),
    definition!(
        "mmu_segmented_region_max_width",
        Float,
        "0",
        "PrintConfig.hpp:937; PrintConfig.cpp:4086-4093",
    ),
    definition!(
        "notes",
        String,
        "",
        "PrintConfig.hpp:1633; PrintConfig.cpp:4723-4731",
    ),
    definition!(
        "nozzle_diameter",
        Floats,
        "0.4",
        "PrintConfig.hpp:1543; PrintConfig.cpp:4715-4721",
    ),
    definition!(
        "nozzle_flush_dataset",
        IntsNullable,
        "0",
        "PrintConfig.hpp:1342; PrintConfig.cpp:2514-2516",
    ),
    definition!(
        "nozzle_height",
        Float,
        "2.5",
        "PrintConfig.hpp:1516; PrintConfig.cpp:2154-2160",
    ),
    definition!(
        "nozzle_hrc",
        Int,
        "0",
        "PrintConfig.hpp:1403; PrintConfig.cpp:3672-3679",
    ),
    definition!(
        "nozzle_temperature",
        Ints,
        "200",
        "PrintConfig.hpp:1568; PrintConfig.cpp:6478-6485",
    ),
    definition!(
        "nozzle_temperature_initial_layer",
        Ints,
        "200",
        "PrintConfig.hpp:1533; PrintConfig.cpp:3316-3323",
    ),
    definition!(
        "nozzle_temperature_range_high",
        Ints,
        "240",
        "PrintConfig.hpp:1572; PrintConfig.cpp:6495-6501",
    ),
    definition!(
        "nozzle_temperature_range_low",
        Ints,
        "190",
        "PrintConfig.hpp:1571; PrintConfig.cpp:6487-6493",
    ),
    definition!(
        "nozzle_type",
        EnumsNullable,
        "undefine",
        "CommonDefs.hpp:12-20; PrintConfig.hpp:338-353; PrintConfig.hpp:1402; PrintConfig.cpp:485-492; PrintConfig.cpp:3652-3669",
    ),
    definition!(
        "nozzle_volume",
        FloatsNullable,
        "0.0",
        "PrintConfig.hpp:1613; PrintConfig.cpp:4770-4777",
    ),
    definition!(
        "nozzle_volume_type",
        Enums,
        "Standard",
        "PrintConfig.hpp:418-421; PrintConfig.hpp:1409; PrintConfig.cpp:571-575; PrintConfig.cpp:5215-5225",
    ),
    definition!(
        "only_one_wall_first_layer",
        Bool,
        "false",
        "PrintConfig.hpp:1180; PrintConfig.cpp:1433-1437",
    ),
    definition!(
        "only_one_wall_top",
        Bool,
        "false",
        "PrintConfig.hpp:1176; PrintConfig.cpp:1411-1415",
    ),
    definition!(
        "ooze_prevention",
        Bool,
        "false",
        "PrintConfig.hpp:1545; PrintConfig.cpp:4837-4841",
    ),
    definition!(
        "other_layers_print_sequence",
        Ints,
        "0",
        "PrintConfig.hpp:1508; PrintConfig.cpp:1078-1082",
    ),
    definition!(
        "other_layers_print_sequence_nums",
        Int,
        "0",
        "PrintConfig.hpp:1509; PrintConfig.cpp:1084-1086",
    ),
    definition!(
        "other_layers_sequence_choice",
        Enum,
        "Auto",
        "PrintConfig.hpp:333-335; PrintConfig.cpp:479-483; PrintConfig.cpp:1099-1108",
    ),
    definition!(
        "outer_wall_acceleration",
        Float,
        "500",
        "PrintConfig.hpp:1043; PrintConfig.cpp:3095-3102",
    ),
    definition!(
        "outer_wall_flow_ratio",
        Float,
        "1",
        "PrintConfig.hpp:1216; PrintConfig.cpp:1324-1333",
    ),
    definition!(
        "outer_wall_jerk",
        Float,
        "9",
        "PrintConfig.hpp:1053; PrintConfig.cpp:3188-3195",
    ),
    definition!(
        "outer_wall_line_width",
        FloatOrPercent,
        "0",
        "PrintConfig.cpp:2027-2037",
    ),
    definition!("outer_wall_speed", Float, "60", "PrintConfig.cpp:2039-2047",),
    definition!(
        "overhang_1_4_speed",
        FloatOrPercent,
        "0",
        "PrintConfig.hpp:1172; PrintConfig.cpp:1524-1534",
    ),
    definition!(
        "overhang_2_4_speed",
        FloatOrPercent,
        "0",
        "PrintConfig.hpp:1173; PrintConfig.cpp:1536-1546",
    ),
    definition!(
        "overhang_3_4_speed",
        FloatOrPercent,
        "0",
        "PrintConfig.hpp:1174; PrintConfig.cpp:1548-1558",
    ),
    definition!(
        "overhang_4_4_speed",
        FloatOrPercent,
        "0",
        "PrintConfig.hpp:1175; PrintConfig.cpp:1560-1570",
    ),
    definition!(
        "overhang_fan_speed",
        Ints,
        "100",
        "PrintConfig.hpp:1503; PrintConfig.cpp:1177-1188",
    ),
    definition!(
        "overhang_fan_threshold",
        Enums,
        "95%",
        "PrintConfig.hpp:304-310; PrintConfig.hpp:1504; PrintConfig.cpp:456-464; PrintConfig.cpp:1190-1211",
    ),
    definition!(
        "overhang_flow_ratio",
        Float,
        "1",
        "PrintConfig.hpp:1218; PrintConfig.cpp:1344-1353",
    ),
    definition!(
        "overhang_reverse",
        Bool,
        "false",
        "PrintConfig.hpp:1205; PrintConfig.cpp:1446-1452",
    ),
    definition!(
        "overhang_reverse_internal_only",
        Bool,
        "false",
        "PrintConfig.hpp:1206; PrintConfig.cpp:1454-1465",
    ),
    definition!(
        "overhang_reverse_threshold",
        FloatOrPercent,
        "50%",
        "PrintConfig.hpp:1207; PrintConfig.cpp:1485-1498",
    ),
    definition!(
        "pad_around_object",
        Bool,
        "false",
        "PrintConfig.hpp:1766; PrintConfig.cpp:7768-7773",
    ),
    definition!(
        "pad_around_object_everywhere",
        Bool,
        "false",
        "PrintConfig.hpp:1768; PrintConfig.cpp:7775-7780",
    ),
    definition!(
        "pad_brim_size",
        Float,
        "1.6",
        "PrintConfig.hpp:1745; PrintConfig.cpp:7739-7747",
    ),
    definition!(
        "pad_enable",
        Bool,
        "true",
        "PrintConfig.hpp:1736; PrintConfig.cpp:7712-7717",
    ),
    definition!(
        "pad_max_merge_distance",
        Float,
        "50",
        "PrintConfig.hpp:1749; PrintConfig.cpp:7749-7756",
    ),
    definition!(
        "pad_object_connector_penetration",
        Float,
        "0.3",
        "PrintConfig.hpp:1780; PrintConfig.cpp:7810-7817",
    ),
    definition!(
        "pad_object_connector_stride",
        Float,
        "10",
        "PrintConfig.hpp:1774; PrintConfig.cpp:7792-7799",
    ),
    definition!(
        "pad_object_connector_width",
        Float,
        "0.5",
        "PrintConfig.hpp:1777; PrintConfig.cpp:7801-7808",
    ),
    definition!(
        "pad_object_gap",
        Float,
        "1",
        "PrintConfig.hpp:1771; PrintConfig.cpp:7782-7790",
    ),
    definition!(
        "pad_wall_height",
        Float,
        "0",
        "PrintConfig.hpp:1742; PrintConfig.cpp:7729-7737",
    ),
    definition!(
        "pad_wall_slope",
        Float,
        "90",
        "PrintConfig.hpp:1755; PrintConfig.cpp:7758-7766",
    ),
    definition!(
        "pad_wall_thickness",
        Float,
        "2",
        "PrintConfig.hpp:1739; PrintConfig.cpp:7719-7727",
    ),
];
