use super::{OptionDefinition, OptionValueKind};

pub(super) const LATE_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!("is_infill_first", Bool, "false",),
    definition!("lateral_lattice_angle_1", Float, "-45",),
    definition!("lateral_lattice_angle_2", Float, "45",),
    definition!("layer_change_gcode", String, "",),
    definition!("layer_height", Float, "0.2"),
    definition!("line_width", FloatOrPercent, "0",),
    definition!("long_retractions_when_cut", Bools, "false",),
    definition!("long_retractions_when_ec", BoolsNullable, "false",),
    definition!(
        "machine_end_gcode",
        String,
        "M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n",
    ),
    definition!("machine_load_filament_time", Float, "0",),
    definition!("machine_max_acceleration_e", Floats, "5000,5000",),
    definition!("machine_max_acceleration_extruding", Floats, "1500,1250",),
    definition!("machine_max_acceleration_retracting", Floats, "1500,1250",),
    definition!("machine_max_acceleration_travel", Floats, "0,0",),
    definition!("machine_max_acceleration_x", Floats, "1000,1000",),
    definition!("machine_max_acceleration_y", Floats, "1000,1000",),
    definition!("machine_max_acceleration_z", Floats, "500,200",),
    definition!("machine_max_jerk_e", Floats, "2.5,2.5",),
    definition!("machine_max_jerk_x", Floats, "10,10",),
    definition!("machine_max_jerk_y", Floats, "10,10",),
    definition!("machine_max_jerk_z", Floats, "0.2,0.4",),
    definition!("machine_max_junction_deviation", Floats, "0.01",),
    definition!("machine_max_speed_e", Floats, "120,120",),
    definition!("machine_max_speed_x", Floats, "500,200",),
    definition!("machine_max_speed_y", Floats, "500,200",),
    definition!("machine_max_speed_z", Floats, "12,12",),
    definition!("machine_min_extruding_rate", Floats, "0,0",),
    definition!("machine_min_travel_rate", Floats, "0,0",),
    definition!("machine_pause_gcode", String, "",),
    definition!(
        "machine_start_gcode",
        String,
        "G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n",
    ),
    definition!("machine_tool_change_time", Float, "0",),
    definition!("machine_unload_filament_time", Float, "0",),
];
