use super::{OptionDefinition, OptionValueKind};

pub(super) const LATE_TAIL_FINAL_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!(
        "post_process",
        Strings,
        "",
        "PrintConfig.hpp:1547; PrintConfig.cpp:4935-4946",
    ),
    definition!(
        "precise_outer_wall",
        Bool,
        "true",
        "PrintConfig.hpp:1188; PrintConfig.cpp:1404-1409",
    ),
    definition!(
        "precise_z_height",
        Bool,
        "false",
        "PrintConfig.hpp:1059; PrintConfig.cpp:3597-3604",
    ),
    definition!(
        "preferred_orientation",
        Float,
        "0",
        "PrintConfig.cpp:775-782",
    ),
    definition!(
        "preheat_steps",
        Int,
        "1",
        "PrintConfig.hpp:1567; PrintConfig.cpp:5767-5774",
    ),
    definition!(
        "preheat_time",
        Float,
        "30",
        "PrintConfig.hpp:1566; PrintConfig.cpp:5757-5765",
    ),
    definition!("preset_name", String, "", "PrintConfig.cpp:890-894",),
    definition!(
        "preset_names",
        Strings,
        "",
        "PrintConfig.cpp:786-790,872-876",
    ),
    definition!(
        "pressure_advance",
        Floats,
        "0.02",
        "PrintConfig.hpp:1303; PrintConfig.cpp:2257-2262",
    ),
    definition!(
        "prime_tower_brim_width",
        Float,
        "3",
        "PrintConfig.hpp:1582; PrintConfig.cpp:6725-6734",
    ),
    definition!(
        "prime_tower_enable_framework",
        Bool,
        "false",
        "PrintConfig.hpp:1575; PrintConfig.cpp:6653-6657",
    ),
    definition!(
        "prime_tower_flat_ironing",
        Bool,
        "false",
        "PrintConfig.hpp:1585; PrintConfig.cpp:6823-6825",
    ),
    definition!(
        "prime_tower_infill_gap",
        Percent,
        "150",
        "PrintConfig.hpp:1583; PrintConfig.cpp:6839-6845",
    ),
    definition!(
        "prime_tower_skip_points",
        Bool,
        "true",
        "PrintConfig.hpp:1584; PrintConfig.cpp:6817-6821",
    ),
    definition!(
        "prime_tower_width",
        Float,
        "60",
        "PrintConfig.hpp:1579; PrintConfig.cpp:6710-6716",
    ),
    definition!(
        "prime_volume",
        Float,
        "45",
        "PrintConfig.hpp:1607; PrintConfig.cpp:6686-6692",
    ),
    definition!(
        "print_compatible_printers",
        Strings,
        "",
        "PrintConfig.cpp:1746-1748",
    ),
    definition!(
        "print_extruder_id",
        Ints,
        "1",
        "PrintConfig.hpp:1077; PrintConfig.cpp:5272-5277",
    ),
    definition!(
        "print_extruder_variant",
        Strings,
        "Direct Drive Standard",
        "PrintConfig.hpp:1078; PrintConfig.cpp:5279-5284",
    ),
    definition!("print_flow_ratio", Float, "1", "PrintConfig.cpp:2239-2250",),
    definition!("print_host", String, "", "PrintConfig.cpp:806-814",),
    definition!("print_host_webui", String, "", "PrintConfig.cpp:816-821",),
    definition!(
        "print_order",
        Enum,
        "default",
        "PrintConfig.hpp:155-159; PrintConfig.hpp:1506; PrintConfig.cpp:299-303; PrintConfig.cpp:1761-1770",
    ),
    definition!(
        "print_sequence",
        Enum,
        "by layer",
        "PrintConfig.hpp:148-153; PrintConfig.hpp:1505; PrintConfig.cpp:293-297; PrintConfig.cpp:1750-1759",
    ),
    definition!("print_settings_id", String, "", "PrintConfig.cpp:4978-4981",),
    definition!(
        "printable_area",
        Points,
        "0x0,200x0,200x200,0x200",
        "PrintConfig.cpp:684-688",
    ),
    definition!("printable_height", Float, "100", "PrintConfig.cpp:757-764",),
    definition!("printer_agent", String, "", "PrintConfig.cpp:799-804",),
    definition!(
        "printer_extruder_id",
        Ints,
        "1",
        "PrintConfig.hpp:1411; PrintConfig.cpp:5252-5257",
    ),
    definition!(
        "printer_extruder_variant",
        Strings,
        "Direct Drive Standard",
        "PrintConfig.hpp:1413; PrintConfig.cpp:5259-5264",
    ),
    definition!(
        "printer_model",
        String,
        "",
        "PrintConfig.hpp:1548; PrintConfig.cpp:4957-4961",
    ),
    definition!(
        "printer_notes",
        String,
        "",
        "PrintConfig.hpp:1634; PrintConfig.cpp:4963-4970",
    ),
    definition!(
        "printer_settings_id",
        String,
        "",
        "PrintConfig.cpp:4983-4986",
    ),
    definition!(
        "printer_structure",
        Enum,
        "undefine",
        "PrintConfig.hpp:357-363; PrintConfig.hpp:1406; PrintConfig.cpp:494-501; PrintConfig.cpp:3681-3696",
    ),
    definition!("printer_technology", Enum, "FFF", "PrintConfig.cpp:676-682",),
    definition!("printer_variant", String, "", "PrintConfig.cpp:4972-4976",),
    definition!("printhost_apikey", String, "", "PrintConfig.cpp:823-829",),
    definition!(
        "printhost_authorization_type",
        Enum,
        "key",
        "PrintConfig.hpp:83-85; PrintConfig.cpp:155-159; PrintConfig.cpp:878-888",
    ),
    definition!("printhost_cafile", String, "", "PrintConfig.cpp:839-845",),
    definition!("printhost_password", String, "", "PrintConfig.cpp:856-861",),
    definition!("printhost_port", String, "", "PrintConfig.cpp:831-837",),
    definition!(
        "printhost_ssl_ignore_revoke",
        Bool,
        "false",
        "PrintConfig.cpp:863-870",
    ),
];
