use super::{OptionDefinition, OptionValueKind};

pub(super) const LATE_TAIL_AFTER_MATERIAL_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!("max_bridge_length", Float, "10",),
    definition!("max_exposure_time", Float, "100",),
    definition!("max_initial_exposure_time", Float, "150",),
    definition!("max_layer_height", Floats, "0",),
    definition!("max_resonance_avoidance_speed", Float, "120",),
    definition!("max_travel_detour_distance", FloatOrPercent, "0",),
    definition!("max_volumetric_extrusion_rate_slope", Float, "0",),
    definition!(
        "max_volumetric_extrusion_rate_slope_segment_length",
        Float,
        "3.0",
    ),
    definition!("min_bead_width", Percent, "85",),
    definition!("min_exposure_time", Float, "0",),
    definition!("min_feature_size", Percent, "25",),
    definition!("min_initial_exposure_time", Float, "0",),
    definition!("min_layer_height", Floats, "0.07",),
    definition!("min_length_factor", Float, "0.5",),
    definition!("min_resonance_avoidance_speed", Float, "70",),
    definition!("min_skirt_length", Float, "0",),
    definition!("min_width_top_surface", FloatOrPercent, "300%",),
    definition!("minimum_sparse_infill_area", Float, "15",),
    definition!("mmu_segmented_region_interlocking_depth", Float, "0",),
    definition!("mmu_segmented_region_max_width", Float, "0",),
    definition!("notes", String, "",),
    definition!("nozzle_diameter", Floats, "0.4",),
    definition!("nozzle_flush_dataset", IntsNullable, "0",),
    definition!("nozzle_height", Float, "2.5",),
    definition!("nozzle_hrc", Int, "0",),
    definition!("nozzle_temperature", Ints, "200",),
    definition!("nozzle_temperature_initial_layer", Ints, "200",),
    definition!("nozzle_temperature_range_high", Ints, "240",),
    definition!("nozzle_temperature_range_low", Ints, "190",),
    definition!("nozzle_type", EnumsNullable, "undefine",),
    definition!("nozzle_volume", FloatsNullable, "0.0",),
    definition!("nozzle_volume_type", Enums, "Standard",),
    definition!("only_one_wall_first_layer", Bool, "false",),
    definition!("only_one_wall_top", Bool, "false",),
    definition!("ooze_prevention", Bool, "false",),
    definition!("other_layers_print_sequence", Ints, "0",),
    definition!("other_layers_print_sequence_nums", Int, "0",),
    definition!("other_layers_sequence_choice", Enum, "Auto",),
    definition!("outer_wall_acceleration", Float, "500",),
    definition!("outer_wall_flow_ratio", Float, "1",),
    definition!("outer_wall_jerk", Float, "9",),
    definition!("outer_wall_line_width", FloatOrPercent, "0",),
    definition!("outer_wall_speed", Float, "60"),
    definition!("overhang_1_4_speed", FloatOrPercent, "0",),
    definition!("overhang_2_4_speed", FloatOrPercent, "0",),
    definition!("overhang_3_4_speed", FloatOrPercent, "0",),
    definition!("overhang_4_4_speed", FloatOrPercent, "0",),
    definition!("overhang_fan_speed", Ints, "100",),
    definition!("overhang_fan_threshold", Enums, "95%",),
    definition!("overhang_flow_ratio", Float, "1",),
    definition!("overhang_reverse", Bool, "false",),
    definition!("overhang_reverse_internal_only", Bool, "false",),
    definition!("overhang_reverse_threshold", FloatOrPercent, "50%",),
    definition!("pad_around_object", Bool, "false",),
    definition!("pad_around_object_everywhere", Bool, "false",),
    definition!("pad_brim_size", Float, "1.6",),
    definition!("pad_enable", Bool, "true",),
    definition!("pad_max_merge_distance", Float, "50",),
    definition!("pad_object_connector_penetration", Float, "0.3",),
    definition!("pad_object_connector_stride", Float, "10",),
    definition!("pad_object_connector_width", Float, "0.5",),
    definition!("pad_object_gap", Float, "1",),
    definition!("pad_wall_height", Float, "0",),
    definition!("pad_wall_slope", Float, "90",),
    definition!("pad_wall_thickness", Float, "2",),
];
