use super::{OptionDefinition, OptionValueKind};

pub(super) const MIDDLE_INDEPENDENT_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!(
        "idle_temperature",
        Ints,
        "0",
        "PrintConfig.hpp:1603; PrintConfig.cpp:6898-6905",
    ),
    definition!(
        "independent_support_layer_height",
        Bool,
        "true",
        "PrintConfig.hpp:1618; PrintConfig.cpp:6232-6238",
    ),
    definition!(
        "infill_anchor",
        FloatOrPercent,
        "400%",
        "PrintConfig.hpp:1195; PrintConfig.cpp:3017-3043",
    ),
    definition!(
        "infill_anchor_max",
        FloatOrPercent,
        "20",
        "PrintConfig.hpp:1196; PrintConfig.cpp:3045-3066",
    ),
    definition!(
        "infill_combination",
        Bool,
        "false",
        "PrintConfig.hpp:1132; PrintConfig.cpp:3853-3860",
    ),
    definition!(
        "infill_combination_max_layer_height",
        FloatOrPercent,
        "100%",
        "PrintConfig.hpp:1134; PrintConfig.cpp:3972-3984",
    ),
    definition!(
        "infill_direction",
        Float,
        "45",
        "PrintConfig.hpp:1095; PrintConfig.cpp:2861-2869",
    ),
    definition!(
        "infill_jerk",
        Float,
        "9",
        "PrintConfig.hpp:1055; PrintConfig.cpp:3215-3222",
    ),
    definition!(
        "infill_lock_depth",
        Float,
        "1",
        "PrintConfig.hpp:1128; PrintConfig.cpp:3934-3942",
    ),
    definition!(
        "infill_overhang_angle",
        Float,
        "60",
        "PrintConfig.hpp:1105; PrintConfig.cpp:3007-3015",
    ),
    definition!(
        "infill_shift_step",
        Float,
        "0.4",
        "PrintConfig.hpp:1099; PrintConfig.cpp:3862-3870",
    ),
    definition!(
        "infill_wall_overlap",
        Percent,
        "15",
        "PrintConfig.hpp:1123; PrintConfig.cpp:4028-4039",
    ),
    definition!("inherits", String, "", "PrintConfig.cpp:4063-4069",),
    definition!("inherits_group", Strings, "", "PrintConfig.cpp:4071-4075",),
    definition!(
        "initial_exposure_time",
        Float,
        "15",
        "PrintConfig.hpp:1816; PrintConfig.cpp:7472-7477",
    ),
    definition!(
        "initial_layer_acceleration",
        Float,
        "300",
        "PrintConfig.hpp:1046; PrintConfig.cpp:3134-3141",
    ),
    definition!(
        "initial_layer_height",
        Float,
        "0.3",
        "PrintConfig.cpp:7390-7395",
    ),
    definition!(
        "initial_layer_infill_speed",
        Float,
        "60",
        "PrintConfig.hpp:1532; PrintConfig.cpp:3288-3294",
    ),
    definition!(
        "initial_layer_jerk",
        Float,
        "9",
        "PrintConfig.hpp:1057; PrintConfig.cpp:3224-3231",
    ),
    definition!(
        "initial_layer_line_width",
        FloatOrPercent,
        "0",
        "PrintConfig.hpp:1527; PrintConfig.cpp:3251-3261",
    ),
    definition!(
        "initial_layer_min_bead_width",
        Percent,
        "85",
        "PrintConfig.hpp:1026; PrintConfig.cpp:7099-7107",
    ),
    definition!(
        "initial_layer_print_height",
        Float,
        "0.2",
        "PrintConfig.hpp:1528; PrintConfig.cpp:3264-3270",
    ),
    definition!(
        "initial_layer_speed",
        Float,
        "30",
        "PrintConfig.hpp:1529; PrintConfig.cpp:3280-3286",
    ),
    definition!(
        "initial_layer_travel_acceleration",
        FloatOrPercent,
        "100%",
        "PrintConfig.hpp:1422; PrintConfig.cpp:3143-3150",
    ),
    definition!(
        "initial_layer_travel_jerk",
        FloatOrPercent,
        "100%",
        "PrintConfig.hpp:1423; PrintConfig.cpp:3242-3249",
    ),
    definition!(
        "initial_layer_travel_speed",
        FloatOrPercent,
        "100%",
        "PrintConfig.hpp:1421; PrintConfig.cpp:3296-3304",
    ),
    definition!(
        "inner_wall_acceleration",
        Float,
        "10000",
        "PrintConfig.hpp:1044; PrintConfig.cpp:3068-3075",
    ),
    definition!(
        "inner_wall_flow_ratio",
        Float,
        "1",
        "PrintConfig.hpp:1217; PrintConfig.cpp:1334-1343",
    ),
    definition!(
        "inner_wall_jerk",
        Float,
        "9",
        "PrintConfig.hpp:1054; PrintConfig.cpp:3197-3204",
    ),
    definition!(
        "inner_wall_line_width",
        FloatOrPercent,
        "0",
        "PrintConfig.hpp:1155; PrintConfig.cpp:4896-4906",
    ),
    definition!(
        "inner_wall_speed",
        Float,
        "60",
        "PrintConfig.hpp:1156; PrintConfig.cpp:4908-4916",
    ),
    definition!(
        "input_shaping_damp_x",
        Float,
        "0.1",
        "PrintConfig.hpp:1286; PrintConfig.cpp:4575-4581",
    ),
    definition!(
        "input_shaping_damp_y",
        Float,
        "0.1",
        "PrintConfig.hpp:1287; PrintConfig.cpp:4583-4589",
    ),
    definition!(
        "input_shaping_emit",
        Bool,
        "false",
        "PrintConfig.hpp:1282; PrintConfig.cpp:4541-4546",
    ),
    definition!(
        "input_shaping_freq_x",
        Float,
        "0",
        "PrintConfig.hpp:1284; PrintConfig.cpp:4557-4564",
    ),
    definition!(
        "input_shaping_freq_y",
        Float,
        "0",
        "PrintConfig.hpp:1285; PrintConfig.cpp:4566-4573",
    ),
    definition!(
        "input_shaping_type",
        Enum,
        "Default",
        "PrintConfig.hpp:365-379; PrintConfig.hpp:544; PrintConfig.hpp:1283; PrintConfig.cpp:503-518; PrintConfig.cpp:4548-4555",
    ),
];
