use super::{OptionDefinition, OptionValueKind};

pub(super) const MIDDLE_TAIL_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!("interface_shells", Bool, "false",),
    definition!("interlocking_beam", Bool, "false",),
    definition!("interlocking_beam_layer_count", Int, "2",),
    definition!("interlocking_beam_width", Float, "0.8",),
    definition!("interlocking_boundary_avoidance", Int, "2",),
    definition!("interlocking_depth", Int, "2",),
    definition!("interlocking_orientation", Float, "22.5",),
    definition!("internal_bridge_angle", Float, "0",),
    definition!("internal_bridge_density", Percent, "100",),
    definition!("internal_bridge_fan_speed", Ints, "-1",),
    definition!("internal_bridge_flow", Float, "1",),
    definition!("internal_bridge_speed", FloatOrPercent, "150%",),
    definition!("internal_solid_infill_acceleration", FloatOrPercent, "100%",),
    definition!("internal_solid_infill_flow_ratio", Float, "1",),
    definition!("internal_solid_infill_line_width", FloatOrPercent, "0",),
    definition!("internal_solid_infill_pattern", Enum, "monotonic",),
    definition!("internal_solid_infill_speed", Float, "100",),
    definition!("ironing_angle", Float, "0",),
    definition!("ironing_angle_fixed", Bool, "false",),
    definition!("ironing_expansion", Float, "0"),
    definition!("ironing_fan_speed", Ints, "-1",),
    definition!("ironing_flow", Percent, "10",),
    definition!("ironing_inset", Float, "0",),
    definition!("ironing_pattern", Enum, "rectilinear",),
    definition!("ironing_spacing", Float, "0.1",),
    definition!("ironing_speed", Float, "20",),
    definition!("ironing_type", Enum, "no ironing",),
];
