use super::{OptionDefinition, OptionValueKind};

pub(super) const MIDDLE_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!(
        "fill_multiline",
        Int,
        "1",
        "PrintConfig.hpp:1135; PrintConfig.cpp:2906-2913",
    ),
    definition!(
        "filter_out_gap_fill",
        Float,
        "0",
        "PrintConfig.hpp:1190; PrintConfig.cpp:3578-3585",
    ),
    definition!(
        "first_layer_flow_ratio",
        Float,
        "1",
        "PrintConfig.hpp:1215; PrintConfig.cpp:1314-1323",
    ),
    definition!(
        "first_layer_print_sequence",
        Ints,
        "0",
        "PrintConfig.hpp:1507; PrintConfig.cpp:1072-1076",
    ),
    definition!(
        "first_layer_sequence_choice",
        Enum,
        "Auto",
        "PrintConfig.hpp:333-335; PrintConfig.cpp:479-483; PrintConfig.cpp:1088-1097",
    ),
    definition!(
        "first_x_layer_fan_speed",
        Floats,
        "0",
        "PrintConfig.hpp:1478; PrintConfig.cpp:4688-4695",
    ),
    definition!(
        "flush_into_infill",
        Bool,
        "false",
        "PrintConfig.hpp:1005; PrintConfig.cpp:6847-6854",
    ),
    definition!(
        "flush_into_objects",
        Bool,
        "false",
        "PrintConfig.hpp:1003; PrintConfig.cpp:6864-6870",
    ),
    definition!(
        "flush_into_support",
        Bool,
        "true",
        "PrintConfig.hpp:1006; PrintConfig.cpp:6856-6862",
    ),
    definition!(
        "flush_multiplier",
        Floats,
        "0.3",
        "PrintConfig.hpp:1608; PrintConfig.cpp:6679-6683",
    ),
    definition!(
        "flush_volumes_matrix",
        Floats,
        "0,280,280,280,280,0,280,280,280,280,0,280,280,280,280,0",
        "PrintConfig.hpp:1590; PrintConfig.cpp:6669-6677",
    ),
    definition!(
        "flush_volumes_vector",
        Floats,
        "140,140,140,140,140,140,140,140",
        "PrintConfig.hpp:1591; PrintConfig.cpp:6659-6667",
    ),
    definition!(
        "full_fan_speed_layer",
        Ints,
        "0",
        "PrintConfig.hpp:1534; PrintConfig.cpp:3325-3335",
    ),
    definition!(
        "fuzzy_skin",
        Enum,
        "disabled_fuzzy",
        "PrintConfig.hpp:50-57; PrintConfig.hpp:1108; PrintConfig.cpp:192-200; PrintConfig.cpp:3420-3439",
    ),
    definition!(
        "fuzzy_skin_first_layer",
        Bool,
        "false",
        "PrintConfig.hpp:1111; PrintConfig.cpp:3461-3466",
    ),
    definition!(
        "fuzzy_skin_layers_between_ripple_offset",
        Int,
        "1",
        "PrintConfig.hpp:1119; PrintConfig.cpp:3567-3576",
    ),
    definition!(
        "fuzzy_skin_mode",
        Enum,
        "displacement",
        "PrintConfig.hpp:59-63; PrintConfig.hpp:1113; PrintConfig.cpp:218-223; PrintConfig.cpp:3468-3489",
    ),
    definition!(
        "fuzzy_skin_noise_type",
        Enum,
        "classic",
        "PrintConfig.hpp:65-72; PrintConfig.hpp:1112; PrintConfig.cpp:202-210; PrintConfig.cpp:3491-3515",
    ),
    definition!(
        "fuzzy_skin_octaves",
        Int,
        "4",
        "PrintConfig.hpp:1115; PrintConfig.cpp:3527-3534",
    ),
    definition!(
        "fuzzy_skin_persistence",
        Float,
        "0.5",
        "PrintConfig.hpp:1116; PrintConfig.cpp:3536-3543",
    ),
    definition!(
        "fuzzy_skin_point_distance",
        Float,
        "0.3",
        "PrintConfig.hpp:1110; PrintConfig.cpp:3451-3459",
    ),
    definition!(
        "fuzzy_skin_ripple_offset",
        Percent,
        "50",
        "PrintConfig.hpp:1118; PrintConfig.cpp:3553-3565",
    ),
    definition!(
        "fuzzy_skin_ripples_per_layer",
        Int,
        "15",
        "PrintConfig.hpp:1117; PrintConfig.cpp:3545-3551",
    ),
    definition!(
        "fuzzy_skin_scale",
        Float,
        "1",
        "PrintConfig.hpp:1114; PrintConfig.cpp:3517-3525",
    ),
    definition!(
        "fuzzy_skin_thickness",
        Float,
        "0.2",
        "PrintConfig.hpp:1109; PrintConfig.cpp:3441-3449",
    ),
    definition!(
        "gamma_correction",
        Float,
        "1",
        "PrintConfig.hpp:1844; PrintConfig.cpp:7360-7367",
    ),
    definition!(
        "gap_fill_flow_ratio",
        Float,
        "1",
        "PrintConfig.hpp:1221; PrintConfig.cpp:1374-1383",
    ),
    definition!(
        "gap_fill_target",
        Enum,
        "nowhere",
        "PrintConfig.hpp:241-243; PrintConfig.hpp:1038; PrintConfig.cpp:393-398; PrintConfig.cpp:1141-1168",
    ),
    definition!(
        "gap_infill_speed",
        Float,
        "30",
        "PrintConfig.hpp:1120; PrintConfig.cpp:3587-3594",
    ),
    definition!(
        "gcode_add_line_number",
        Bool,
        "false",
        "PrintConfig.hpp:1353; PrintConfig.cpp:3618-3622",
    ),
    definition!(
        "gcode_comments",
        Bool,
        "false",
        "PrintConfig.hpp:1626; PrintConfig.cpp:3845-3851",
    ),
    definition!(
        "gcode_flavor",
        Enum,
        "marlin",
        "PrintConfig.hpp:33-46; PrintConfig.hpp:1355; PrintConfig.cpp:161-176; PrintConfig.cpp:3785-3817",
    ),
    definition!(
        "gcode_label_objects",
        Bool,
        "true",
        "PrintConfig.hpp:1623; PrintConfig.cpp:3831-3837",
    ),
    definition!(
        "grab_length",
        Floats,
        "0",
        "PrintConfig.hpp:1625; PrintConfig.cpp:2202-2207",
    ),
    definition!(
        "gyroid_optimized",
        Bool,
        "false",
        "PrintConfig.hpp:1136; PrintConfig.cpp:2915-2926",
    ),
    definition!(
        "has_filament_switcher",
        Bool,
        "false",
        "PrintConfig.cpp:2436-2440",
    ),
    definition!(
        "has_scarf_joint_seam",
        Bool,
        "false",
        "PrintConfig.hpp:1466; PrintConfig.cpp:4373-4375",
    ),
    definition!(
        "head_wrap_detect_zone",
        Points,
        "0x0",
        "PrintConfig.hpp:1485; PrintConfig.cpp:6503-6506",
    ),
    definition!(
        "high_current_on_filament_swap",
        Bool,
        "false",
        "PrintConfig.hpp:1430; PrintConfig.cpp:4795-4801",
    ),
    definition!(
        "hole_to_polyhole",
        Bool,
        "false",
        "PrintConfig.hpp:1202; PrintConfig.cpp:6927-6934",
    ),
    definition!(
        "hole_to_polyhole_threshold",
        FloatOrPercent,
        "0.01",
        "PrintConfig.hpp:1203; PrintConfig.cpp:6936-6947",
    ),
    definition!(
        "hole_to_polyhole_twisted",
        Bool,
        "true",
        "PrintConfig.hpp:1204; PrintConfig.cpp:6949-6954",
    ),
    definition!(
        "hollowing_closing_distance",
        Float,
        "2",
        "PrintConfig.hpp:1802; PrintConfig.cpp:7845-7853",
    ),
    definition!(
        "hollowing_enable",
        Bool,
        "false",
        "PrintConfig.hpp:1791; PrintConfig.cpp:7819-7824",
    ),
    definition!(
        "hollowing_min_thickness",
        Float,
        "3",
        "PrintConfig.hpp:1796; PrintConfig.cpp:7826-7834",
    ),
    definition!(
        "hollowing_quality",
        Float,
        "0.5",
        "PrintConfig.hpp:1799; PrintConfig.cpp:7836-7843",
    ),
    definition!(
        "host_type",
        Enum,
        "octoprint",
        "PrintConfig.hpp:79-81; PrintConfig.cpp:137-153; PrintConfig.cpp:4733-4768",
    ),
    definition!(
        "hot_plate_temp",
        Ints,
        "45",
        "PrintConfig.hpp:1494; PrintConfig.cpp:964-972",
    ),
    definition!(
        "hot_plate_temp_initial_layer",
        Ints,
        "45",
        "PrintConfig.hpp:1500; PrintConfig.cpp:1024-1031",
    ),
];
