use super::{OptionDefinition, OptionValueKind};

pub(super) const MIDDLE_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!("fill_multiline", Int, "1",),
    definition!("filter_out_gap_fill", Float, "0",),
    definition!("first_layer_flow_ratio", Float, "1",),
    definition!("first_layer_print_sequence", Ints, "0",),
    definition!("first_layer_sequence_choice", Enum, "Auto",),
    definition!("first_x_layer_fan_speed", Floats, "0",),
    definition!("flush_into_infill", Bool, "false",),
    definition!("flush_into_objects", Bool, "false",),
    definition!("flush_into_support", Bool, "true",),
    definition!("flush_multiplier", Floats, "0.3",),
    definition!(
        "flush_volumes_matrix",
        Floats,
        "0,280,280,280,280,0,280,280,280,280,0,280,280,280,280,0",
    ),
    definition!(
        "flush_volumes_vector",
        Floats,
        "140,140,140,140,140,140,140,140",
    ),
    definition!("full_fan_speed_layer", Ints, "0",),
    definition!("fuzzy_skin", Enum, "disabled_fuzzy",),
    definition!("fuzzy_skin_first_layer", Bool, "false",),
    definition!("fuzzy_skin_layers_between_ripple_offset", Int, "1",),
    definition!("fuzzy_skin_mode", Enum, "displacement",),
    definition!("fuzzy_skin_noise_type", Enum, "classic",),
    definition!("fuzzy_skin_octaves", Int, "4",),
    definition!("fuzzy_skin_persistence", Float, "0.5",),
    definition!("fuzzy_skin_point_distance", Float, "0.3",),
    definition!("fuzzy_skin_ripple_offset", Percent, "50",),
    definition!("fuzzy_skin_ripples_per_layer", Int, "15",),
    definition!("fuzzy_skin_scale", Float, "1",),
    definition!("fuzzy_skin_thickness", Float, "0.2",),
    definition!("gamma_correction", Float, "1",),
    definition!("gap_fill_flow_ratio", Float, "1",),
    definition!("gap_fill_target", Enum, "nowhere",),
    definition!("gap_infill_speed", Float, "30",),
    definition!("gcode_add_line_number", Bool, "false",),
    definition!("gcode_comments", Bool, "false",),
    definition!("gcode_flavor", Enum, "marlin",),
    definition!("gcode_label_objects", Bool, "true",),
    definition!("grab_length", Floats, "0",),
    definition!("gyroid_optimized", Bool, "false",),
    definition!("has_filament_switcher", Bool, "false",),
    definition!("has_scarf_joint_seam", Bool, "false",),
    definition!("head_wrap_detect_zone", Points, "0x0",),
    definition!("high_current_on_filament_swap", Bool, "false",),
    definition!("hole_to_polyhole", Bool, "false",),
    definition!("hole_to_polyhole_threshold", FloatOrPercent, "0.01",),
    definition!("hole_to_polyhole_twisted", Bool, "true",),
    definition!("hollowing_closing_distance", Float, "2",),
    definition!("hollowing_enable", Bool, "false",),
    definition!("hollowing_min_thickness", Float, "3",),
    definition!("hollowing_quality", Float, "0.5",),
    definition!("host_type", Enum, "octoprint",),
    definition!("hot_plate_temp", Ints, "45",),
    definition!("hot_plate_temp_initial_layer", Ints, "45",),
];
