use super::{OptionDefinition, OptionValueKind};

pub(super) const MIDDLE_INDEPENDENT_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!("idle_temperature", Ints, "0",),
    definition!("independent_support_layer_height", Bool, "true",),
    definition!("infill_anchor", FloatOrPercent, "400%",),
    definition!("infill_anchor_max", FloatOrPercent, "20",),
    definition!("infill_combination", Bool, "false",),
    definition!(
        "infill_combination_max_layer_height",
        FloatOrPercent,
        "100%",
    ),
    definition!("infill_direction", Float, "45",),
    definition!("infill_jerk", Float, "9",),
    definition!("infill_lock_depth", Float, "1",),
    definition!("infill_overhang_angle", Float, "60",),
    definition!("infill_shift_step", Float, "0.4",),
    definition!("infill_wall_overlap", Percent, "15",),
    definition!("inherits", String, ""),
    definition!("inherits_group", Strings, ""),
    definition!("initial_exposure_time", Float, "15",),
    definition!("initial_layer_acceleration", Float, "300",),
    definition!("initial_layer_height", Float, "0.3",),
    definition!("initial_layer_infill_speed", Float, "60",),
    definition!("initial_layer_jerk", Float, "9",),
    definition!("initial_layer_line_width", FloatOrPercent, "0",),
    definition!("initial_layer_min_bead_width", Percent, "85",),
    definition!("initial_layer_print_height", Float, "0.2",),
    definition!("initial_layer_speed", Float, "30",),
    definition!("initial_layer_travel_acceleration", FloatOrPercent, "100%",),
    definition!("initial_layer_travel_jerk", FloatOrPercent, "100%",),
    definition!("initial_layer_travel_speed", FloatOrPercent, "100%",),
    definition!("inner_wall_acceleration", Float, "10000",),
    definition!("inner_wall_flow_ratio", Float, "1",),
    definition!("inner_wall_jerk", Float, "9",),
    definition!("inner_wall_line_width", FloatOrPercent, "0",),
    definition!("inner_wall_speed", Float, "60",),
    definition!("input_shaping_damp_x", Float, "0.1",),
    definition!("input_shaping_damp_y", Float, "0.1",),
    definition!("input_shaping_emit", Bool, "false",),
    definition!("input_shaping_freq_x", Float, "0",),
    definition!("input_shaping_freq_y", Float, "0",),
    definition!("input_shaping_type", Enum, "Default",),
];
