use super::{OptionDefinition, OptionValueKind};

pub(super) const MIDDLE_TAIL_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!(
        "interface_shells",
        Bool,
        "false",
        "PrintConfig.hpp:935; PrintConfig.cpp:4077-4084",
    ),
    definition!(
        "interlocking_beam",
        Bool,
        "false",
        "PrintConfig.hpp:1062; PrintConfig.cpp:4106-4111",
    ),
    definition!(
        "interlocking_beam_layer_count",
        Int,
        "2",
        "PrintConfig.hpp:1065; PrintConfig.cpp:4132-4138",
    ),
    definition!(
        "interlocking_beam_width",
        Float,
        "0.8",
        "PrintConfig.hpp:1063; PrintConfig.cpp:4113-4120",
    ),
    definition!(
        "interlocking_boundary_avoidance",
        Int,
        "2",
        "PrintConfig.hpp:1067; PrintConfig.cpp:4148-4154",
    ),
    definition!(
        "interlocking_depth",
        Int,
        "2",
        "PrintConfig.hpp:1066; PrintConfig.cpp:4140-4146",
    ),
    definition!(
        "interlocking_orientation",
        Float,
        "22.5",
        "PrintConfig.hpp:1064; PrintConfig.cpp:4122-4130",
    ),
    definition!(
        "internal_bridge_angle",
        Float,
        "0",
        "PrintConfig.hpp:1082; PrintConfig.cpp:1226-1235",
    ),
    definition!(
        "internal_bridge_density",
        Percent,
        "100",
        "PrintConfig.hpp:991; PrintConfig.cpp:1252-1264",
    ),
    definition!(
        "internal_bridge_fan_speed",
        Ints,
        "-1",
        "PrintConfig.hpp:1629; PrintConfig.cpp:3350-3359",
    ),
    definition!(
        "internal_bridge_flow",
        Float,
        "1",
        "PrintConfig.cpp:1276-1284",
    ),
    definition!(
        "internal_bridge_speed",
        FloatOrPercent,
        "150%",
        "PrintConfig.cpp:1584-1592",
    ),
    definition!(
        "internal_solid_infill_acceleration",
        FloatOrPercent,
        "100%",
        "PrintConfig.hpp:1050; PrintConfig.cpp:3124-3132",
    ),
    definition!(
        "internal_solid_infill_flow_ratio",
        Float,
        "1",
        "PrintConfig.hpp:1220; PrintConfig.cpp:1364-1373",
    ),
    definition!(
        "internal_solid_infill_line_width",
        FloatOrPercent,
        "0",
        "PrintConfig.hpp:1162; PrintConfig.cpp:5657-5667",
    ),
    definition!(
        "internal_solid_infill_pattern",
        Enum,
        "monotonic",
        "PrintConfig.hpp:87-98; PrintConfig.hpp:1092; PrintConfig.cpp:225-255; PrintConfig.cpp:2018-2025",
    ),
    definition!(
        "internal_solid_infill_speed",
        Float,
        "100",
        "PrintConfig.hpp:1163; PrintConfig.cpp:5669-5676",
    ),
    definition!(
        "ironing_angle",
        Float,
        "0",
        "PrintConfig.hpp:1145; PrintConfig.cpp:4231-4239",
    ),
    definition!(
        "ironing_angle_fixed",
        Bool,
        "false",
        "PrintConfig.hpp:1146; PrintConfig.cpp:4241-4246",
    ),
    definition!("ironing_expansion", Float, "0", "PrintConfig.cpp:4248-4256",),
    definition!(
        "ironing_fan_speed",
        Ints,
        "-1",
        "PrintConfig.hpp:1630; PrintConfig.cpp:3361-3370",
    ),
    definition!(
        "ironing_flow",
        Percent,
        "10",
        "PrintConfig.hpp:1140; PrintConfig.cpp:4190-4200",
    ),
    definition!(
        "ironing_inset",
        Float,
        "0",
        "PrintConfig.hpp:1142; PrintConfig.cpp:4212-4220",
    ),
    definition!(
        "ironing_pattern",
        Enum,
        "rectilinear",
        "PrintConfig.hpp:87-98; PrintConfig.hpp:1139; PrintConfig.cpp:225-255; PrintConfig.cpp:4178-4188",
    ),
    definition!(
        "ironing_spacing",
        Float,
        "0.1",
        "PrintConfig.hpp:1141; PrintConfig.cpp:4202-4210",
    ),
    definition!(
        "ironing_speed",
        Float,
        "20",
        "PrintConfig.hpp:1144; PrintConfig.cpp:4222-4229",
    ),
    definition!(
        "ironing_type",
        Enum,
        "no ironing",
        "PrintConfig.hpp:100-106; PrintConfig.hpp:1138; PrintConfig.cpp:257-263; PrintConfig.cpp:4161-4176",
    ),
];
