use super::{OptionDefinition, OptionValueKind};

pub(super) const PRE_MIDDLE_PROCESS_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!("deretraction_speed", Floats, "0",),
    definition!("detect_narrow_internal_solid_infill", Bool, "true",),
    definition!("detect_overhang_wall", Bool, "true",),
    definition!("detect_thin_wall", Bool, "false",),
    definition!("different_settings_to_system", Strings, "",),
    definition!("disable_m73", Bool, "false",),
    definition!("display_height", Float, "68",),
    definition!("display_mirror_x", Bool, "true",),
    definition!("display_mirror_y", Bool, "false",),
    definition!("display_orientation", Enum, "portrait",),
    definition!("display_pixels_x", Int, "2560",),
    definition!("display_pixels_y", Int, "1440",),
    definition!("display_width", Float, "120",),
    definition!("dont_filter_internal_bridges", Enum, "disabled",),
    definition!("dont_slow_down_outer_wall", Bools, "false",),
    definition!("draft_shield", Enum, "disabled",),
    definition!("during_print_exhaust_fan_speed", Ints, "60",),
    definition!("elefant_foot_compensation", Float, "0",),
    definition!("elefant_foot_compensation_layers", Int, "1",),
    definition!("elefant_foot_layers_density", Percent, "100",),
    definition!("elefant_foot_min_width", Float, "0.2",),
    definition!("emit_machine_limits_to_gcode", Bool, "true",),
    definition!("enable_arc_fitting", Bool, "false",),
    definition!("enable_extra_bridge_layer", Enum, "disabled",),
    definition!("enable_filament_dynamic_map", Bool, "false",),
    definition!("enable_filament_ramming", Bool, "true",),
    definition!("enable_long_retraction_when_cut", Int, "0",),
    definition!("enable_overhang_bridge_fan", Bools, "true",),
    definition!("enable_overhang_speed", Bool, "true",),
    definition!("enable_power_loss_recovery", Enum, "printer_configuration",),
    definition!("enable_pressure_advance", Bools, "false",),
    definition!("enable_prime_tower", Bool, "false",),
    definition!("enable_support", Bool, "false",),
    definition!(
        "enable_tower_interface_cooldown_during_tower",
        Bool,
        "false",
    ),
    definition!("enable_tower_interface_features", Bool, "false",),
    definition!("enable_wrapping_detection", Bool, "false",),
    definition!("enforce_support_layers", Int, "0",),
    definition!("eng_plate_temp", Ints, "45",),
    definition!("eng_plate_temp_initial_layer", Ints, "45",),
    definition!("ensure_vertical_shell_thickness", Enum, "ensure_all",),
    definition!("exclude_object", Bool, "false",),
    definition!("exposure_time", Float, "10",),
    definition!("extra_loading_move", Float, "-2",),
    definition!("extra_perimeters_on_overhangs", Bool, "false",),
    definition!("extra_solid_infills", String, "",),
    definition!("extruder", Int, "0",),
    definition!("extruder_ams_count", Strings, "",),
    definition!("extruder_clearance_height_to_lid", Float, "120",),
    definition!("extruder_clearance_height_to_rod", Float, "40",),
    definition!("extruder_clearance_radius", Float, "40",),
    definition!("extruder_colour", Strings, "",),
    definition!("extruder_offset", Points, "0x0",),
    definition!("extruder_printable_area", PointsGroups, "",),
    definition!("extruder_printable_height", Floats, "0",),
    definition!("extruder_type", Enums, "Direct Drive",),
    definition!("extruder_variant_list", Strings, "Direct Drive Standard",),
    definition!(
        "extrusion_rate_smoothing_external_perimeter_only",
        Bool,
        "false",
    ),
    definition!("faded_layers", Int, "10"),
    definition!("fan_cooling_layer_time", Floats, "60",),
    definition!("fan_kickstart", Float, "0",),
    definition!("fan_max_speed", Floats, "100",),
    definition!("fan_min_speed", Floats, "20",),
    definition!("fan_speedup_overhangs", Bool, "true",),
    definition!("fan_speedup_time", Float, "0",),
    definition!("fast_tilt_time", Float, "5",),
];
