use super::{OptionDefinition, OptionValueKind};

pub(super) const PRE_MIDDLE_FILAMENT_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!(
        "filament_adaptive_volumetric_speed",
        BoolsNullable,
        "false",
        "PrintConfig.hpp:1318; PrintConfig.cpp:2557-2565",
    ),
    definition!(
        "filament_adhesiveness_category",
        Ints,
        "0",
        "PrintConfig.hpp:1320; PrintConfig.cpp:2596-2601",
    ),
    definition!(
        "filament_change_extrusion_role_gcode",
        Strings,
        "",
        "PrintConfig.hpp:1395; PrintConfig.cpp:6534-6541",
    ),
    definition!(
        "filament_change_length",
        Floats,
        "10",
        "PrintConfig.hpp:1329; PrintConfig.cpp:2804-2810",
    ),
    definition!(
        "filament_colour",
        Strings,
        "#F2754E",
        "PrintConfig.hpp:1325; PrintConfig.cpp:2367-2372",
    ),
    definition!(
        "filament_colour_type",
        Strings,
        "1",
        "PrintConfig.cpp:2389-2390",
    ),
    definition!(
        "filament_cooling_before_tower",
        FloatsNullable,
        "10",
        "PrintConfig.hpp:1444; PrintConfig.cpp:2689-2695",
    ),
    definition!(
        "filament_cooling_final_speed",
        Floats,
        "3.4",
        "PrintConfig.hpp:1450; PrintConfig.cpp:2737-2743",
    ),
    definition!(
        "filament_cooling_initial_speed",
        Floats,
        "2.2",
        "PrintConfig.hpp:1442; PrintConfig.cpp:2670-2676",
    ),
    definition!(
        "filament_cooling_moves",
        Ints,
        "4",
        "PrintConfig.hpp:1441; PrintConfig.cpp:2646-2653",
    ),
    definition!(
        "filament_cost",
        Floats,
        "0",
        "PrintConfig.hpp:1330; PrintConfig.cpp:2837-2843",
    ),
    definition!(
        "filament_density",
        Floats,
        "0",
        "PrintConfig.hpp:1321; PrintConfig.cpp:2776-2782",
    ),
    definition!(
        "filament_deretraction_speed",
        FloatsNullable,
        "0",
        "PrintConfig.hpp:512; PrintConfig.cpp:63-83; PrintConfig.cpp:7121-7156; PrintConfig.hpp:1296; PrintConfig.cpp:5330-5336",
    ),
    definition!(
        "filament_diameter",
        Floats,
        "1.75",
        "PrintConfig.hpp:1317; PrintConfig.cpp:2518-2523",
    ),
    definition!(
        "filament_end_gcode",
        Strings,
        " ",
        "PrintConfig.hpp:1300; PrintConfig.cpp:1958-1965",
    ),
    definition!(
        "filament_extruder_variant",
        Strings,
        "Direct Drive Standard",
        "PrintConfig.hpp:1338; PrintConfig.cpp:5292-5297",
    ),
    definition!(
        "filament_flow_ratio",
        FloatsNullable,
        "1",
        "PrintConfig.hpp:1301; PrintConfig.cpp:2227-2237",
    ),
    definition!(
        "filament_flush_temp",
        IntsNullable,
        "0",
        "PrintConfig.hpp:1344; PrintConfig.cpp:2442-2450",
    ),
    definition!(
        "filament_flush_volumetric_speed",
        FloatsNullable,
        "0",
        "PrintConfig.hpp:1343; PrintConfig.cpp:2452-2460",
    ),
    definition!(
        "filament_ids",
        Strings,
        "",
        "PrintConfig.hpp:1324; PrintConfig.cpp:2850-2852",
    ),
    definition!(
        "filament_ironing_flow",
        PercentsNullable,
        "nil",
        "PrintConfig.hpp:1148; PrintConfig.cpp:3372-3383",
    ),
    definition!(
        "filament_ironing_inset",
        FloatsNullable,
        "nil",
        "PrintConfig.hpp:1150; PrintConfig.cpp:3397-3407",
    ),
    definition!(
        "filament_ironing_spacing",
        FloatsNullable,
        "nil",
        "PrintConfig.hpp:1149; PrintConfig.cpp:3385-3395",
    ),
    definition!(
        "filament_ironing_speed",
        FloatsNullable,
        "nil",
        "PrintConfig.hpp:1151; PrintConfig.cpp:3409-3418",
    ),
    definition!(
        "filament_is_support",
        Bools,
        "false",
        "PrintConfig.hpp:1327; PrintConfig.cpp:2812-2816",
    ),
    definition!(
        "filament_loading_speed",
        Floats,
        "28",
        "PrintConfig.hpp:1436; PrintConfig.cpp:2603-2609",
    ),
    definition!(
        "filament_loading_speed_start",
        Floats,
        "3",
        "PrintConfig.hpp:1437; PrintConfig.cpp:2611-2617",
    ),
    definition!(
        "filament_long_retractions_when_cut",
        BoolsNullable,
        "false",
        "PrintConfig.hpp:512; PrintConfig.cpp:63-83; PrintConfig.cpp:7121-7156; PrintConfig.hpp:1372; PrintConfig.cpp:5081-5086",
    ),
    definition!(
        "filament_map",
        Ints,
        "1",
        "PrintConfig.hpp:1336; PrintConfig.cpp:2401-2405",
    ),
    definition!(
        "filament_map_mode",
        Enum,
        "Auto For Flush",
        "PrintConfig.hpp:1335; PrintConfig.cpp:2414-2428",
    ),
    definition!(
        "filament_max_volumetric_speed",
        Floats,
        "2",
        "PrintConfig.hpp:1333; PrintConfig.cpp:2462-2470",
    ),
    definition!(
        "filament_minimal_purge_on_wipe_tower",
        Floats,
        "15",
        "PrintConfig.hpp:1443; PrintConfig.cpp:2678-2687",
    ),
    definition!(
        "filament_multi_colour",
        Strings,
        "",
        "PrintConfig.cpp:2385-2386",
    ),
    definition!(
        "filament_multitool_ramming",
        Bools,
        "false",
        "PrintConfig.hpp:1452; PrintConfig.cpp:2752-2758",
    ),
    definition!(
        "filament_multitool_ramming_flow",
        Floats,
        "10",
        "PrintConfig.hpp:1454; PrintConfig.cpp:2768-2774",
    ),
    definition!(
        "filament_multitool_ramming_volume",
        Floats,
        "10",
        "PrintConfig.hpp:1453; PrintConfig.cpp:2760-2766",
    ),
    definition!(
        "filament_notes",
        Strings,
        "",
        "PrintConfig.hpp:1632; PrintConfig.cpp:2375-2382",
    ),
    definition!(
        "filament_printable",
        Ints,
        "3",
        "PrintConfig.hpp:1328; PrintConfig.cpp:2818-2826",
    ),
];
