use super::{OptionDefinition, OptionValueKind};

pub(super) const PRE_MIDDLE_PROCESS_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!(
        "deretraction_speed",
        Floats,
        "0",
        "PrintConfig.hpp:1296; PrintConfig.cpp:5330-5336",
    ),
    definition!(
        "detect_narrow_internal_solid_infill",
        Bool,
        "true",
        "PrintConfig.hpp:1017; PrintConfig.cpp:7154-7161",
    ),
    definition!(
        "detect_overhang_wall",
        Bool,
        "true",
        "PrintConfig.hpp:1153; PrintConfig.cpp:4879-4885",
    ),
    definition!(
        "detect_thin_wall",
        Bool,
        "false",
        "PrintConfig.hpp:1165; PrintConfig.cpp:6508-6514",
    ),
    definition!(
        "different_settings_to_system",
        Strings,
        "",
        "PrintConfig.cpp:1742-1744",
    ),
    definition!(
        "disable_m73",
        Bool,
        "false",
        "PrintConfig.hpp:1425; PrintConfig.cpp:5351-5355",
    ),
    definition!(
        "display_height",
        Float,
        "68",
        "PrintConfig.hpp:1831; PrintConfig.cpp:7241-7245",
    ),
    definition!(
        "display_mirror_x",
        Bool,
        "true",
        "PrintConfig.hpp:1835; PrintConfig.cpp:7261-7266",
    ),
    definition!(
        "display_mirror_y",
        Bool,
        "false",
        "PrintConfig.hpp:1836; PrintConfig.cpp:7268-7273",
    ),
    definition!(
        "display_orientation",
        Enum,
        "portrait",
        "PrintConfig.hpp:260-263; PrintConfig.hpp:1834; PrintConfig.cpp:400-404; PrintConfig.cpp:7275-7284",
    ),
    definition!(
        "display_pixels_x",
        Int,
        "2560",
        "PrintConfig.hpp:1832; PrintConfig.cpp:7247-7252",
    ),
    definition!(
        "display_pixels_y",
        Int,
        "1440",
        "PrintConfig.hpp:1833; PrintConfig.cpp:7254-7259",
    ),
    definition!(
        "display_width",
        Float,
        "120",
        "PrintConfig.hpp:1830; PrintConfig.cpp:7235-7239",
    ),
    definition!(
        "dont_filter_internal_bridges",
        Enum,
        "disabled",
        "PrintConfig.hpp:231-233; PrintConfig.hpp:988; PrintConfig.cpp:377-382; PrintConfig.cpp:1902-1928",
    ),
    definition!(
        "dont_slow_down_outer_wall",
        Bools,
        "false",
        "PrintConfig.hpp:1520; PrintConfig.cpp:2340-2347",
    ),
    definition!(
        "draft_shield",
        Enum,
        "disabled",
        "PrintConfig.hpp:290-292; PrintConfig.hpp:1512; PrintConfig.cpp:443-447; PrintConfig.cpp:5573-5586",
    ),
    definition!(
        "during_print_exhaust_fan_speed",
        Ints,
        "60",
        "PrintConfig.cpp:1819-1826",
    ),
    definition!(
        "elefant_foot_compensation",
        Float,
        "0",
        "PrintConfig.cpp:717-724",
    ),
    definition!(
        "elefant_foot_compensation_layers",
        Int,
        "1",
        "PrintConfig.cpp:726-735",
    ),
    definition!(
        "elefant_foot_layers_density",
        Percent,
        "100",
        "PrintConfig.cpp:737-747",
    ),
    definition!(
        "elefant_foot_min_width",
        Float,
        "0.2",
        "PrintConfig.hpp:1843; PrintConfig.cpp:7351-7358",
    ),
    definition!(
        "emit_machine_limits_to_gcode",
        Bool,
        "true",
        "PrintConfig.hpp:1247; PrintConfig.cpp:4326-4332",
    ),
    definition!(
        "enable_arc_fitting",
        Bool,
        "false",
        "PrintConfig.hpp:1298; PrintConfig.cpp:3607-3616",
    ),
    definition!(
        "enable_extra_bridge_layer",
        Enum,
        "disabled",
        "PrintConfig.hpp:236-238; PrintConfig.hpp:990; PrintConfig.cpp:384-390; PrintConfig.cpp:1871-1900",
    ),
    definition!(
        "enable_filament_dynamic_map",
        Bool,
        "false",
        "PrintConfig.cpp:2430-2434",
    ),
    definition!(
        "enable_filament_ramming",
        Bool,
        "true",
        "PrintConfig.hpp:1459; PrintConfig.cpp:5838-5842",
    ),
    definition!(
        "enable_long_retraction_when_cut",
        Int,
        "0",
        "PrintConfig.hpp:1370; PrintConfig.cpp:5077-5079",
    ),
    definition!(
        "enable_overhang_bridge_fan",
        Bools,
        "true",
        "PrintConfig.hpp:1502; PrintConfig.cpp:1170-1175",
    ),
    definition!(
        "enable_overhang_speed",
        Bool,
        "true",
        "PrintConfig.hpp:1171; PrintConfig.cpp:1500-1505",
    ),
    definition!(
        "enable_power_loss_recovery",
        Enum,
        "printer_configuration",
        "PrintConfig.hpp:125-129; PrintConfig.hpp:1347; PrintConfig.cpp:185-190; PrintConfig.cpp:3632-3643",
    ),
    definition!(
        "enable_pressure_advance",
        Bools,
        "false",
        "PrintConfig.hpp:1302; PrintConfig.cpp:2252-2255",
    ),
    definition!(
        "enable_prime_tower",
        Bool,
        "false",
        "PrintConfig.hpp:1574; PrintConfig.cpp:6646-6651",
    ),
    definition!(
        "enable_support",
        Bool,
        "false",
        "PrintConfig.hpp:948; PrintConfig.cpp:5903-5908",
    ),
    definition!(
        "enable_tower_interface_cooldown_during_tower",
        Bool,
        "false",
        "PrintConfig.hpp:1587; PrintConfig.cpp:6833-6837",
    ),
    definition!(
        "enable_tower_interface_features",
        Bool,
        "false",
        "PrintConfig.hpp:1586; PrintConfig.cpp:6827-6831",
    ),
    definition!(
        "enable_wrapping_detection",
        Bool,
        "false",
        "PrintConfig.hpp:1348; PrintConfig.cpp:3987-3991",
    ),
    definition!(
        "enforce_support_layers",
        Int,
        "0",
        "PrintConfig.hpp:958; PrintConfig.cpp:6013-6025",
    ),
    definition!(
        "eng_plate_temp",
        Ints,
        "45",
        "PrintConfig.hpp:1493; PrintConfig.cpp:954-962",
    ),
    definition!(
        "eng_plate_temp_initial_layer",
        Ints,
        "45",
        "PrintConfig.hpp:1499; PrintConfig.cpp:1014-1022",
    ),
    definition!(
        "ensure_vertical_shell_thickness",
        Enum,
        "ensure_all",
        "PrintConfig.hpp:223-228; PrintConfig.hpp:1087; PrintConfig.cpp:368-374; PrintConfig.cpp:1967-1984",
    ),
    definition!(
        "exclude_object",
        Bool,
        "false",
        "PrintConfig.hpp:1624; PrintConfig.cpp:3839-3843",
    ),
    definition!(
        "exposure_time",
        Float,
        "10",
        "PrintConfig.hpp:1815; PrintConfig.cpp:7449-7454",
    ),
    definition!(
        "extra_loading_move",
        Float,
        "-2",
        "PrintConfig.hpp:1432; PrintConfig.cpp:4812-4819",
    ),
    definition!(
        "extra_perimeters_on_overhangs",
        Bool,
        "false",
        "PrintConfig.hpp:1200; PrintConfig.cpp:1439-1444",
    ),
    definition!(
        "extra_solid_infills",
        String,
        "",
        "PrintConfig.hpp:1107; PrintConfig.cpp:2898-2903",
    ),
    definition!(
        "extruder_ams_count",
        Strings,
        "",
        "PrintConfig.hpp:1410; PrintConfig.cpp:5246-5250",
    ),
    definition!(
        "extruder_clearance_height_to_lid",
        Float,
        "120",
        "PrintConfig.hpp:1514; PrintConfig.cpp:2137-2144",
    ),
    definition!(
        "extruder_clearance_height_to_rod",
        Float,
        "40",
        "PrintConfig.hpp:1513; PrintConfig.cpp:2127-2134",
    ),
    definition!(
        "extruder_clearance_radius",
        Float,
        "40",
        "PrintConfig.hpp:1515; PrintConfig.cpp:2146-2152",
    ),
    definition!(
        "extruder_colour",
        Strings,
        "",
        "PrintConfig.hpp:1517; PrintConfig.cpp:2209-2215",
    ),
    definition!(
        "extruder_offset",
        Points,
        "0x0",
        "PrintConfig.hpp:1518; PrintConfig.cpp:2217-2225",
    ),
    definition!(
        "extruder_printable_area",
        PointsGroups,
        "",
        "PrintConfig.cpp:690-694",
    ),
    definition!(
        "extruder_printable_height",
        Floats,
        "0",
        "PrintConfig.cpp:766-773",
    ),
    definition!(
        "extruder_type",
        Enums,
        "Direct Drive",
        "PrintConfig.hpp:412-415; PrintConfig.hpp:1408; PrintConfig.cpp:565-569; PrintConfig.cpp:5202-5212",
    ),
    definition!(
        "extruder_variant_list",
        Strings,
        "Direct Drive Standard",
        "PrintConfig.cpp:5239-5244",
    ),
    definition!(
        "extrusion_rate_smoothing_external_perimeter_only",
        Bool,
        "false",
        "PrintConfig.hpp:1364; PrintConfig.cpp:4643-4648",
    ),
    definition!("faded_layers", Int, "10", "PrintConfig.cpp:7425-7431",),
    definition!(
        "fan_cooling_layer_time",
        Floats,
        "60",
        "PrintConfig.hpp:1521; PrintConfig.cpp:2349-2357",
    ),
    definition!(
        "fan_kickstart",
        Float,
        "0",
        "PrintConfig.hpp:1310; PrintConfig.cpp:3729-3738",
    ),
    definition!(
        "fan_max_speed",
        Floats,
        "100",
        "PrintConfig.hpp:1535; PrintConfig.cpp:4591-4599",
    ),
    definition!(
        "fan_min_speed",
        Floats,
        "20",
        "PrintConfig.hpp:1537; PrintConfig.cpp:4651-4658",
    ),
    definition!(
        "fan_speedup_overhangs",
        Bool,
        "true",
        "PrintConfig.hpp:1311; PrintConfig.cpp:3723-3727",
    ),
    definition!(
        "fan_speedup_time",
        Float,
        "0",
        "PrintConfig.hpp:1312; PrintConfig.cpp:3710-3721",
    ),
    definition!(
        "fast_tilt_time",
        Float,
        "5",
        "PrintConfig.hpp:1845; PrintConfig.cpp:7286-7293",
    ),
];
