use super::{OptionDefinition, OptionValueKind};

pub(super) const PRE_MIDDLE_TAIL_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!(
        "filament_ramming_parameters",
        Strings,
        "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6",
    ),
    definition!("filament_retract_before_wipe", PercentsNullable, "100",),
    definition!("filament_retract_lift_above", FloatsNullable, "0",),
    definition!("filament_retract_lift_below", FloatsNullable, "0",),
    definition!(
        "filament_retract_lift_enforce",
        EnumsNullable,
        "All Surfaces",
    ),
    definition!("filament_retract_restart_extra", FloatsNullable, "0",),
    definition!(
        "filament_retract_when_changing_layer",
        BoolsNullable,
        "false",
    ),
    definition!(
        "filament_retraction_distances_when_cut",
        FloatsNullable,
        "18",
    ),
    definition!("filament_retraction_length", FloatsNullable, "0.8",),
    definition!("filament_retraction_minimum_travel", FloatsNullable, "2",),
    definition!("filament_retraction_speed", FloatsNullable, "30",),
    definition!("filament_self_index", Ints, "1",),
    definition!("filament_settings_id", Strings, "",),
    definition!("filament_shrink", Percents, "100",),
    definition!("filament_shrinkage_compensation_z", Percents, "100",),
    definition!("filament_soluble", Bools, "false",),
    definition!("filament_stamping_distance", Floats, "0",),
    definition!("filament_stamping_loading_speed", Floats, "0",),
    definition!("filament_start_gcode", Strings, " ",),
    definition!("filament_toolchange_delay", Floats, "0",),
    definition!("filament_tower_interface_pre_extrusion_dist", Floats, "10",),
    definition!("filament_tower_interface_pre_extrusion_length", Floats, "0",),
    definition!("filament_tower_interface_print_temp", Ints, "-1",),
    definition!("filament_tower_interface_purge_volume", Floats, "20",),
    definition!("filament_tower_ironing_area", Floats, "4",),
    definition!("filament_type", Strings, "PLA",),
    definition!("filament_unloading_speed", Floats, "90",),
    definition!("filament_unloading_speed_start", Floats, "100",),
    definition!("filament_vendor", Strings, "(Undefined)",),
    definition!("filament_wipe", BoolsNullable, "false",),
    definition!("filament_wipe_distance", FloatsNullable, "1",),
    definition!("filament_z_hop", FloatsNullable, "0.4",),
    definition!("filament_z_hop_types", EnumsNullable, "Slope Lift",),
    definition!("file_start_gcode", String, "",),
    definition!(
        "filename_format",
        String,
        "{input_filename_base}_{filament_type[initial_tool]}_{print_time}.gcode",
    ),
];
