use super::{OptionDefinition, OptionValueKind};

pub(super) const PRE_MIDDLE_FILAMENT_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!("filament_adaptive_volumetric_speed", BoolsNullable, "false",),
    definition!("filament_adhesiveness_category", Ints, "0",),
    definition!("filament_change_extrusion_role_gcode", Strings, "",),
    definition!("filament_change_length", Floats, "10",),
    definition!("filament_colour", Strings, "#F2754E",),
    definition!("filament_colour_type", Strings, "1",),
    definition!("filament_cooling_before_tower", FloatsNullable, "10",),
    definition!("filament_cooling_final_speed", Floats, "3.4",),
    definition!("filament_cooling_initial_speed", Floats, "2.2",),
    definition!("filament_cooling_moves", Ints, "4",),
    definition!("filament_cost", Floats, "0",),
    definition!("filament_density", Floats, "0",),
    definition!("filament_deretraction_speed", FloatsNullable, "0",),
    definition!("filament_diameter", Floats, "1.75",),
    definition!("filament_end_gcode", Strings, " ",),
    definition!(
        "filament_extruder_variant",
        Strings,
        "Direct Drive Standard",
    ),
    definition!("filament_flow_ratio", FloatsNullable, "1",),
    definition!("filament_flush_temp", IntsNullable, "0",),
    definition!("filament_flush_volumetric_speed", FloatsNullable, "0",),
    definition!("filament_ids", Strings, "",),
    definition!("filament_ironing_flow", PercentsNullable, "nil",),
    definition!("filament_ironing_inset", FloatsNullable, "nil",),
    definition!("filament_ironing_spacing", FloatsNullable, "nil",),
    definition!("filament_ironing_speed", FloatsNullable, "nil",),
    definition!("filament_is_support", Bools, "false",),
    definition!("filament_loading_speed", Floats, "28",),
    definition!("filament_loading_speed_start", Floats, "3",),
    definition!("filament_long_retractions_when_cut", BoolsNullable, "false",),
    definition!("filament_map", Ints, "1",),
    definition!("filament_map_mode", Enum, "Auto For Flush",),
    definition!("filament_max_volumetric_speed", Floats, "2",),
    definition!("filament_minimal_purge_on_wipe_tower", Floats, "15",),
    definition!("filament_multi_colour", Strings, "",),
    definition!("filament_multitool_ramming", Bools, "false",),
    definition!("filament_multitool_ramming_flow", Floats, "10",),
    definition!("filament_multitool_ramming_volume", Floats, "10",),
    definition!("filament_notes", Strings, "",),
    definition!("filament_printable", Ints, "3",),
];
