use super::{OptionDefinition, OptionValueKind};

pub(super) const TAIL_RAFT_SUFFIX_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!(
        "required_nozzle_HRC",
        Ints,
        "0",
        "PrintConfig.hpp:1334; PrintConfig.cpp:2393-2399",
    ),
    definition!(
        "resolution",
        Float,
        "0.01",
        "PrintConfig.hpp:1549; PrintConfig.cpp:5039-5046",
    ),
    definition!(
        "resonance_avoidance",
        Bool,
        "false",
        "PrintConfig.hpp:1277; PrintConfig.cpp:4516-4523",
    ),
    definition!(
        "retract_before_wipe",
        Percents,
        "100",
        "PrintConfig.hpp:1367; PrintConfig.cpp:5055-5060",
    ),
    definition!(
        "retract_length_toolchange",
        Floats,
        "10",
        "PrintConfig.hpp:1369; PrintConfig.cpp:5111-5120",
    ),
    definition!(
        "retract_lift_above",
        Floats,
        "0",
        "PrintConfig.hpp:1379; PrintConfig.cpp:5133-5139; PrintConfig.cpp:5173-5178",
    ),
    definition!(
        "retract_lift_below",
        Floats,
        "0",
        "PrintConfig.hpp:1380; PrintConfig.cpp:5141-5147; PrintConfig.cpp:5180-5185",
    ),
    definition!(
        "retract_lift_enforce",
        Enums,
        "All Surfaces",
        "PrintConfig.hpp:390-394; PrintConfig.hpp:1381; PrintConfig.cpp:534-540; PrintConfig.cpp:5187-5200",
    ),
    definition!(
        "retract_restart_extra",
        Floats,
        "0",
        "PrintConfig.hpp:1382; PrintConfig.cpp:5306-5312",
    ),
    definition!(
        "retract_restart_extra_toolchange",
        Floats,
        "0",
        "PrintConfig.hpp:1383; PrintConfig.cpp:5314-5320",
    ),
    definition!(
        "retract_when_changing_layer",
        Bools,
        "false",
        "PrintConfig.hpp:1551; PrintConfig.cpp:5062-5066",
    ),
    definition!(
        "retraction_distances_when_cut",
        Floats,
        "18",
        "PrintConfig.hpp:1371; PrintConfig.cpp:5088-5094",
    ),
    definition!(
        "retraction_distances_when_ec",
        FloatsNullable,
        "10",
        "PrintConfig.hpp:1373; PrintConfig.cpp:5102-5109",
    ),
    definition!(
        "retraction_length",
        Floats,
        "0.8",
        "PrintConfig.hpp:1368; PrintConfig.cpp:5068-5075",
    ),
    definition!(
        "retraction_minimum_travel",
        Floats,
        "2",
        "PrintConfig.hpp:1550; PrintConfig.cpp:5048-5053",
    ),
    definition!(
        "retraction_speed",
        Floats,
        "30",
        "PrintConfig.hpp:1384; PrintConfig.cpp:5322-5328",
    ),
    definition!(
        "role_based_wipe_speed",
        Bool,
        "true",
        "PrintConfig.hpp:1183; PrintConfig.cpp:5502-5508",
    ),
    definition!(
        "scan_first_layer",
        Bool,
        "false",
        "PrintConfig.hpp:1346; PrintConfig.cpp:3625-3629",
    ),
    definition!(
        "scarf_angle_threshold",
        Int,
        "155",
        "PrintConfig.hpp:1226; PrintConfig.cpp:5413-5423",
    ),
    definition!(
        "scarf_joint_flow_ratio",
        Float,
        "1",
        "PrintConfig.hpp:1233; PrintConfig.cpp:5451-5458",
    ),
    definition!(
        "scarf_joint_speed",
        FloatOrPercent,
        "100%",
        "PrintConfig.hpp:1232; PrintConfig.cpp:5437-5449",
    ),
    definition!(
        "scarf_overhang_threshold",
        Percent,
        "40",
        "PrintConfig.hpp:1234; PrintConfig.cpp:5425-5435",
    ),
    definition!(
        "seam_gap",
        FloatOrPercent,
        "10%",
        "PrintConfig.hpp:1182; PrintConfig.cpp:5382-5390",
    ),
    definition!(
        "seam_position",
        Enum,
        "aligned",
        "PrintConfig.hpp:211-213; PrintConfig.hpp:944; PrintConfig.cpp:350-357; PrintConfig.cpp:5357-5373",
    ),
    definition!(
        "seam_slope_conditional",
        Bool,
        "false",
        "PrintConfig.hpp:1225; PrintConfig.cpp:5406-5411",
    ),
    definition!(
        "seam_slope_entire_loop",
        Bool,
        "false",
        "PrintConfig.hpp:1228; PrintConfig.cpp:5471-5476",
    ),
    definition!(
        "seam_slope_inner_walls",
        Bool,
        "false",
        "PrintConfig.hpp:1231; PrintConfig.cpp:5495-5500",
    ),
    definition!(
        "seam_slope_min_length",
        Float,
        "20",
        "PrintConfig.hpp:1229; PrintConfig.cpp:5478-5485",
    ),
    definition!(
        "seam_slope_start_height",
        FloatOrPercent,
        "0",
        "PrintConfig.hpp:1227; PrintConfig.cpp:5460-5469",
    ),
    definition!(
        "seam_slope_steps",
        Int,
        "10",
        "PrintConfig.hpp:1230; PrintConfig.cpp:5487-5493",
    ),
    definition!(
        "seam_slope_type",
        Enum,
        "none",
        "PrintConfig.hpp:216-220; PrintConfig.hpp:1224; PrintConfig.cpp:360-365; PrintConfig.cpp:5392-5404",
    ),
    definition!(
        "set_other_flow_ratios",
        Bool,
        "false",
        "PrintConfig.hpp:978; PrintConfig.cpp:1307-1312",
    ),
    definition!(
        "silent_mode",
        Bool,
        "false",
        "PrintConfig.hpp:1398; PrintConfig.cpp:4320-4324",
    ),
    definition!(
        "single_extruder_multi_material",
        Bool,
        "true",
        "PrintConfig.hpp:1388; PrintConfig.cpp:5807-5811",
    ),
    definition!(
        "single_extruder_multi_material_priming",
        Bool,
        "false",
        "PrintConfig.hpp:1390; PrintConfig.cpp:5863-5867",
    ),
    definition!(
        "single_loop_draft_shield",
        Bool,
        "false",
        "PrintConfig.hpp:1557; PrintConfig.cpp:5567-5571",
    ),
    definition!(
        "skeleton_infill_density",
        Percent,
        "25",
        "PrintConfig.hpp:1126; PrintConfig.cpp:3898-3909",
    ),
    definition!(
        "skeleton_infill_line_width",
        FloatOrPercent,
        "100%",
        "PrintConfig.hpp:1131; PrintConfig.cpp:3954-3962",
    ),
    definition!(
        "skin_infill_density",
        Percent,
        "25",
        "PrintConfig.hpp:1127; PrintConfig.cpp:3911-3922",
    ),
    definition!(
        "skin_infill_depth",
        Float,
        "2",
        "PrintConfig.hpp:1129; PrintConfig.cpp:3924-3932",
    ),
    definition!(
        "skin_infill_line_width",
        FloatOrPercent,
        "100%",
        "PrintConfig.hpp:1130; PrintConfig.cpp:3944-3952",
    ),
    definition!(
        "skirt_distance",
        Float,
        "2",
        "PrintConfig.hpp:1552; PrintConfig.cpp:5540-5547",
    ),
    definition!(
        "skirt_height",
        Int,
        "1",
        "PrintConfig.hpp:1553; PrintConfig.cpp:5559-5565",
    ),
    definition!(
        "skirt_loops",
        Int,
        "1",
        "PrintConfig.hpp:1554; PrintConfig.cpp:5600-5607",
    ),
    definition!(
        "skirt_speed",
        Float,
        "50",
        "PrintConfig.hpp:1556; PrintConfig.cpp:5609-5616",
    ),
    definition!(
        "skirt_start_angle",
        Float,
        "-135",
        "PrintConfig.hpp:927; PrintConfig.cpp:5549-5557",
    ),
    definition!(
        "skirt_type",
        Enum,
        "combined",
        "PrintConfig.hpp:286-288; PrintConfig.hpp:1555; PrintConfig.cpp:437-441; PrintConfig.cpp:5588-5598",
    ),
    definition!(
        "sla_material_settings_id",
        String,
        "",
        "PrintConfig.cpp:7519-7523",
    ),
    definition!(
        "sla_print_settings_id",
        String,
        "",
        "PrintConfig.cpp:7531-7535",
    ),
    definition!(
        "slice_closing_radius",
        Float,
        "0.049",
        "PrintConfig.hpp:946; PrintConfig.cpp:5869-5877",
    ),
    definition!(
        "slicing_mode",
        Enum,
        "regular",
        "PrintConfig.hpp:162-170; PrintConfig.hpp:947; PrintConfig.cpp:305-310; PrintConfig.cpp:5879-5891",
    ),
    definition!(
        "slow_down_for_layer_cooling",
        Bools,
        "true",
        "PrintConfig.cpp:1772-1777",
    ),
    definition!(
        "slow_down_layer_time",
        Floats,
        "5",
        "PrintConfig.hpp:1559; PrintConfig.cpp:5629-5637",
    ),
    definition!(
        "slow_down_layers",
        Int,
        "0",
        "PrintConfig.hpp:1627; PrintConfig.cpp:3306-3314",
    ),
    definition!(
        "slow_down_min_speed",
        Floats,
        "10",
        "PrintConfig.hpp:1542; PrintConfig.cpp:4706-4713",
    ),
    definition!(
        "slow_tilt_time",
        Float,
        "8",
        "PrintConfig.hpp:1846; PrintConfig.cpp:7295-7302",
    ),
    definition!(
        "slowdown_for_curled_perimeters",
        Bool,
        "true",
        "PrintConfig.hpp:1201; PrintConfig.cpp:1507-1522",
    ),
];
