use super::{OptionDefinition, OptionValueKind};

pub(super) const TAIL_SUPPORT_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!(
        "support_air_filtration",
        Bool,
        "true",
        "PrintConfig.hpp:1405; PrintConfig.cpp:3779-3783",
    ),
    definition!(
        "support_angle",
        Float,
        "0",
        "PrintConfig.hpp:952; PrintConfig.cpp:5949-5957",
    ),
    definition!(
        "support_base_diameter",
        Float,
        "4",
        "PrintConfig.hpp:1708; PrintConfig.cpp:7629-7637",
    ),
    definition!(
        "support_base_height",
        Float,
        "1",
        "PrintConfig.hpp:1711; PrintConfig.cpp:7639-7646",
    ),
    definition!(
        "support_base_pattern",
        Enum,
        "default",
        "PrintConfig.hpp:172-177; PrintConfig.hpp:969; PrintConfig.cpp:312-320; PrintConfig.cpp:6133-6156",
    ),
    definition!(
        "support_base_pattern_spacing",
        Float,
        "2.5",
        "PrintConfig.hpp:972; PrintConfig.cpp:6178-6185",
    ),
    definition!(
        "support_base_safety_distance",
        Float,
        "1",
        "PrintConfig.hpp:1714; PrintConfig.cpp:7648-7656",
    ),
    definition!(
        "support_bottom_interface_spacing",
        Float,
        "0.5",
        "PrintConfig.hpp:1019; PrintConfig.cpp:6114-6122",
    ),
    definition!(
        "support_bottom_z_distance",
        Float,
        "0.2",
        "PrintConfig.hpp:957; PrintConfig.cpp:6002-6011",
    ),
    definition!(
        "support_buildplate_only",
        Bool,
        "false",
        "PrintConfig.hpp:1699; PrintConfig.cpp:7613-7618",
    ),
    definition!(
        "support_chamber_temp_control",
        Bool,
        "true",
        "PrintConfig.hpp:1407; PrintConfig.cpp:3771-3777",
    ),
    definition!(
        "support_critical_angle",
        Float,
        "45",
        "PrintConfig.hpp:1717; PrintConfig.cpp:7658-7666",
    ),
    definition!(
        "support_critical_regions_only",
        Bool,
        "false",
        "PrintConfig.hpp:954; PrintConfig.cpp:5967-5972",
    ),
    definition!(
        "support_expansion",
        Float,
        "0",
        "PrintConfig.hpp:973; PrintConfig.cpp:6187-6193",
    ),
    definition!(
        "support_filament",
        Int,
        "0",
        "PrintConfig.hpp:959; PrintConfig.cpp:6027-6034",
    ),
    definition!(
        "support_flow_ratio",
        Float,
        "1",
        "PrintConfig.hpp:980; PrintConfig.cpp:1384-1393",
    ),
    definition!(
        "support_head_front_diameter",
        Float,
        "0.4",
        "PrintConfig.hpp:1677; PrintConfig.cpp:7544-7551",
    ),
    definition!(
        "support_head_penetration",
        Float,
        "0.2",
        "PrintConfig.hpp:1680; PrintConfig.cpp:7553-7560",
    ),
    definition!(
        "support_head_width",
        Float,
        "1",
        "PrintConfig.hpp:1683; PrintConfig.cpp:7562-7570",
    ),
    definition!(
        "support_interface_bottom_layers",
        Int,
        "0",
        "PrintConfig.hpp:965; PrintConfig.cpp:6090-6102",
    ),
    definition!(
        "support_interface_filament",
        Int,
        "0",
        "PrintConfig.hpp:963; PrintConfig.cpp:6062-6070",
    ),
    definition!(
        "support_interface_flow_ratio",
        Float,
        "1",
        "PrintConfig.hpp:981; PrintConfig.cpp:1394-1403",
    ),
    definition!(
        "support_interface_loop_pattern",
        Bool,
        "false",
        "PrintConfig.hpp:962; PrintConfig.cpp:6055-6060",
    ),
    definition!(
        "support_interface_not_for_body",
        Bool,
        "true",
        "PrintConfig.hpp:961; PrintConfig.cpp:6036-6041",
    ),
    definition!(
        "support_interface_pattern",
        Enum,
        "auto",
        "PrintConfig.hpp:190-192; PrintConfig.hpp:970; PrintConfig.cpp:333-340; PrintConfig.cpp:6158-6176",
    ),
    definition!(
        "support_interface_spacing",
        Float,
        "0.5",
        "PrintConfig.hpp:966-967; PrintConfig.cpp:6104-6112",
    ),
    definition!(
        "support_interface_speed",
        Float,
        "80",
        "PrintConfig.hpp:968; PrintConfig.cpp:6124-6131",
    ),
    definition!(
        "support_interface_top_layers",
        Int,
        "3",
        "PrintConfig.hpp:964; PrintConfig.cpp:6072-6088",
    ),
    definition!(
        "support_ironing",
        Bool,
        "false",
        "PrintConfig.hpp:997; PrintConfig.cpp:6406-6412",
    ),
    definition!(
        "support_ironing_flow",
        Percent,
        "10",
        "PrintConfig.hpp:999; PrintConfig.cpp:6426-6436",
    ),
    definition!(
        "support_ironing_pattern",
        Enum,
        "rectilinear",
        "PrintConfig.hpp:87-98; PrintConfig.hpp:998; PrintConfig.cpp:225-255; PrintConfig.cpp:6414-6424",
    ),
    definition!(
        "support_ironing_spacing",
        Float,
        "0.1",
        "PrintConfig.hpp:1000; PrintConfig.cpp:6438-6446",
    ),
    definition!(
        "support_line_width",
        FloatOrPercent,
        "0",
        "PrintConfig.hpp:960; PrintConfig.cpp:6043-6053",
    ),
    definition!(
        "support_material_interface_fan_speed",
        Ints,
        "-1",
        "PrintConfig.hpp:1628; PrintConfig.cpp:3337-3347",
    ),
    definition!(
        "support_max_bridge_length",
        Float,
        "15",
        "PrintConfig.hpp:1720; PrintConfig.cpp:7668-7675",
    ),
    definition!(
        "support_max_bridges_on_pillar",
        Int,
        "3",
        "PrintConfig.hpp:1693; PrintConfig.cpp:7592-7600",
    ),
    definition!(
        "support_max_pillar_link_distance",
        Float,
        "10",
        "PrintConfig.hpp:1723; PrintConfig.cpp:7677-7684",
    ),
    definition!(
        "support_multi_bed_types",
        Bool,
        "false",
        "PrintConfig.hpp:1461; PrintConfig.cpp:3825-3829",
    ),
    definition!(
        "support_object_elevation",
        Float,
        "5",
        "PrintConfig.hpp:1727; PrintConfig.cpp:7686-7694",
    ),
    definition!(
        "support_object_first_layer_gap",
        Float,
        "0.2",
        "PrintConfig.cpp:5938-5947",
    ),
    definition!(
        "support_object_skip_flush",
        Bool,
        "false",
        "PrintConfig.hpp:1339; PrintConfig.cpp:2500-2501",
    ),
    definition!(
        "support_object_xy_distance",
        Float,
        "0.35",
        "PrintConfig.cpp:5927-5936",
    ),
    definition!(
        "support_on_build_plate_only",
        Bool,
        "false",
        "PrintConfig.hpp:953; PrintConfig.cpp:5959-5964",
    ),
    definition!(
        "support_pillar_connection_mode",
        Enum,
        "dynamic",
        "PrintConfig.hpp:265-269; PrintConfig.hpp:1696; PrintConfig.cpp:406-411; PrintConfig.cpp:7600-7611",
    ),
    definition!(
        "support_pillar_diameter",
        Float,
        "1",
        "PrintConfig.hpp:1686; PrintConfig.cpp:7572-7580",
    ),
    definition!(
        "support_pillar_widening_factor",
        Float,
        "0",
        "PrintConfig.hpp:1705; PrintConfig.cpp:7620-7627",
    ),
    definition!(
        "support_points_density_relative",
        Int,
        "100",
        "PrintConfig.hpp:1730; PrintConfig.cpp:7696-7702",
    ),
    definition!(
        "support_points_minimal_distance",
        Float,
        "1",
        "PrintConfig.hpp:1731; PrintConfig.cpp:7704-7710",
    ),
    definition!(
        "support_remove_small_overhang",
        Bool,
        "true",
        "PrintConfig.hpp:955; PrintConfig.cpp:5974-5979",
    ),
    definition!(
        "support_small_pillar_diameter_percent",
        Percent,
        "50",
        "PrintConfig.hpp:1690; PrintConfig.cpp:7582-7590",
    ),
    definition!(
        "support_speed",
        Float,
        "80",
        "PrintConfig.hpp:974; PrintConfig.cpp:6195-6202",
    ),
    definition!(
        "support_style",
        Enum,
        "default",
        "PrintConfig.hpp:179-181; PrintConfig.hpp:975; PrintConfig.cpp:322-331; PrintConfig.cpp:6204-6230",
    ),
    definition!(
        "support_threshold_angle",
        Int,
        "30",
        "PrintConfig.hpp:993; PrintConfig.cpp:6240-6251",
    ),
    definition!(
        "support_threshold_overlap",
        FloatOrPercent,
        "50%",
        "PrintConfig.hpp:994; PrintConfig.cpp:6253-6262",
    ),
    definition!(
        "support_top_z_distance",
        Float,
        "0.2",
        "PrintConfig.hpp:956; PrintConfig.cpp:5981-6000",
    ),
    definition!(
        "support_type",
        Enum,
        "normal(auto)",
        "PrintConfig.hpp:195-209; PrintConfig.hpp:950; PrintConfig.cpp:342-348; PrintConfig.cpp:5910-5925",
    ),
    definition!(
        "supports_enable",
        Bool,
        "true",
        "PrintConfig.hpp:1674; PrintConfig.cpp:7537-7542",
    ),
];
