use super::{OptionDefinition, OptionValueKind};

pub(super) const TAIL_TERMINAL_SUFFIX_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!(
        "symmetric_infill_y_axis",
        Bool,
        "false",
        "PrintConfig.hpp:1098; PrintConfig.cpp:3964-3970",
    ),
    definition!(
        "temperature_vitrification",
        Ints,
        "100",
        "PrintConfig.hpp:1332; PrintConfig.cpp:2828-2835",
    ),
    definition!(
        "template_custom_gcode",
        String,
        "",
        "PrintConfig.hpp:1400; PrintConfig.cpp:4343-4350",
    ),
    definition!(
        "textured_cool_plate_temp",
        Ints,
        "40",
        "PrintConfig.hpp:1491; PrintConfig.cpp:944-952",
    ),
    definition!(
        "textured_cool_plate_temp_initial_layer",
        Ints,
        "40",
        "PrintConfig.hpp:1498; PrintConfig.cpp:1004-1012",
    ),
    definition!(
        "textured_plate_temp",
        Ints,
        "45",
        "PrintConfig.hpp:1495; PrintConfig.cpp:974-982",
    ),
    definition!(
        "textured_plate_temp_initial_layer",
        Ints,
        "45",
        "PrintConfig.hpp:1501; PrintConfig.cpp:1033-1041",
    ),
    definition!(
        "thick_bridges",
        Bool,
        "false",
        "PrintConfig.hpp:986; PrintConfig.cpp:1855-1861",
    ),
    definition!(
        "thick_internal_bridges",
        Bool,
        "true",
        "PrintConfig.hpp:987; PrintConfig.cpp:1863-1869",
    ),
    definition!(
        "thumbnails",
        String,
        "48x48/PNG,300x300/PNG",
        "PrintConfig.hpp:1616; PrintConfig.cpp:6956-6961",
    ),
    definition!(
        "thumbnails_format",
        Enum,
        "PNG",
        "PrintConfig.hpp:397-399; PrintConfig.cpp:542-549; PrintConfig.cpp:6963-6978",
    ),
    definition!(
        "time_cost",
        Float,
        "0",
        "PrintConfig.hpp:1357; PrintConfig.cpp:3763-3769",
    ),
    definition!(
        "time_lapse_gcode",
        String,
        "",
        "PrintConfig.hpp:1359; PrintConfig.cpp:4304-4310",
    ),
    definition!(
        "timelapse_type",
        Enum,
        "0",
        "PrintConfig.hpp:281-284; PrintConfig.hpp:1615; PrintConfig.cpp:431-435; PrintConfig.cpp:5728-5743",
    ),
    definition!(
        "tool_change_on_wipe_tower",
        Bool,
        "false",
        "PrintConfig.hpp:1460; PrintConfig.cpp:5844-5852",
    ),
    definition!(
        "top_bottom_infill_wall_overlap",
        Percent,
        "25",
        "PrintConfig.hpp:1124; PrintConfig.cpp:4041-4052",
    ),
    definition!(
        "top_shell_layers",
        Int,
        "4",
        "PrintConfig.hpp:1167; PrintConfig.cpp:6564-6573",
    ),
    definition!(
        "top_shell_thickness",
        Float,
        "0.6",
        "PrintConfig.hpp:1168; PrintConfig.cpp:6575-6584",
    ),
    definition!(
        "top_solid_infill_flow_ratio",
        Float,
        "1",
        "PrintConfig.hpp:1193; PrintConfig.cpp:1286-1295",
    ),
    definition!(
        "top_surface_acceleration",
        Float,
        "500",
        "PrintConfig.hpp:1045; PrintConfig.cpp:3086-3093",
    ),
    definition!(
        "top_surface_density",
        Percent,
        "100",
        "PrintConfig.hpp:1088; PrintConfig.cpp:6586-6596",
    ),
    definition!(
        "top_surface_jerk",
        Float,
        "9",
        "PrintConfig.hpp:1056; PrintConfig.cpp:3206-3213",
    ),
    definition!(
        "top_surface_line_width",
        FloatOrPercent,
        "0",
        "PrintConfig.hpp:1166; PrintConfig.cpp:6543-6553",
    ),
    definition!(
        "top_surface_pattern",
        Enum,
        "monotonicline",
        "PrintConfig.hpp:87-98; PrintConfig.hpp:1090; PrintConfig.cpp:225-255; PrintConfig.cpp:1986-2007",
    ),
    definition!(
        "top_surface_speed",
        Float,
        "100",
        "PrintConfig.hpp:1169; PrintConfig.cpp:6555-6562",
    ),
    definition!(
        "travel_acceleration",
        Float,
        "10000",
        "PrintConfig.hpp:1048; PrintConfig.cpp:3077-3084",
    ),
    definition!(
        "travel_jerk",
        Float,
        "12",
        "PrintConfig.hpp:1058; PrintConfig.cpp:3233-3240",
    ),
    definition!(
        "travel_slope",
        Floats,
        "3",
        "PrintConfig.hpp:1378; PrintConfig.cpp:5164-5171",
    ),
    definition!(
        "travel_speed",
        Float,
        "120",
        "PrintConfig.hpp:1396; PrintConfig.cpp:6610-6616",
    ),
    definition!(
        "travel_speed_z",
        Float,
        "0",
        "PrintConfig.hpp:1397; PrintConfig.cpp:6618-6626",
    ),
    definition!(
        "tree_support_angle_slow",
        Float,
        "25",
        "PrintConfig.hpp:1013; PrintConfig.cpp:6286-6296",
    ),
    definition!(
        "tree_support_auto_brim",
        Bool,
        "true",
        "PrintConfig.hpp:1015; PrintConfig.cpp:6332-6336",
    ),
    definition!(
        "tree_support_branch_angle",
        Float,
        "40",
        "PrintConfig.hpp:1011; PrintConfig.cpp:6264-6273",
    ),
    definition!(
        "tree_support_branch_angle_organic",
        Float,
        "40",
        "PrintConfig.hpp:1037; PrintConfig.cpp:6275-6284",
    ),
    definition!(
        "tree_support_branch_diameter",
        Float,
        "5",
        "PrintConfig.hpp:1010; PrintConfig.cpp:6356-6364",
    ),
    definition!(
        "tree_support_branch_diameter_angle",
        Float,
        "5",
        "PrintConfig.hpp:1012; PrintConfig.cpp:6366-6378",
    ),
    definition!(
        "tree_support_branch_diameter_organic",
        Float,
        "2",
        "PrintConfig.hpp:1036; PrintConfig.cpp:6380-6388",
    ),
    definition!(
        "tree_support_branch_distance",
        Float,
        "5",
        "PrintConfig.hpp:1008; PrintConfig.cpp:6298-6306",
    ),
    definition!(
        "tree_support_branch_distance_organic",
        Float,
        "1",
        "PrintConfig.hpp:1034; PrintConfig.cpp:6308-6316",
    ),
    definition!(
        "tree_support_brim_width",
        Float,
        "3",
        "PrintConfig.hpp:1016; PrintConfig.cpp:6338-6343",
    ),
    definition!(
        "tree_support_tip_diameter",
        Float,
        "0.8",
        "PrintConfig.hpp:1009; PrintConfig.cpp:6345-6354",
    ),
    definition!(
        "tree_support_top_rate",
        Percent,
        "30",
        "PrintConfig.hpp:1035; PrintConfig.cpp:6318-6330",
    ),
    definition!(
        "tree_support_wall_count",
        Int,
        "0",
        "PrintConfig.hpp:1014; PrintConfig.cpp:6390-6397",
    ),
    definition!(
        "tree_support_with_infill",
        Bool,
        "false",
        "PrintConfig.cpp:6399-6404",
    ),
    definition!(
        "upward_compatible_machine",
        Strings,
        "",
        "PrintConfig.cpp:1702-1706",
    ),
    definition!(
        "use_firmware_retraction",
        Bool,
        "false",
        "PrintConfig.hpp:1417; PrintConfig.cpp:5338-5343",
    ),
    definition!(
        "use_relative_e_distances",
        Bool,
        "true",
        "PrintConfig.hpp:1418; PrintConfig.cpp:6980-6987",
    ),
    definition!(
        "volumetric_speed_coefficients",
        Strings,
        "",
        "PrintConfig.hpp:1319; PrintConfig.cpp:2567-2569",
    ),
    definition!(
        "wall_direction",
        Enum,
        "ccw",
        "PrintConfig.hpp:140-144; PrintConfig.hpp:1212; PrintConfig.cpp:286-290; PrintConfig.cpp:2100-2110",
    ),
    definition!(
        "wall_distribution_count",
        Int,
        "1",
        "PrintConfig.hpp:1024; PrintConfig.cpp:7042-7049",
    ),
    definition!(
        "wall_filament",
        Int,
        "1",
        "PrintConfig.hpp:1154; PrintConfig.cpp:4887-4894",
    ),
    definition!(
        "wall_generator",
        Enum,
        "arachne",
        "PrintConfig.hpp:294-300; PrintConfig.hpp:1020; PrintConfig.cpp:520-524; PrintConfig.cpp:6989-7001",
    ),
    definition!(
        "wall_loops",
        Int,
        "2",
        "PrintConfig.hpp:1158; PrintConfig.cpp:4918-4924",
    ),
    definition!(
        "wall_maximum_deviation",
        Float,
        "0.025",
        "PrintConfig.hpp:1031; PrintConfig.cpp:7087-7097",
    ),
    definition!(
        "wall_maximum_resolution",
        Float,
        "0.5",
        "PrintConfig.hpp:1030; PrintConfig.cpp:7076-7085",
    ),
    definition!(
        "wall_sequence",
        Enum,
        "inner wall/outer wall",
        "PrintConfig.hpp:132-137; PrintConfig.hpp:1209; PrintConfig.cpp:277-283; PrintConfig.cpp:2070-2091",
    ),
    definition!(
        "wall_transition_angle",
        Float,
        "10",
        "PrintConfig.hpp:1023; PrintConfig.cpp:7029-7040",
    ),
    definition!(
        "wall_transition_filter_deviation",
        Percent,
        "25",
        "PrintConfig.hpp:1022; PrintConfig.cpp:7014-7027",
    ),
    definition!(
        "wall_transition_length",
        Percent,
        "100",
        "PrintConfig.hpp:1021; PrintConfig.cpp:7003-7012",
    ),
    definition!(
        "wipe",
        Bools,
        "false",
        "PrintConfig.hpp:1569; PrintConfig.cpp:6628-6633",
    ),
    definition!(
        "wipe_before_external_loop",
        Bool,
        "false",
        "PrintConfig.hpp:1186; PrintConfig.cpp:5517-5526",
    ),
    definition!(
        "wipe_distance",
        Floats,
        "1",
        "PrintConfig.hpp:1573; PrintConfig.cpp:6635-6644",
    ),
    definition!(
        "wipe_on_loops",
        Bool,
        "false",
        "PrintConfig.hpp:1185; PrintConfig.cpp:5510-5515",
    ),
    definition!(
        "wipe_speed",
        FloatOrPercent,
        "80%",
        "PrintConfig.hpp:1184; PrintConfig.cpp:5528-5538",
    ),
];
