use super::{OptionDefinition, OptionValueKind};

pub(super) const TAIL_TERMINAL_WIPE_OPTION_DEFINITIONS: &[OptionDefinition] = &[
    definition!(
        "wipe_tower_bridging",
        Float,
        "10",
        "PrintConfig.hpp:1588; PrintConfig.cpp:6872-6877",
    ),
    definition!(
        "wipe_tower_cone_angle",
        Float,
        "30",
        "PrintConfig.hpp:1594; PrintConfig.cpp:6736-6744",
    ),
    definition!(
        "wipe_tower_extra_flow",
        Percent,
        "100",
        "PrintConfig.hpp:1589; PrintConfig.cpp:6888-6896",
    ),
    definition!(
        "wipe_tower_extra_rib_length",
        Float,
        "0",
        "PrintConfig.hpp:1598; PrintConfig.cpp:6775-6782",
    ),
    definition!(
        "wipe_tower_extra_spacing",
        Percent,
        "100",
        "PrintConfig.hpp:1595; PrintConfig.cpp:6879-6886",
    ),
    definition!(
        "wipe_tower_filament",
        Int,
        "0",
        "PrintConfig.hpp:1601; PrintConfig.cpp:6800-6808",
    ),
    definition!(
        "wipe_tower_fillet_wall",
        Bool,
        "true",
        "PrintConfig.hpp:1600; PrintConfig.cpp:6793-6797",
    ),
    definition!(
        "wipe_tower_max_purge_speed",
        Float,
        "90",
        "PrintConfig.hpp:1596; PrintConfig.cpp:6746-6757",
    ),
    definition!(
        "wipe_tower_no_sparse_layers",
        Bool,
        "false",
        "PrintConfig.hpp:1391; PrintConfig.cpp:5855-5861",
    ),
    definition!(
        "wipe_tower_rib_width",
        Float,
        "8",
        "PrintConfig.hpp:1599; PrintConfig.cpp:6784-6791",
    ),
    definition!(
        "wipe_tower_rotation_angle",
        Float,
        "0",
        "PrintConfig.hpp:1581; PrintConfig.cpp:6718-6723",
    ),
    definition!(
        "wipe_tower_type",
        Enum,
        "type2",
        "PrintConfig.hpp:74-77; PrintConfig.hpp:1457; PrintConfig.cpp:212-216; PrintConfig.cpp:5821-5830",
    ),
    definition!(
        "wipe_tower_wall_type",
        Enum,
        "rib",
        "PrintConfig.hpp:405-408; PrintConfig.hpp:1597; PrintConfig.cpp:558-563; PrintConfig.cpp:6759-6773",
    ),
    definition!(
        "wipe_tower_x",
        Floats,
        "15",
        "PrintConfig.hpp:1577; PrintConfig.cpp:6694-6700",
    ),
    definition!(
        "wipe_tower_y",
        Floats,
        "220",
        "PrintConfig.hpp:1578; PrintConfig.cpp:6702-6708",
    ),
    definition!(
        "wiping_volumes_extruders",
        Floats,
        "70,70,70,70,70,70,70,70,70,70",
        "PrintConfig.hpp:1602; PrintConfig.cpp:6810-6815",
    ),
    definition!(
        "wrapping_detection_gcode",
        String,
        "",
        "PrintConfig.hpp:1360; PrintConfig.cpp:4312-4318",
    ),
    definition!(
        "wrapping_detection_layers",
        Int,
        "20",
        "PrintConfig.hpp:1349; PrintConfig.cpp:3993-3998",
    ),
    definition!(
        "wrapping_exclude_area",
        Points,
        "0x0",
        "PrintConfig.hpp:1350; PrintConfig.cpp:4000-4005",
    ),
    definition!(
        "xy_contour_compensation",
        Float,
        "0",
        "PrintConfig.hpp:1002; PrintConfig.cpp:6917-6925",
    ),
    definition!(
        "xy_hole_compensation",
        Float,
        "0",
        "PrintConfig.hpp:1001; PrintConfig.cpp:6907-6915",
    ),
];
