pub(in crate::options::tests::filament_remaining) const NULLABLE_KEYS: [&str; 20] = [
    "filament_deretraction_speed",
    "filament_ironing_flow",
    "filament_ironing_inset",
    "filament_ironing_spacing",
    "filament_ironing_speed",
    "filament_long_retractions_when_cut",
    "filament_retract_before_wipe",
    "filament_retract_lift_above",
    "filament_retract_lift_below",
    "filament_retract_lift_enforce",
    "filament_retract_restart_extra",
    "filament_retract_when_changing_layer",
    "filament_retraction_distances_when_cut",
    "filament_retraction_length",
    "filament_retraction_minimum_travel",
    "filament_retraction_speed",
    "filament_wipe",
    "filament_wipe_distance",
    "filament_z_hop",
    "filament_z_hop_types",
];

pub(in crate::options::tests::filament_remaining) const FIXTURE_NIL_KEYS: [&str; 15] = [
    "filament_deretraction_speed",
    "filament_ironing_flow",
    "filament_ironing_inset",
    "filament_ironing_spacing",
    "filament_ironing_speed",
    "filament_long_retractions_when_cut",
    "filament_retract_before_wipe",
    "filament_retract_lift_above",
    "filament_retract_lift_below",
    "filament_retract_lift_enforce",
    "filament_retract_restart_extra",
    "filament_retract_when_changing_layer",
    "filament_retraction_minimum_travel",
    "filament_retraction_speed",
    "filament_z_hop",
];

pub(in crate::options::tests::filament_remaining) const FIXTURE_CONCRETE_NULLABLE_KEYS: [&str; 5] = [
    "filament_retraction_distances_when_cut",
    "filament_retraction_length",
    "filament_wipe",
    "filament_wipe_distance",
    "filament_z_hop_types",
];

pub(in crate::options::tests::filament_remaining) const VARIANT_KEYS: [&str; 27] = [
    "activate_air_filtration",
    "activate_air_filtration_during_print",
    "activate_air_filtration_on_completion",
    "complete_print_exhaust_fan_speed",
    "during_print_exhaust_fan_speed",
    "filament_deretraction_speed",
    "filament_ironing_flow",
    "filament_ironing_inset",
    "filament_ironing_spacing",
    "filament_ironing_speed",
    "filament_long_retractions_when_cut",
    "filament_retract_before_wipe",
    "filament_retract_lift_above",
    "filament_retract_lift_below",
    "filament_retract_lift_enforce",
    "filament_retract_restart_extra",
    "filament_retract_when_changing_layer",
    "filament_retraction_distances_when_cut",
    "filament_retraction_length",
    "filament_retraction_minimum_travel",
    "filament_retraction_speed",
    "filament_wipe",
    "filament_wipe_distance",
    "filament_z_hop",
    "filament_z_hop_types",
    "nozzle_temperature",
    "nozzle_temperature_initial_layer",
];

pub(in crate::options::tests::filament_remaining) const FIXTURE_OVERRIDE_KEYS: [&str; 26] = [
    "additional_cooling_fan_speed",
    "close_additional_fan_first_x_layers",
    "complete_print_exhaust_fan_speed",
    "during_print_exhaust_fan_speed",
    "eng_plate_temp",
    "eng_plate_temp_initial_layer",
    "fan_cooling_layer_time",
    "fan_min_speed",
    "filament_retraction_distances_when_cut",
    "filament_retraction_length",
    "filament_wipe",
    "filament_wipe_distance",
    "filament_z_hop_types",
    "first_x_layer_fan_speed",
    "hot_plate_temp",
    "hot_plate_temp_initial_layer",
    "nozzle_temperature",
    "nozzle_temperature_initial_layer",
    "overhang_fan_threshold",
    "reduce_fan_stop_start_freq",
    "slow_down_layer_time",
    "slow_down_min_speed",
    "supertack_plate_temp",
    "supertack_plate_temp_initial_layer",
    "textured_plate_temp",
    "textured_plate_temp_initial_layer",
];

pub(in crate::options::tests::filament_remaining) const PRODUCTION_LITERAL_COMPLEMENT: [&str; 3] = [
    "chamber_minimal_temperature",
    "filament_long_retractions_when_cut",
    "filament_retraction_distances_when_cut",
];
