mod enums;
mod wire;

use std::fmt;

use serde::{Deserialize, Deserializer, de::Visitor};

pub use enums::{
    ProcessCounterboreHoleBridging, ProcessEnsureVerticalShellThickness, ProcessFuzzySkinMode,
    ProcessFuzzySkinType, ProcessIroningType, ProcessNoiseType, ProcessSeamScarfType,
    ProcessWallDirection, ProcessWallSequence,
};

use super::super::{
    FloatOrPercent, OrcaBool, OrcaFloat, OrcaInt, OrcaInts, OrcaString, OrcaStrings, Percent,
    option_group::declare_option_group,
};
use super::object_source::ProcessInfillPattern;

declare_option_group! {
    pub struct ProcessRegionSourceOptions, ProcessRegionSourceOptionsBuilder {
        print_extruder_id => "print_extruder_id": OrcaInts = OrcaInts(vec![OrcaInt(1)]),
        print_extruder_variant => "print_extruder_variant": OrcaStrings = strings(&["Direct Drive Standard"]),
        bottom_shell_layers => "bottom_shell_layers": OrcaInt = OrcaInt(3),
        bottom_shell_thickness => "bottom_shell_thickness": OrcaFloat = OrcaFloat(0.0),
        bridge_angle => "bridge_angle": OrcaFloat = OrcaFloat(0.0),
        internal_bridge_angle => "internal_bridge_angle": OrcaFloat = OrcaFloat(0.0),
        relative_bridge_angle => "relative_bridge_angle": OrcaBool = OrcaBool(false),
        bridge_flow => "bridge_flow": OrcaFloat = OrcaFloat(1.0),
        bridge_line_width => "bridge_line_width": FloatOrPercent = FloatOrPercent::Percent(Percent(100.0)),
        internal_bridge_flow => "internal_bridge_flow": OrcaFloat = OrcaFloat(1.0),
        bridge_speed => "bridge_speed": OrcaFloat = OrcaFloat(25.0),
        internal_bridge_speed => "internal_bridge_speed": FloatOrPercent = FloatOrPercent::Percent(Percent(150.0)),
        ensure_vertical_shell_thickness => "ensure_vertical_shell_thickness": ProcessEnsureVerticalShellThickness = ProcessEnsureVerticalShellThickness::EnsureAll,
        top_surface_density => "top_surface_density": Percent = Percent(100.0),
        bottom_surface_density => "bottom_surface_density": Percent = Percent(100.0),
        top_surface_pattern => "top_surface_pattern": ProcessInfillPattern = ProcessInfillPattern::MonotonicLine,
        bottom_surface_pattern => "bottom_surface_pattern": ProcessInfillPattern = ProcessInfillPattern::Monotonic,
        internal_solid_infill_pattern => "internal_solid_infill_pattern": ProcessInfillPattern = ProcessInfillPattern::Monotonic,
        outer_wall_line_width => "outer_wall_line_width": FloatOrPercent = FloatOrPercent::Float(0.0),
        outer_wall_speed => "outer_wall_speed": OrcaFloat = OrcaFloat(60.0),
        infill_direction => "infill_direction": OrcaFloat = OrcaFloat(45.0),
        solid_infill_direction => "solid_infill_direction": OrcaFloat = OrcaFloat(45.0),
        solid_infill_rotate_template => "solid_infill_rotate_template": OrcaString = string(""),
        symmetric_infill_y_axis => "symmetric_infill_y_axis": OrcaBool = OrcaBool(false),
        infill_shift_step => "infill_shift_step": OrcaFloat = OrcaFloat(0.4),
        sparse_infill_rotate_template => "sparse_infill_rotate_template": OrcaString = string(""),
        sparse_infill_density => "sparse_infill_density": Percent = Percent(20.0),
        sparse_infill_pattern => "sparse_infill_pattern": ProcessInfillPattern = ProcessInfillPattern::CrossHatch,
        lateral_lattice_angle_1 => "lateral_lattice_angle_1": OrcaFloat = OrcaFloat(-45.0),
        lateral_lattice_angle_2 => "lateral_lattice_angle_2": OrcaFloat = OrcaFloat(45.0),
        infill_overhang_angle => "infill_overhang_angle": OrcaFloat = OrcaFloat(60.0),
        lightning_overhang_angle => "lightning_overhang_angle": OrcaFloat = OrcaFloat(45.0),
        lightning_prune_angle => "lightning_prune_angle": OrcaFloat = OrcaFloat(45.0),
        lightning_straightening_angle => "lightning_straightening_angle": OrcaFloat = OrcaFloat(45.0),
        align_infill_direction_to_model => "align_infill_direction_to_model": OrcaBool = OrcaBool(false),
        extra_solid_infills => "extra_solid_infills": OrcaString = string(""),
        fuzzy_skin => "fuzzy_skin": ProcessFuzzySkinType = ProcessFuzzySkinType::Disabled,
        fuzzy_skin_thickness => "fuzzy_skin_thickness": OrcaFloat = OrcaFloat(0.2),
        fuzzy_skin_point_distance => "fuzzy_skin_point_distance": OrcaFloat = OrcaFloat(0.3),
        fuzzy_skin_first_layer => "fuzzy_skin_first_layer": OrcaBool = OrcaBool(false),
        fuzzy_skin_noise_type => "fuzzy_skin_noise_type": ProcessNoiseType = ProcessNoiseType::Classic,
        fuzzy_skin_mode => "fuzzy_skin_mode": ProcessFuzzySkinMode = ProcessFuzzySkinMode::Displacement,
        fuzzy_skin_scale => "fuzzy_skin_scale": OrcaFloat = OrcaFloat(1.0),
        fuzzy_skin_octaves => "fuzzy_skin_octaves": OrcaInt = OrcaInt(4),
        fuzzy_skin_persistence => "fuzzy_skin_persistence": OrcaFloat = OrcaFloat(0.5),
        fuzzy_skin_ripples_per_layer => "fuzzy_skin_ripples_per_layer": OrcaInt = OrcaInt(15),
        fuzzy_skin_ripple_offset => "fuzzy_skin_ripple_offset": Percent = Percent(50.0),
        fuzzy_skin_layers_between_ripple_offset => "fuzzy_skin_layers_between_ripple_offset": OrcaInt = OrcaInt(1),
        gap_infill_speed => "gap_infill_speed": OrcaFloat = OrcaFloat(30.0),
        sparse_infill_filament_id => "sparse_infill_filament_id": OrcaInt = OrcaInt(0),
        sparse_infill_line_width => "sparse_infill_line_width": FloatOrPercent = FloatOrPercent::Float(0.0),
        infill_wall_overlap => "infill_wall_overlap": Percent = Percent(15.0),
        top_bottom_infill_wall_overlap => "top_bottom_infill_wall_overlap": Percent = Percent(25.0),
        sparse_infill_speed => "sparse_infill_speed": OrcaFloat = OrcaFloat(100.0),
        skeleton_infill_density => "skeleton_infill_density": Percent = Percent(25.0),
        skin_infill_density => "skin_infill_density": Percent = Percent(25.0),
        infill_lock_depth => "infill_lock_depth": OrcaFloat = OrcaFloat(1.0),
        skin_infill_depth => "skin_infill_depth": OrcaFloat = OrcaFloat(2.0),
        skin_infill_line_width => "skin_infill_line_width": FloatOrPercent = FloatOrPercent::Percent(Percent(100.0)),
        skeleton_infill_line_width => "skeleton_infill_line_width": FloatOrPercent = FloatOrPercent::Percent(Percent(100.0)),
        infill_combination => "infill_combination": OrcaBool = OrcaBool(false),
        infill_combination_max_layer_height => "infill_combination_max_layer_height": FloatOrPercent = FloatOrPercent::Percent(Percent(100.0)),
        fill_multiline => "fill_multiline": OrcaInt = OrcaInt(1),
        gyroid_optimized => "gyroid_optimized": OrcaBool = OrcaBool(false),
        ironing_type => "ironing_type": ProcessIroningType = ProcessIroningType::NoIroning,
        ironing_pattern => "ironing_pattern": ProcessInfillPattern = ProcessInfillPattern::Rectilinear,
        ironing_flow => "ironing_flow": Percent = Percent(10.0),
        ironing_spacing => "ironing_spacing": OrcaFloat = OrcaFloat(0.1),
        ironing_inset => "ironing_inset": OrcaFloat = OrcaFloat(0.0),
        ironing_speed => "ironing_speed": OrcaFloat = OrcaFloat(20.0),
        ironing_angle => "ironing_angle": OrcaFloat = OrcaFloat(0.0),
        ironing_angle_fixed => "ironing_angle_fixed": OrcaBool = OrcaBool(false),
        detect_overhang_wall => "detect_overhang_wall": OrcaBool = OrcaBool(true),
        outer_wall_filament_id => "outer_wall_filament_id": OrcaInt = OrcaInt(0),
        inner_wall_filament_id => "inner_wall_filament_id": OrcaInt = OrcaInt(0),
        inner_wall_line_width => "inner_wall_line_width": FloatOrPercent = FloatOrPercent::Float(0.0),
        inner_wall_speed => "inner_wall_speed": OrcaFloat = OrcaFloat(60.0),
        wall_loops => "wall_loops": OrcaInt = OrcaInt(2),
        alternate_extra_wall => "alternate_extra_wall": OrcaBool = OrcaBool(false),
        minimum_sparse_infill_area => "minimum_sparse_infill_area": OrcaFloat = OrcaFloat(15.0),
        internal_solid_filament_id => "internal_solid_filament_id": OrcaInt = OrcaInt(0),
        top_surface_filament_id => "top_surface_filament_id": OrcaInt = OrcaInt(0),
        bottom_surface_filament_id => "bottom_surface_filament_id": OrcaInt = OrcaInt(0),
        internal_solid_infill_line_width => "internal_solid_infill_line_width": FloatOrPercent = FloatOrPercent::Float(0.0),
        internal_solid_infill_speed => "internal_solid_infill_speed": OrcaFloat = OrcaFloat(100.0),
        detect_thin_wall => "detect_thin_wall": OrcaBool = OrcaBool(false),
        top_surface_line_width => "top_surface_line_width": FloatOrPercent = FloatOrPercent::Float(0.0),
        top_shell_layers => "top_shell_layers": OrcaInt = OrcaInt(4),
        top_shell_thickness => "top_shell_thickness": OrcaFloat = OrcaFloat(0.6),
        top_surface_speed => "top_surface_speed": OrcaFloat = OrcaFloat(100.0),
        enable_overhang_speed => "enable_overhang_speed": OrcaBool = OrcaBool(true),
        overhang_1_4_speed => "overhang_1_4_speed": FloatOrPercent = FloatOrPercent::Float(0.0),
        overhang_2_4_speed => "overhang_2_4_speed": FloatOrPercent = FloatOrPercent::Float(0.0),
        overhang_3_4_speed => "overhang_3_4_speed": FloatOrPercent = FloatOrPercent::Float(0.0),
        overhang_4_4_speed => "overhang_4_4_speed": FloatOrPercent = FloatOrPercent::Float(0.0),
        only_one_wall_top => "only_one_wall_top": OrcaBool = OrcaBool(false),
        min_width_top_surface => "min_width_top_surface": FloatOrPercent = FloatOrPercent::Percent(Percent(300.0)),
        only_one_wall_first_layer => "only_one_wall_first_layer": OrcaBool = OrcaBool(false),
        print_flow_ratio => "print_flow_ratio": OrcaFloat = OrcaFloat(1.0),
        seam_gap => "seam_gap": FloatOrPercent = FloatOrPercent::Percent(Percent(10.0)),
        role_based_wipe_speed => "role_based_wipe_speed": OrcaBool = OrcaBool(true),
        wipe_speed => "wipe_speed": FloatOrPercent = FloatOrPercent::Percent(Percent(80.0)),
        wipe_on_loops => "wipe_on_loops": OrcaBool = OrcaBool(false),
        wipe_before_external_loop => "wipe_before_external_loop": OrcaBool = OrcaBool(false),
        precise_outer_wall => "precise_outer_wall": OrcaBool = OrcaBool(true),
        bridge_density => "bridge_density": Percent = Percent(100.0),
        filter_out_gap_fill => "filter_out_gap_fill": OrcaFloat = OrcaFloat(0.0),
        small_perimeter_speed => "small_perimeter_speed": FloatOrPercent = FloatOrPercent::Percent(Percent(50.0)),
        small_perimeter_threshold => "small_perimeter_threshold": OrcaFloat = OrcaFloat(0.0),
        top_solid_infill_flow_ratio => "top_solid_infill_flow_ratio": OrcaFloat = OrcaFloat(1.0),
        bottom_solid_infill_flow_ratio => "bottom_solid_infill_flow_ratio": OrcaFloat = OrcaFloat(1.0),
        infill_anchor => "infill_anchor": FloatOrPercent = FloatOrPercent::Percent(Percent(400.0)),
        infill_anchor_max => "infill_anchor_max": FloatOrPercent = FloatOrPercent::Float(20.0),
        make_overhang_printable => "make_overhang_printable": OrcaBool = OrcaBool(false),
        extra_perimeters_on_overhangs => "extra_perimeters_on_overhangs": OrcaBool = OrcaBool(false),
        slowdown_for_curled_perimeters => "slowdown_for_curled_perimeters": OrcaBool = OrcaBool(false),
        hole_to_polyhole => "hole_to_polyhole": OrcaBool = OrcaBool(false),
        hole_to_polyhole_threshold => "hole_to_polyhole_threshold": FloatOrPercent = FloatOrPercent::Float(0.01),
        hole_to_polyhole_twisted => "hole_to_polyhole_twisted": OrcaBool = OrcaBool(true),
        overhang_reverse => "overhang_reverse": OrcaBool = OrcaBool(false),
        overhang_reverse_internal_only => "overhang_reverse_internal_only": OrcaBool = OrcaBool(false),
        overhang_reverse_threshold => "overhang_reverse_threshold": FloatOrPercent = FloatOrPercent::Percent(Percent(50.0)),
        counterbore_hole_bridging => "counterbore_hole_bridging": ProcessCounterboreHoleBridging = ProcessCounterboreHoleBridging::None,
        wall_sequence => "wall_sequence": ProcessWallSequence = ProcessWallSequence::InnerOuter,
        is_infill_first => "is_infill_first": OrcaBool = OrcaBool(false),
        small_area_infill_flow_compensation => "small_area_infill_flow_compensation": OrcaBool = OrcaBool(false),
        wall_direction => "wall_direction": ProcessWallDirection = ProcessWallDirection::CounterClockwise,
        first_layer_flow_ratio => "first_layer_flow_ratio": OrcaFloat = OrcaFloat(1.0),
        outer_wall_flow_ratio => "outer_wall_flow_ratio": OrcaFloat = OrcaFloat(1.0),
        inner_wall_flow_ratio => "inner_wall_flow_ratio": OrcaFloat = OrcaFloat(1.0),
        overhang_flow_ratio => "overhang_flow_ratio": OrcaFloat = OrcaFloat(1.0),
        sparse_infill_flow_ratio => "sparse_infill_flow_ratio": OrcaFloat = OrcaFloat(1.0),
        internal_solid_infill_flow_ratio => "internal_solid_infill_flow_ratio": OrcaFloat = OrcaFloat(1.0),
        gap_fill_flow_ratio => "gap_fill_flow_ratio": OrcaFloat = OrcaFloat(1.0),
        seam_slope_type => "seam_slope_type": ProcessSeamScarfType = ProcessSeamScarfType::None,
        seam_slope_conditional => "seam_slope_conditional": OrcaBool = OrcaBool(false),
        scarf_angle_threshold => "scarf_angle_threshold": OrcaInt = OrcaInt(155),
        seam_slope_start_height => "seam_slope_start_height": FloatOrPercent = FloatOrPercent::Float(0.0),
        seam_slope_entire_loop => "seam_slope_entire_loop": OrcaBool = OrcaBool(false),
        seam_slope_min_length => "seam_slope_min_length": OrcaFloat = OrcaFloat(20.0),
        seam_slope_steps => "seam_slope_steps": OrcaInt = OrcaInt(10),
        seam_slope_inner_walls => "seam_slope_inner_walls": OrcaBool = OrcaBool(false),
        scarf_joint_speed => "scarf_joint_speed": FloatOrPercent = FloatOrPercent::Percent(Percent(100.0)),
        scarf_joint_flow_ratio => "scarf_joint_flow_ratio": OrcaFloat = OrcaFloat(1.0),
        scarf_overhang_threshold => "scarf_overhang_threshold": Percent = Percent(40.0),
        zaa_enabled => "zaa_enabled": OrcaBool = OrcaBool(false),
        zaa_dont_alternate_fill_direction => "zaa_dont_alternate_fill_direction": OrcaBool = OrcaBool(false),
        zaa_min_z => "zaa_min_z": OrcaFloat = OrcaFloat(0.05),
        zaa_minimize_perimeter_height => "zaa_minimize_perimeter_height": OrcaFloat = OrcaFloat(35.0),
    }
}

impl ProcessRegionSourceOptions {
    pub const DECLARATION_ORDER: [&'static str; 149] = [
        "print_extruder_id",
        "print_extruder_variant",
        "bottom_shell_layers",
        "bottom_shell_thickness",
        "bridge_angle",
        "internal_bridge_angle",
        "relative_bridge_angle",
        "bridge_flow",
        "bridge_line_width",
        "internal_bridge_flow",
        "bridge_speed",
        "internal_bridge_speed",
        "ensure_vertical_shell_thickness",
        "top_surface_density",
        "bottom_surface_density",
        "top_surface_pattern",
        "bottom_surface_pattern",
        "internal_solid_infill_pattern",
        "outer_wall_line_width",
        "outer_wall_speed",
        "infill_direction",
        "solid_infill_direction",
        "solid_infill_rotate_template",
        "symmetric_infill_y_axis",
        "infill_shift_step",
        "sparse_infill_rotate_template",
        "sparse_infill_density",
        "sparse_infill_pattern",
        "lateral_lattice_angle_1",
        "lateral_lattice_angle_2",
        "infill_overhang_angle",
        "lightning_overhang_angle",
        "lightning_prune_angle",
        "lightning_straightening_angle",
        "align_infill_direction_to_model",
        "extra_solid_infills",
        "fuzzy_skin",
        "fuzzy_skin_thickness",
        "fuzzy_skin_point_distance",
        "fuzzy_skin_first_layer",
        "fuzzy_skin_noise_type",
        "fuzzy_skin_mode",
        "fuzzy_skin_scale",
        "fuzzy_skin_octaves",
        "fuzzy_skin_persistence",
        "fuzzy_skin_ripples_per_layer",
        "fuzzy_skin_ripple_offset",
        "fuzzy_skin_layers_between_ripple_offset",
        "gap_infill_speed",
        "sparse_infill_filament_id",
        "sparse_infill_line_width",
        "infill_wall_overlap",
        "top_bottom_infill_wall_overlap",
        "sparse_infill_speed",
        "skeleton_infill_density",
        "skin_infill_density",
        "infill_lock_depth",
        "skin_infill_depth",
        "skin_infill_line_width",
        "skeleton_infill_line_width",
        "infill_combination",
        "infill_combination_max_layer_height",
        "fill_multiline",
        "gyroid_optimized",
        "ironing_type",
        "ironing_pattern",
        "ironing_flow",
        "ironing_spacing",
        "ironing_inset",
        "ironing_speed",
        "ironing_angle",
        "ironing_angle_fixed",
        "detect_overhang_wall",
        "outer_wall_filament_id",
        "inner_wall_filament_id",
        "inner_wall_line_width",
        "inner_wall_speed",
        "wall_loops",
        "alternate_extra_wall",
        "minimum_sparse_infill_area",
        "internal_solid_filament_id",
        "top_surface_filament_id",
        "bottom_surface_filament_id",
        "internal_solid_infill_line_width",
        "internal_solid_infill_speed",
        "detect_thin_wall",
        "top_surface_line_width",
        "top_shell_layers",
        "top_shell_thickness",
        "top_surface_speed",
        "enable_overhang_speed",
        "overhang_1_4_speed",
        "overhang_2_4_speed",
        "overhang_3_4_speed",
        "overhang_4_4_speed",
        "only_one_wall_top",
        "min_width_top_surface",
        "only_one_wall_first_layer",
        "print_flow_ratio",
        "seam_gap",
        "role_based_wipe_speed",
        "wipe_speed",
        "wipe_on_loops",
        "wipe_before_external_loop",
        "precise_outer_wall",
        "bridge_density",
        "filter_out_gap_fill",
        "small_perimeter_speed",
        "small_perimeter_threshold",
        "top_solid_infill_flow_ratio",
        "bottom_solid_infill_flow_ratio",
        "infill_anchor",
        "infill_anchor_max",
        "make_overhang_printable",
        "extra_perimeters_on_overhangs",
        "slowdown_for_curled_perimeters",
        "hole_to_polyhole",
        "hole_to_polyhole_threshold",
        "hole_to_polyhole_twisted",
        "overhang_reverse",
        "overhang_reverse_internal_only",
        "overhang_reverse_threshold",
        "counterbore_hole_bridging",
        "wall_sequence",
        "is_infill_first",
        "small_area_infill_flow_compensation",
        "wall_direction",
        "first_layer_flow_ratio",
        "outer_wall_flow_ratio",
        "inner_wall_flow_ratio",
        "overhang_flow_ratio",
        "sparse_infill_flow_ratio",
        "internal_solid_infill_flow_ratio",
        "gap_fill_flow_ratio",
        "seam_slope_type",
        "seam_slope_conditional",
        "scarf_angle_threshold",
        "seam_slope_start_height",
        "seam_slope_entire_loop",
        "seam_slope_min_length",
        "seam_slope_steps",
        "seam_slope_inner_walls",
        "scarf_joint_speed",
        "scarf_joint_flow_ratio",
        "scarf_overhang_threshold",
        "zaa_enabled",
        "zaa_dont_alternate_fill_direction",
        "zaa_min_z",
        "zaa_minimize_perimeter_height",
    ];
}

impl Default for ProcessRegionSourceOptions {
    fn default() -> Self {
        ProcessRegionSourceOptionsBuilder::default().resolve()
    }
}

impl<'de> Deserialize<'de> for ProcessRegionSourceOptions {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        deserializer.deserialize_map(RegionSourceVisitor)
    }
}

struct RegionSourceVisitor;

impl<'de> Visitor<'de> for RegionSourceVisitor {
    type Value = ProcessRegionSourceOptions;

    fn expecting(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("Orca process region-source options")
    }

    fn visit_map<A>(self, mut map: A) -> Result<Self::Value, A::Error>
    where
        A: serde::de::MapAccess<'de>,
    {
        let mut builder = ProcessRegionSourceOptionsBuilder::default();
        while let Some(key) = map.next_key::<String>()? {
            if !builder.deserialize_known_field(&key, &mut map)? {
                return Err(serde::de::Error::custom(format!(
                    "unknown Orca process region option {key}"
                )));
            }
        }
        Ok(builder.resolve())
    }
}

fn string(value: &str) -> OrcaString {
    OrcaString(value.to_owned())
}

fn strings(values: &[&str]) -> OrcaStrings {
    OrcaStrings(values.iter().map(|value| (*value).to_owned()).collect())
}
