use crate::project_slice::{
    island_print_order::{IslandPrintEntity, OrderedExtrusionLayer, PreparedPostIslandPrintOrder},
    perimeters::classic::traversal::PreparedPostClassicTraversal,
};
use crate::{GenerationMetadata, SliceError};

pub(super) fn emit(
    prepared: &PreparedPostIslandPrintOrder,
    traversal: &PreparedPostClassicTraversal,
    metadata: GenerationMetadata,
) -> Result<Vec<u8>, SliceError> {
    let mut output = Vec::new();
    append_header(&mut output, metadata, &prepared.objects, traversal);
    if let Some(config) = &traversal.config_block {
        output.extend_from_slice(config);
    }
    append_width_block(&mut output, traversal);
    output.extend_from_slice(b"; EXECUTABLE_BLOCK_START\n");
    append_machine_limits(&mut output, traversal);
    let mut state = EmitState::default();
    for object in &prepared.objects {
        for (layer_index, layer) in object.iter().enumerate() {
            output.extend_from_slice(b"; CHANGE_LAYER\n");
            output.extend_from_slice(format!("; LAYER_CHANGE {layer_index}\n").as_bytes());
            emit_layer(&mut output, layer, traversal.scale, &mut state)?;
        }
    }
    output.extend_from_slice(b"M2\n");
    Ok(output)
}

#[derive(Default)]
struct EmitState {
    x: f64,
    y: f64,
    e: f64,
}

fn append_header(
    output: &mut Vec<u8>,
    metadata: GenerationMetadata,
    objects: &[Vec<OrderedExtrusionLayer>],
    traversal: &PreparedPostClassicTraversal,
) {
    let (year, month, day, hour, minute, second) = metadata.timestamp();
    let layers = objects.iter().map(Vec::len).max().unwrap_or(0);
    let label_id = traversal
        .project
        .objects()
        .first()
        .and_then(|object| object.instances().first())
        .map_or(0, |instance| instance.loaded_label_id());
    let density = format_values(
        &traversal
            .resolved
            .views
            .full
            .filament
            .gcode
            .filament_density
            .0,
    );
    let diameter = format_values(
        &traversal
            .resolved
            .views
            .full
            .filament
            .gcode
            .filament_diameter
            .0,
    );
    let max_z = traversal
        .objects
        .first()
        .into_iter()
        .flat_map(|object| object.records.iter())
        .filter_map(|record| record.as_ref())
        .map(|record| record.layer_height)
        .sum::<f64>();
    let filament_count = traversal.resolved.usage.supported_used_filaments.len();
    output.extend_from_slice(b"; HEADER_BLOCK_START\n");
    output.extend_from_slice(
        format!(
            "; generated by Ares 2.4.2 on {year:04}-{month:02}-{day:02} at {hour:02}:{minute:02}:{second:02}\n"
        )
        .as_bytes(),
    );
    output.extend_from_slice(b"; model printing time: 0s; total estimated time: 0s\n");
    output.extend_from_slice(b"; estimated first layer printing time (normal mode) = 0s\n");
    output.extend_from_slice(format!("; total layer number: {layers}\n").as_bytes());
    output.extend_from_slice(format!("; model label id: {label_id}\n").as_bytes());
    output.extend_from_slice(format!("; filament_density: {density}\n").as_bytes());
    output.extend_from_slice(format!("; filament_diameter: {diameter}\n").as_bytes());
    output.extend_from_slice(format!("; max_z_height: {max_z:.2}\n").as_bytes());
    output.extend_from_slice(format!("; filament: {filament_count}\n").as_bytes());
    output.extend_from_slice(b"; HEADER_BLOCK_END\n\n");
}

fn format_values(values: &[crate::OrcaFloat]) -> String {
    values
        .iter()
        .map(|value| format!("{:.2}", value.0))
        .collect::<Vec<_>>()
        .join(",")
}

fn append_width_block(output: &mut Vec<u8>, traversal: &PreparedPostClassicTraversal) {
    let settings = &traversal.resolved.views.full;
    let nozzle = settings
        .project
        .print
        .nozzle_diameter
        .0
        .first()
        .map_or(0.4, |value| value.0);
    let object = traversal.resolved.objects.first();
    let region = object
        .and_then(|object| object.layer_candidates.first())
        .and_then(|layer| layer.model_parts.first().map(|part| &part.region));
    let object_width = object.and_then(|object| width(object.object.line_width, nozzle));
    let widths = [
        region
            .and_then(|region| width(region.outer_wall_line_width, nozzle))
            .or(object_width),
        region
            .and_then(|region| width(region.inner_wall_line_width, nozzle))
            .or(object_width),
        region
            .and_then(|region| width(region.sparse_infill_line_width, nozzle))
            .or(object_width),
        region
            .and_then(|region| width(region.internal_solid_infill_line_width, nozzle))
            .or(object_width),
        region
            .and_then(|region| width(region.top_surface_line_width, nozzle))
            .or(object_width),
        width(settings.process.print.initial_layer_line_width, nozzle).or(object_width),
    ];
    let labels = [
        "external perimeters",
        "perimeters",
        "infill",
        "solid infill",
        "top infill",
    ];
    for (index, label) in labels.into_iter().enumerate() {
        if let Some(width) = widths[index] {
            output.extend_from_slice(
                format!("; {label} extrusion width = {width:.2}mm\n").as_bytes(),
            );
        }
    }
    if let Some(width) = widths[5] {
        output.extend_from_slice(
            format!("; first layer extrusion width = {width:.2}mm\n").as_bytes(),
        );
    }
    output.push(b'\n');
}

fn width(value: crate::FloatOrPercent, nozzle: f64) -> Option<f32> {
    match value {
        crate::FloatOrPercent::Float(value) if value > 0.0 => Some(value as f32),
        crate::FloatOrPercent::Percent(value) if value.0 > 0.0 => {
            Some((value.0 * nozzle / 100.0) as f32)
        }
        _ => None,
    }
}

fn append_machine_limits(output: &mut Vec<u8>, traversal: &PreparedPostClassicTraversal) {
    let machine = &traversal.resolved.views.full.printer.machine;
    let travel_acceleration = if traversal.resolved.views.full.printer.gcode.gcode_flavor
        == crate::GCodeFlavor::MarlinLegacy
    {
        machine.machine_max_acceleration_extruding.clone()
    } else {
        machine.machine_max_acceleration_travel.clone()
    };
    output.extend_from_slice(b"M73 P0 R0\n");
    output.extend_from_slice(
        format!(
            "M201 X{} Y{} Z{} E{}\n",
            first(&machine.machine_max_acceleration_x),
            first(&machine.machine_max_acceleration_y),
            first(&machine.machine_max_acceleration_z),
            first(&machine.machine_max_acceleration_e),
        )
        .as_bytes(),
    );
    output.extend_from_slice(
        format!(
            "M203 X{} Y{} Z{} E{}\n",
            first(&machine.machine_max_speed_x),
            first(&machine.machine_max_speed_y),
            first(&machine.machine_max_speed_z),
            first(&machine.machine_max_speed_e),
        )
        .as_bytes(),
    );
    output.extend_from_slice(
        format!(
            "M204 P{} R{} T{}\n",
            first(&machine.machine_max_acceleration_extruding),
            first(&machine.machine_max_acceleration_retracting),
            first(&travel_acceleration),
        )
        .as_bytes(),
    );
    output.extend_from_slice(
        format!(
            "M205 X{:.2} Y{:.2} Z{:.2} E{:.2} ; sets the jerk limits, mm/sec\n",
            first(&machine.machine_max_jerk_x),
            first(&machine.machine_max_jerk_y),
            first(&machine.machine_max_jerk_z),
            first(&machine.machine_max_jerk_e),
        )
        .as_bytes(),
    );
    output.extend_from_slice(b"M106 S0\nM106 P2 S0\n");
}

fn first(values: &crate::OrcaFloats) -> f64 {
    values.0.first().map_or(0.0, |value| value.0)
}

#[expect(
    clippy::excessive_nesting,
    reason = "keeps the source ordered extrusion-entity traversal together"
)]
fn emit_layer(
    output: &mut Vec<u8>,
    layer: &OrderedExtrusionLayer,
    scale: crate::geometry::CoordinateScale,
    state: &mut EmitState,
) -> Result<(), SliceError> {
    for island in &layer.islands {
        for entity in &island.entities {
            match entity {
                IslandPrintEntity::Perimeter(collection) => {
                    for loop_ in &collection.entities {
                        for path in &loop_.extrusion_loop.paths {
                            emit_path(output, path, scale, state);
                        }
                    }
                }
                IslandPrintEntity::Fill(collection) => {
                    for path in &collection.paths {
                        emit_polyline(output, &path.polyline, path.mm3_per_mm, scale, state);
                    }
                }
                IslandPrintEntity::Thin(entity) => match entity {
                    crate::project_slice::perimeters::classic::gap_extrusion::GapFillEntity::Path(path) => {
                        emit_path(output, path, scale, state);
                    }
                    crate::project_slice::perimeters::classic::gap_extrusion::GapFillEntity::Loop(paths) => {
                        for path in paths {
                            emit_path(output, path, scale, state);
                        }
                    }
                },
            }
        }
    }
    Ok(())
}

fn emit_path(
    output: &mut Vec<u8>,
    path: &crate::project_slice::perimeters::classic::materialize::ExtrusionPath,
    scale: crate::geometry::CoordinateScale,
    state: &mut EmitState,
) {
    emit_polyline3(output, &path.polyline.points, path.mm3_per_mm, scale, state);
}

fn emit_polyline(
    output: &mut Vec<u8>,
    polyline: &crate::geometry::Polyline,
    mm3_per_mm: f64,
    scale: crate::geometry::CoordinateScale,
    state: &mut EmitState,
) {
    emit_points(
        output,
        polyline.points().iter().map(|point| (point.x(), point.y())),
        mm3_per_mm,
        scale,
        state,
    );
}

fn emit_polyline3(
    output: &mut Vec<u8>,
    points: &[crate::project_slice::perimeters::classic::materialize::Point3],
    mm3_per_mm: f64,
    scale: crate::geometry::CoordinateScale,
    state: &mut EmitState,
) {
    emit_points(
        output,
        points.iter().map(|point| (point.x, point.y)),
        mm3_per_mm,
        scale,
        state,
    );
}

fn emit_points(
    output: &mut Vec<u8>,
    points: impl Iterator<Item = (i64, i64)>,
    mm3_per_mm: f64,
    scale: crate::geometry::CoordinateScale,
    state: &mut EmitState,
) {
    for (x, y) in points {
        let x = scale.unscale(x);
        let y = scale.unscale(y);
        let distance = (x - state.x).hypot(y - state.y);
        state.e += distance * mm3_per_mm;
        output.extend_from_slice(format!("G1 X{x:.5} Y{y:.5} E{:.5}\n", state.e).as_bytes());
        state.x = x;
        state.y = y;
    }
}
