mod bounds;
mod capabilities;
mod chained_fixture;
mod chained_intersections;
mod closing;
mod closing_fixture;
mod compensation;
mod conical_overhang;
mod elephant_foot;
mod fixture;
mod integration;
mod largest_contour_fixture;
mod largest_contours;
mod looped_fixture;
mod looped_intersections;
mod parameters;
pub(super) mod perimeters;
mod pre_closing_fixture;
mod pre_closing_unions;
pub(in crate::project_slice) mod prepare_infill;
mod profile_layers;
mod raw_fixture;
mod raw_lifecycle;
mod raw_preflights;
mod raw_support;
mod raw_transform;
mod region_fixture;
mod region_slices;
mod slice_ordering;
mod slicing_mode_fixture;
mod slicing_mode_intersections;
pub(in crate::project_slice) mod support;
mod top_empty_layers;
mod volume_bounds;
mod volume_regions;
