use serde_json::{Map, Value, json};

mod extruder_variant_id_values;
mod filament_extruder_override_values;
mod min_feature_length_values;
mod process_values;
mod restart_speed_seam_values;
mod scarf_seam_values;
mod sla_display_tilt_values;
mod tail_values;
mod wipe_speed_loop_values;

pub(super) fn insert_known_values(values: &mut Map<String, Value>) {
    for (key, value) in [
        ("accel_to_decel_enable", json!(true)),
        ("accel_to_decel_factor", json!(50)),
        ("activate_air_filtration", json!([false])),
        ("activate_air_filtration_during_print", json!([true])),
        ("activate_air_filtration_on_completion", json!([true])),
        ("adaptive_bed_mesh_margin", json!(0)),
        ("adaptive_pressure_advance", json!([false])),
        ("adaptive_pressure_advance_bridges", json!([0])),
        ("adaptive_pressure_advance_model", json!(["0,0,0\n0,0,0"])),
        ("adaptive_pressure_advance_overhangs", json!([false])),
        ("additional_cooling_fan_speed", json!([0])),
        ("additional_fan_full_speed_layer", json!([0])),
        ("align_infill_direction_to_model", json!(false)),
        ("alternate_extra_wall", json!(false)),
        ("auxiliary_fan", json!(false)),
        ("bed_mesh_max", json!("99999x99999")),
        ("bed_mesh_min", json!("-99999x-99999")),
        ("bed_mesh_probe_distance", json!("50x50")),
        ("bed_temperature_formula", json!("by_highest_temp")),
        ("best_object_pos", json!("0.5x0.5")),
        ("layer_height", json!(0.2)),
        ("long_retractions_when_cut", json!([false])),
        ("long_retractions_when_ec", json!([false])),
        ("printable_area", json!("0x0,200x0,200x200,0x200")),
        ("preset_names", json!(["printer"])),
        ("pressure_advance", json!([0.02])),
        ("print_flow_ratio", json!(1)),
        ("printhost_authorization_type", json!("key")),
        ("reduce_crossing_wall", json!(true)),
        ("reduce_fan_stop_start_freq", json!([false])),
        ("reduce_infill_retraction", json!(false)),
        ("required_nozzle_HRC", json!([0])),
        (
            "machine_end_gcode",
            json!(
                "M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n"
            ),
        ),
        ("machine_load_filament_time", json!(0)),
        ("machine_max_acceleration_e", json!([5000, 5000])),
        ("machine_max_acceleration_extruding", json!([1500, 1250])),
        ("machine_max_acceleration_retracting", json!([1500, 1250])),
        ("machine_max_acceleration_travel", json!([0, 0])),
        ("machine_max_acceleration_x", json!([1000, 1000])),
        ("machine_max_acceleration_y", json!([1000, 1000])),
        ("machine_max_acceleration_z", json!([500, 200])),
        ("machine_max_speed_e", json!([120, 120])),
        ("machine_max_speed_x", json!([500, 200])),
        ("machine_max_speed_y", json!([500, 200])),
        ("machine_max_speed_z", json!([12, 12])),
        ("machine_max_jerk_e", json!([2.5, 2.5])),
        ("machine_max_jerk_x", json!([10, 10])),
        ("machine_max_jerk_y", json!([10, 10])),
        ("machine_max_jerk_z", json!([0.2, 0.4])),
        ("machine_max_junction_deviation", json!([0.01])),
        ("machine_min_extruding_rate", json!([0, 0])),
        ("machine_min_travel_rate", json!([0, 0])),
        ("machine_tool_change_time", json!(0)),
        ("machine_unload_filament_time", json!(0)),
        ("make_overhang_printable", json!(false)),
        ("make_overhang_printable_angle", json!(55)),
        ("make_overhang_printable_hole_size", json!(0)),
        ("max_bridge_length", json!(10)),
        ("max_resonance_avoidance_speed", json!(120)),
        ("max_travel_detour_distance", json!("50%")),
        ("cool_plate_temp", json!([35])),
        ("hot_plate_temp", json!([45])),
        ("cool_plate_temp_initial_layer", json!([35])),
        ("counterbore_hole_bridging", json!("none")),
        ("hot_plate_temp_initial_layer", json!([45])),
        ("infill_anchor", json!("400%")),
        ("infill_anchor_max", json!(20)),
        ("infill_combination", json!(false)),
        ("infill_combination_max_layer_height", json!("100%")),
        ("infill_lock_depth", json!(1)),
        ("infill_overhang_angle", json!(60)),
        ("infill_wall_overlap", json!(15)),
        ("inherits", json!("")),
        ("inherits_group", json!([])),
        ("infill_shift_step", json!(0.4)),
        ("curr_bed_type", json!("Cool Plate")),
        ("default_nozzle_volume_type", json!(["Standard"])),
        ("first_layer_print_sequence", json!([0])),
        ("full_fan_speed_layer", json!([0])),
        ("fuzzy_skin", json!("disabled_fuzzy")),
        ("fuzzy_skin_first_layer", json!(false)),
        ("fuzzy_skin_layers_between_ripple_offset", json!(1)),
        ("fuzzy_skin_mode", json!("displacement")),
        ("fuzzy_skin_noise_type", json!("classic")),
        ("fuzzy_skin_octaves", json!(4)),
        ("fuzzy_skin_persistence", json!(0.5)),
        ("fuzzy_skin_point_distance", json!(0.3)),
        ("fuzzy_skin_ripple_offset", json!("50%")),
        ("fuzzy_skin_ripples_per_layer", json!(15)),
        ("fuzzy_skin_scale", json!(1)),
        ("fuzzy_skin_thickness", json!(0.2)),
        ("other_layers_sequence_choice", json!("Auto")),
        ("before_layer_change_gcode", json!("")),
        ("bottom_shell_layers", json!(3)),
        ("bottom_solid_infill_flow_ratio", json!(1)),
        ("bottom_surface_pattern", json!("monotonic")),
        ("gap_fill_flow_ratio", json!(1)),
        ("gap_fill_target", json!("nowhere")),
        ("gap_infill_speed", json!(30)),
        ("gcode_add_line_number", json!(false)),
        ("gcode_comments", json!(false)),
        ("gcode_flavor", json!("marlin")),
        ("gcode_label_objects", json!(true)),
        ("grab_length", json!([0])),
        ("gyroid_optimized", json!(false)),
        ("has_filament_switcher", json!(false)),
        ("enable_arc_fitting", json!(false)),
        ("enable_filament_ramming", json!(true)),
        ("enable_extra_bridge_layer", json!("disabled")),
        ("enable_filament_dynamic_map", json!(false)),
        ("enable_long_retraction_when_cut", json!(0)),
        ("ensure_vertical_shell_thickness", json!("ensure_all")),
        ("enable_overhang_bridge_fan", json!([true])),
        ("enable_overhang_speed", json!(true)),
        ("enable_power_loss_recovery", json!("printer_configuration")),
        ("enable_pressure_advance", json!([false])),
        ("enable_wrapping_detection", json!(false)),
        ("overhang_fan_speed", json!([100])),
        ("overhang_fan_threshold", json!(["95%"])),
        ("overhang_flow_ratio", json!(1)),
        ("overhang_1_4_speed", json!(0)),
        ("overhang_2_4_speed", json!(0)),
        ("overhang_3_4_speed", json!(0)),
        ("overhang_4_4_speed", json!(0)),
        ("overhang_reverse", json!(false)),
        ("overhang_reverse_internal_only", json!(false)),
        ("overhang_reverse_threshold", json!("50%")),
        ("pellet_flow_coefficient", json!([0.4157])),
        ("pellet_modded_printer", json!(false)),
        ("part_cooling_fan_min_pwm", json!(0)),
        ("physical_extruder_map", json!([0])),
        ("post_process", json!([])),
        ("exclude_object", json!(false)),
        ("extra_loading_move", json!(-2)),
        ("extra_perimeters_on_overhangs", json!(false)),
        ("extra_solid_infills", json!("")),
        (
            "extrusion_rate_smoothing_external_perimeter_only",
            json!(false),
        ),
        ("extruder_clearance_height_to_lid", json!(120)),
        ("extruder_clearance_height_to_rod", json!(40)),
        ("extruder_clearance_radius", json!(40)),
        ("extruder_colour", json!([""])),
        ("extruder_offset", json!("0x0")),
        ("extruder_type", json!(["Direct Drive"])),
        ("min_resonance_avoidance_speed", json!(70)),
        ("min_width_top_surface", json!("300%")),
        ("mmu_segmented_region_interlocking_depth", json!(0)),
        ("mmu_segmented_region_max_width", json!(0)),
        ("notes", json!("")),
        ("nozzle_volume_type", json!(["Standard"])),
        ("only_one_wall_first_layer", json!(false)),
        ("only_one_wall_top", json!(false)),
        ("precise_outer_wall", json!(true)),
        ("bridge_acceleration", json!("50%")),
        ("bridge_angle", json!(0)),
        ("bridge_density", json!("100%")),
        ("brim_ears", json!(false)),
        ("brim_ears_detection_length", json!(1)),
        ("brim_ears_max_angle", json!(125)),
        ("brim_flow_ratio", json!(1)),
        ("brim_use_efc_outline", json!(false)),
        ("calib_flowrate_topinfill_special_order", json!(false)),
        ("close_additional_fan_first_x_layers", json!([1])),
        ("combine_brims", json!(false)),
        ("close_fan_the_first_x_layers", json!([1])),
        ("compatible_machine_expression_group", json!([])),
        ("compatible_printers", json!([])),
        ("compatible_printers_condition", json!("")),
        ("compatible_prints", json!([])),
        ("compatible_prints_condition", json!("")),
        ("compatible_process_expression_group", json!([])),
        ("complete_print_exhaust_fan_speed", json!([80])),
        ("cooling_tube_length", json!(5)),
        ("cooling_tube_retraction", json!(91.5)),
        ("default_acceleration", json!(500)),
        ("default_filament_colour", json!([""])),
        ("default_filament_profile", json!([])),
        ("default_jerk", json!(0)),
        ("default_junction_deviation", json!(0)),
        ("default_print_profile", json!("")),
        ("dont_filter_internal_bridges", json!("disabled")),
        ("dont_slow_down_outer_wall", json!([false])),
        ("during_print_exhaust_fan_speed", json!([60])),
        ("print_compatible_printers", json!([])),
        ("print_settings_id", json!("")),
        ("printer_structure", json!("undefine")),
        ("printer_model", json!("")),
        ("printer_notes", json!("")),
        ("printer_settings_id", json!("")),
        ("printer_variant", json!("")),
        ("print_order", json!("default")),
        ("print_sequence", json!("by layer")),
        ("printing_by_object_gcode", json!("")),
        ("raft_contact_distance", json!(0.1)),
        ("raft_expansion", json!(1.5)),
        ("raft_first_layer_density", json!(90)),
        ("raft_first_layer_expansion", json!(2.0)),
        ("raft_layers", json!(0)),
        ("process_change_extrusion_role_gcode", json!("")),
        ("upward_compatible_machine", json!([])),
        ("volumetric_speed_coefficients", json!([""])),
        ("infill_jerk", json!(9)),
        ("initial_layer_acceleration", json!(300)),
        ("initial_layer_infill_speed", json!(60)),
        ("initial_layer_jerk", json!(9)),
        ("initial_layer_line_width", json!(0)),
        ("initial_layer_min_bead_width", json!(85)),
        ("initial_layer_print_height", json!(0.2)),
        ("initial_layer_speed", json!(30)),
        ("initial_layer_travel_acceleration", json!("100%")),
        ("initial_layer_travel_jerk", json!("100%")),
        ("initial_layer_travel_speed", json!("100%")),
        ("inner_wall_acceleration", json!(10000)),
        ("inner_wall_jerk", json!(9)),
        ("inner_wall_line_width", json!(0)),
        ("inner_wall_speed", json!(60)),
        ("input_shaping_damp_x", json!(0.1)),
        ("input_shaping_damp_y", json!(0.1)),
        ("input_shaping_emit", json!(false)),
        ("input_shaping_freq_x", json!(0)),
        ("input_shaping_freq_y", json!(0)),
        ("input_shaping_type", json!("Default")),
        ("interface_shells", json!(false)),
        ("interlocking_beam", json!(false)),
        ("interlocking_beam_layer_count", json!(2)),
        ("interlocking_beam_width", json!(0.8)),
        ("interlocking_boundary_avoidance", json!(2)),
        ("interlocking_depth", json!(2)),
        ("interlocking_orientation", json!(22.5)),
        ("internal_bridge_angle", json!(0)),
        ("internal_bridge_density", json!("100%")),
        ("internal_bridge_fan_speed", json!([-1])),
        ("internal_solid_infill_acceleration", json!("100%")),
        ("internal_solid_infill_flow_ratio", json!(1)),
        ("internal_solid_infill_pattern", json!("monotonic")),
        ("ironing_angle", json!(0)),
        ("ironing_angle_fixed", json!(false)),
        ("ironing_expansion", json!(0)),
        ("ironing_fan_speed", json!([-1])),
        ("ironing_flow", json!(10)),
        ("ironing_inset", json!(0)),
        ("ironing_pattern", json!("rectilinear")),
        ("ironing_spacing", json!(0.1)),
        ("ironing_speed", json!(20)),
        ("ironing_type", json!("no ironing")),
        ("outer_wall_acceleration", json!(500)),
        ("outer_wall_jerk", json!(9)),
        ("sparse_infill_acceleration", json!("100%")),
        ("top_solid_infill_flow_ratio", json!(1)),
        ("top_surface_acceleration", json!(500)),
        ("top_surface_jerk", json!(9)),
        ("top_surface_pattern", json!("monotonicline")),
        ("travel_acceleration", json!(10000)),
        ("travel_jerk", json!(12)),
        ("travel_slope", json!([3])),
        ("fan_cooling_layer_time", json!([60])),
        ("fan_kickstart", json!(0)),
        ("fan_max_speed", json!([100])),
        ("fan_min_speed", json!([20])),
        ("fan_speedup_overhangs", json!(true)),
        ("fan_speedup_time", json!(0)),
        ("filament_adaptive_volumetric_speed", json!([false])),
        ("filament_adhesiveness_category", json!([0])),
        ("filament_change_length", json!([10])),
        ("filament_colour", json!(["#F2754E"])),
        ("filament_colour_type", json!(["1"])),
        ("filament_cooling_before_tower", json!([10])),
        ("filament_cooling_final_speed", json!([3.4])),
        ("filament_cooling_initial_speed", json!([2.2])),
        ("filament_cooling_moves", json!([4])),
        ("filament_cost", json!([0])),
        ("filament_density", json!([0])),
        ("filament_end_gcode", json!([" "])),
        ("filament_flow_ratio", json!([1])),
        ("filament_flush_temp", json!([0])),
        ("filament_flush_volumetric_speed", json!([0])),
        ("filament_ids", json!([""])),
        ("filament_ironing_flow", json!([null])),
        ("filament_ironing_inset", json!([null])),
        ("filament_ironing_spacing", json!([null])),
        ("filament_ironing_speed", json!([null])),
        ("filament_is_support", json!([false])),
        ("filament_loading_speed", json!([28])),
        ("filament_loading_speed_start", json!([3])),
        ("filament_map", json!([1])),
        ("filament_map_mode", json!("Auto For Flush")),
        ("filament_max_volumetric_speed", json!([2])),
        ("filament_minimal_purge_on_wipe_tower", json!([15])),
        ("filament_multi_colour", json!([""])),
        ("filament_multitool_ramming", json!([false])),
        ("filament_multitool_ramming_flow", json!([10])),
        ("filament_multitool_ramming_volume", json!([10])),
        ("filament_notes", json!([""])),
        ("filament_printable", json!([3])),
        (
            "filament_ramming_parameters",
            json!([
                "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
            ]),
        ),
        ("filament_settings_id", json!([""])),
        ("filament_shrink", json!(["100%"])),
        ("filament_shrinkage_compensation_z", json!(["100%"])),
        ("filament_soluble", json!([false])),
        ("filament_stamping_distance", json!([0])),
        ("filament_stamping_loading_speed", json!([0])),
        ("filament_toolchange_delay", json!([0])),
        ("filament_tower_interface_pre_extrusion_dist", json!([10])),
        ("filament_tower_interface_pre_extrusion_length", json!([0])),
        ("filament_tower_interface_print_temp", json!([-1])),
        ("filament_tower_interface_purge_volume", json!([20])),
        ("filament_tower_ironing_area", json!([4])),
        ("filament_type", json!(["PLA"])),
        ("filament_unloading_speed", json!([90])),
        ("filament_unloading_speed_start", json!([100])),
        ("filament_vendor", json!(["(Undefined)"])),
        (
            "filename_format",
            json!("{input_filename_base}_{filament_type[initial_tool]}_{print_time}.gcode"),
        ),
        ("fill_multiline", json!(1)),
        ("filter_out_gap_fill", json!(0)),
        ("first_layer_flow_ratio", json!(1)),
        ("first_x_layer_fan_speed", json!([0])),
        ("lateral_lattice_angle_1", json!(-45)),
        ("lateral_lattice_angle_2", json!(45)),
        ("inner_wall_flow_ratio", json!(1)),
        ("outer_wall_flow_ratio", json!(1)),
        ("ooze_prevention", json!(false)),
        ("parking_pos_retraction", json!(92)),
        ("precise_z_height", json!(false)),
        ("resonance_avoidance", json!(false)),
        ("resolution", json!(0.01)),
        ("retract_before_wipe", json!([100])),
        ("retract_length_toolchange", json!([10])),
        ("retract_when_changing_layer", json!([false])),
        ("retraction_distances_when_cut", json!([18])),
        ("retraction_distances_when_ec", json!([10])),
        ("retract_lift_above", json!([0])),
        ("retract_lift_below", json!([0])),
        ("retract_lift_enforce", json!(["All Surfaces"])),
        ("retraction_length", json!([0.8])),
        ("retraction_minimum_travel", json!([2])),
        ("scan_first_layer", json!(false)),
        ("set_other_flow_ratios", json!(false)),
        ("skeleton_infill_density", json!(25)),
        ("skeleton_infill_line_width", json!("100%")),
        ("skin_infill_density", json!(25)),
        ("skin_infill_depth", json!(2)),
        ("skin_infill_line_width", json!("100%")),
        ("slow_down_for_layer_cooling", json!([true])),
        ("slow_down_layers", json!(0)),
        ("slow_down_min_speed", json!([10])),
        ("slowdown_for_curled_perimeters", json!(true)),
        ("small_perimeter_speed", json!("50%")),
        ("small_perimeter_threshold", json!(0)),
        ("solid_infill_direction", json!(45)),
        ("solid_infill_rotate_template", json!("")),
        ("sparse_infill_filament", json!(1)),
        ("sparse_infill_pattern", json!("crosshatch")),
        ("sparse_infill_rotate_template", json!("")),
        ("sparse_infill_flow_ratio", json!(1)),
    ] {
        values.insert(key.to_owned(), value);
    }

    extruder_variant_id_values::insert_known_extruder_variant_id_values(values);
    filament_extruder_override_values::insert_known_filament_extruder_override_values(values);
    min_feature_length_values::insert_known_min_feature_length_values(values);
    process_values::insert_known_process_values(values);
    restart_speed_seam_values::insert_known_restart_speed_seam_values(values);
    scarf_seam_values::insert_known_scarf_seam_values(values);
    sla_display_tilt_values::insert_known_sla_display_tilt_values(values);
    tail_values::insert_known_tail_values(values);
    wipe_speed_loop_values::insert_known_wipe_speed_loop_values(values);
}
