use crate::{
    FilamentOptions, GenerationMetadata, PresetMetadata, PrinterOptions, ProcessOptions,
    ProjectRuntimeOptions, load_project, slice_project,
};

use super::fixture::ProjectParts;

#[tokio::test]
async fn project_exposes_partial_typed_settings_with_omitted_defaults() {
    let mut parts = ProjectParts::valid();
    parts.insert_text(
        "Metadata/project_settings.config",
        r#"{"layer_height":"0.27","wall_generator":"classic"}"#,
    );
    let bytes = parts.bytes();
    let project = load_project(&bytes).unwrap();
    let settings = project.settings();

    assert_eq!(settings.printer, PrinterOptions::default());
    assert_eq!(settings.filament, FilamentOptions::default());
    assert_eq!(settings.project, ProjectRuntimeOptions::default());
    assert_eq!(settings.metadata, PresetMetadata::default());

    let mut process = serde_json::to_value(&settings.process)
        .unwrap()
        .as_object()
        .unwrap()
        .clone();
    let mut defaults = serde_json::to_value(ProcessOptions::default())
        .unwrap()
        .as_object()
        .unwrap()
        .clone();
    assert_eq!(process.remove("layer_height").unwrap(), "0.27");
    assert_eq!(process.remove("wall_generator").unwrap(), "classic");
    defaults.remove("layer_height");
    defaults.remove("wall_generator");
    assert_eq!(process, defaults);

    let metadata = GenerationMetadata::deterministic(2026, 7, 13, 1, 2, 3);
    let output = slice_project(&bytes, metadata).await.unwrap();
    assert!(output.starts_with(b"; HEADER_BLOCK_START\n; generated by Ares"));
}

#[tokio::test]
async fn malformed_typed_settings_fail_during_project_loading() {
    let metadata = GenerationMetadata::deterministic(2026, 7, 13, 1, 2, 3);
    for (input, key, reason) in [
        (r#"{"future_option":"1"}"#, "", "ignored like orca"),
        (
            r#"{"layer_height":"0.2","layer_height":"0.3"}"#,
            "layer_height",
            "duplicate Orca option",
        ),
        (
            r#"{"layer_height":"not-a-float"}"#,
            "layer_height",
            "invalid float literal",
        ),
    ] {
        let mut parts = ProjectParts::valid();
        parts.insert_text("Metadata/project_settings.config", input);
        let bytes = parts.bytes();
        // Unknown keys are skipped (Orca config loader semantics); malformed
        // and duplicate typed keys still fail the load.
        let message = match load_project(&bytes) {
            Ok(_) if key.is_empty() => continue,
            Ok(_) => panic!("unexpected successful load for {key}"),
            Err(error) => error.to_string(),
        };

        assert!(message.starts_with("invalid project settings JSON: "));
        assert!(message.contains(key), "diagnostic omitted {key}: {message}");
        assert!(
            message.contains(reason),
            "diagnostic omitted {reason}: {message}"
        );
        assert!(slice_project(&bytes, metadata).await.is_err());
    }
}
