use super::super::{
    island_print_order::OrderedExtrusionLayer,
    perimeters::classic::traversal::PreparedPostClassicTraversal,
};
use crate::GenerationMetadata;

pub(super) fn append_header(
    output: &mut Vec<u8>,
    metadata: GenerationMetadata,
    objects: &[Vec<OrderedExtrusionLayer>],
    traversal: &PreparedPostClassicTraversal,
) {
    let (year, month, day, hour, minute, second) = metadata.timestamp();
    let layers = objects.iter().map(Vec::len).max().unwrap_or(0);
    let label_id = traversal
        .project
        .objects()
        .first()
        .and_then(|object| object.instances().first())
        .map_or(0, |instance| instance.loaded_label_id());
    let density = format_values(
        &traversal
            .resolved
            .views
            .full
            .filament
            .gcode
            .filament_density
            .0,
    );
    let diameter = format_values(
        &traversal
            .resolved
            .views
            .full
            .filament
            .gcode
            .filament_diameter
            .0,
    );
    let max_z = traversal
        .objects
        .first()
        .into_iter()
        .flat_map(|object| object.records.iter())
        .filter_map(|record| record.as_ref())
        .map(|record| record.layer_height)
        .sum::<f64>();
    let filament_count = traversal.resolved.usage.supported_used_filaments.len();
    output.extend_from_slice(b"; HEADER_BLOCK_START\n");
    output.extend_from_slice(
        format!(
            "; generated by Ares 2.4.2 on {year:04}-{month:02}-{day:02} at {hour:02}:{minute:02}:{second:02}\n"
        )
        .as_bytes(),
    );
    let tags = super::tags::Tags::of(traversal);
    // `GCode.cpp:2578-2608`: BBL printers carry the time placeholders in
    // the header; the compatible flavor keeps them at the file tail next to
    // the klipper-style statistics.
    if tags.is_bbl() {
        output.extend_from_slice(b"; model printing time: 0s; total estimated time: 0s\n");
        output.extend_from_slice(b"; estimated first layer printing time (normal mode) = 0s\n");
    }
    output.extend_from_slice(format!("; total layer number: {layers}\n").as_bytes());
    (tags.is_bbl())
        .then(|| output.extend_from_slice(format!("; model label id: {label_id}\n").as_bytes()));
    output.extend_from_slice(format!("; filament_density: {density}\n").as_bytes());
    output.extend_from_slice(format!("; filament_diameter: {diameter}\n").as_bytes());
    output.extend_from_slice(format!("; max_z_height: {max_z:.2}\n").as_bytes());
    output.extend_from_slice(format!("; filament: {filament_count}\n").as_bytes());
    output.extend_from_slice(b"; HEADER_BLOCK_END\n\n");
}

fn format_values(values: &[crate::OrcaFloat]) -> String {
    values
        .iter()
        .map(|value| {
            let rendered = format!("{:.2}", value.0);
            rendered
                .trim_end_matches('0')
                .trim_end_matches('.')
                .to_owned()
        })
        .collect::<Vec<_>>()
        .join(",")
}

pub(super) fn append_width_block(output: &mut Vec<u8>, traversal: &PreparedPostClassicTraversal) {
    let settings = &traversal.resolved.views.full;
    let nozzle = settings
        .project
        .print
        .nozzle_diameter
        .0
        .first()
        .map_or(0.4, |value| value.0);
    let object = traversal.resolved.objects.first();
    let region = object
        .and_then(|object| object.layer_candidates.first())
        .and_then(|layer| layer.model_parts.first().map(|part| &part.region));
    let object_width = object.and_then(|object| width(object.object.line_width, nozzle));
    let widths = [
        region
            .and_then(|region| width(region.outer_wall_line_width, nozzle))
            .or(object_width),
        region
            .and_then(|region| width(region.inner_wall_line_width, nozzle))
            .or(object_width),
        region
            .and_then(|region| width(region.sparse_infill_line_width, nozzle))
            .or(object_width),
        region
            .and_then(|region| width(region.internal_solid_infill_line_width, nozzle))
            .or(object_width),
        region
            .and_then(|region| width(region.top_surface_line_width, nozzle))
            .or(object_width),
        width(settings.process.print.initial_layer_line_width, nozzle).or(object_width),
    ];
    let labels = [
        "external perimeters",
        "perimeters",
        "infill",
        "solid infill",
        "top infill",
    ];
    for (index, label) in labels.into_iter().enumerate() {
        if let Some(width) = widths[index] {
            output.extend_from_slice(
                format!("; {label} extrusion width = {width:.2}mm\n").as_bytes(),
            );
        }
    }
    let support_width = object.and_then(|object| {
        let options = &object.object;
        if !options.enable_support.0
            && options.enforce_support_layers.0 <= 0
            && options.raft_layers.0 <= 0
        {
            return None;
        }
        let index = options.support_filament.0.saturating_sub(1) as usize;
        let support_nozzle = settings
            .project
            .print
            .nozzle_diameter
            .0
            .get(index)
            .or_else(|| settings.project.print.nozzle_diameter.0.first())
            .map_or(nozzle, |value| value.0);
        Some(
            width(options.support_line_width, support_nozzle)
                .or_else(|| width(options.line_width, support_nozzle))
                .unwrap_or(1.125 * support_nozzle as f32),
        )
    });
    if let Some(width) = support_width {
        output.extend_from_slice(
            format!("; support material extrusion width = {width:.2}mm\n").as_bytes(),
        );
    }
    if let Some(width) = widths[5] {
        output.extend_from_slice(
            format!("; first layer extrusion width = {width:.2}mm\n").as_bytes(),
        );
    }
    output.push(b'\n');
}

fn width(value: crate::FloatOrPercent, nozzle: f64) -> Option<f32> {
    match value {
        crate::FloatOrPercent::Float(value) if value > 0.0 => Some(value as f32),
        crate::FloatOrPercent::Percent(value) if value.0 > 0.0 => {
            Some((value.0 * nozzle / 100.0) as f32)
        }
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn header_values_trim_fractional_trailing_zeroes() {
        let values = [
            crate::OrcaFloat(1.3),
            crate::OrcaFloat(1.24),
            crate::OrcaFloat(1.0),
        ];

        assert_eq!(super::format_values(&values), "1.3,1.24,1");
    }
}
