use super::super::perimeters::classic::traversal::PreparedPostClassicTraversal;
use crate::GenerationMetadata;

pub(super) fn append_header(
    output: &mut Vec<u8>,
    metadata: GenerationMetadata,
    traversal: &PreparedPostClassicTraversal,
) {
    let (year, month, day, hour, minute, second) = metadata.timestamp();
    let layers = plate_layer_count(traversal);
    let label_id = traversal
        .project
        .objects()
        .first()
        .and_then(|object| object.instances().first())
        .map_or(0, |instance| instance.loaded_label_id());
    let density = format_values(
        &traversal
            .resolved
            .views
            .full
            .filament
            .gcode
            .filament_density
            .0,
    );
    let diameter = format_values(
        &traversal
            .resolved
            .views
            .full
            .filament
            .gcode
            .filament_diameter
            .0,
    );
    let max_z = traversal
        .objects
        .first()
        .into_iter()
        .flat_map(|object| object.records.iter())
        .filter_map(|record| record.as_ref())
        .map(|record| record.layer_height)
        .sum::<f64>();
    let filament_count = traversal.resolved.usage.supported_used_filaments.len();
    output.extend_from_slice(b"; HEADER_BLOCK_START\n");
    output.extend_from_slice(
        format!(
            "; generated by Ares 2.4.2 on {year:04}-{month:02}-{day:02} at {hour:02}:{minute:02}:{second:02}\n"
        )
        .as_bytes(),
    );
    let tags = super::tags::Tags::of(traversal);
    // `GCode.cpp:2578-2608`: BBL printers carry the time placeholders in
    // the header; the compatible flavor keeps them at the file tail next to
    // the klipper-style statistics.
    if tags.is_bbl() {
        output.extend_from_slice(b"; model printing time: 0s; total estimated time: 0s\n");
        output.extend_from_slice(b"; estimated first layer printing time (normal mode) = 0s\n");
    }
    output.extend_from_slice(format!("; total layer number: {layers}\n").as_bytes());
    (tags.is_bbl())
        .then(|| output.extend_from_slice(format!("; model label id: {label_id}\n").as_bytes()));
    output.extend_from_slice(format!("; filament_density: {density}\n").as_bytes());
    output.extend_from_slice(format!("; filament_diameter: {diameter}\n").as_bytes());
    output.extend_from_slice(format!("; max_z_height: {max_z:.2}\n").as_bytes());
    output.extend_from_slice(format!("; filament: {filament_count}\n").as_bytes());
    output.extend_from_slice(b"; HEADER_BLOCK_END\n\n");
}

/// `GCode.cpp:2513-2527` (default print sequence): the plate layer count
/// merges every print object's layer print_z values into one sorted unique
/// set, rather than summing per-object layer counts.
pub(super) fn plate_layer_count(traversal: &PreparedPostClassicTraversal) -> usize {
    let mut zs = Vec::new();
    for object in &traversal.objects {
        let (post_region, _) = object
            .predecessor
            .predecessor
            .predecessor
            .predecessor
            .object
            .object
            .as_parts();
        let (plan, _, _) = post_region.as_parts();
        let object_index = traversal
            .objects
            .iter()
            .position(|candidate| std::ptr::eq(candidate, object))
            .unwrap_or(0);
        let resolved_object = &traversal.resolved.objects[object_index];
        // Raft layers precede the object layers (`PrintObject::layers()`
        // carries the raft offset); their print z's join the plate grid,
        // and the object z's shift by the raft offset.
        let (raft_zs, object_shift) = match crate::project_slice::raft::bridge::build_project_raft(
            &traversal.resolved.views.full,
            &resolved_object.object,
            plan.layers.iter().map(|layer| layer.height).sum(),
            &[],
            traversal.scale,
        ) {
            Ok(Some(stream)) => (
                stream
                    .plans
                    .iter()
                    .map(|plan| plan.z.print_z)
                    .collect::<Vec<_>>(),
                stream.object_print_z_min,
            ),
            _ => (Vec::new(), 0.0),
        };
        zs.extend(plan.layers.iter().map(|layer| layer.print_z + object_shift));
        zs.extend(raft_zs);
    }
    zs.sort_by(f64::total_cmp);
    let mut count = 0;
    let mut previous: Option<f64> = None;
    for z in zs {
        if previous.is_none_or(|previous| (z - previous).abs() >= EPSILON) {
            count += 1;
            previous = Some(z);
        }
    }
    count
}

/// `libslic3r` `EPSILON` used by `GCode.cpp:2523` to merge numerically
/// close layer print_z values.
const EPSILON: f64 = 1e-4;

pub(super) fn finalize_layer_count(output: &mut Vec<u8>, layers: usize) -> usize {
    let prefix = b"; total layer number: ";
    let start = output
        .windows(prefix.len())
        .position(|window| window == prefix)
        .expect("generated header contains its layer-count field")
        + prefix.len();
    let end = output[start..]
        .iter()
        .position(|byte| *byte == b'\n')
        .expect("generated layer-count field is line terminated")
        + start;
    output.splice(start..end, layers.to_string().bytes());
    layers
}

fn format_values(values: &[crate::OrcaFloat]) -> String {
    values
        .iter()
        .map(|value| value.0.to_string())
        .collect::<Vec<_>>()
        .join(",")
}

pub(super) fn append_width_block(output: &mut Vec<u8>, traversal: &PreparedPostClassicTraversal) {
    // `GCode.cpp:2676-2693`: one terse width block per print region, in
    // region order (one region per object model part here).
    for object in &traversal.resolved.objects {
        append_object_width_block(output, traversal, object);
    }
}

fn append_object_width_block(
    output: &mut Vec<u8>,
    traversal: &PreparedPostClassicTraversal,
    object: &crate::project::effective_config::types::ResolvedProjectObject,
) {
    let settings = &traversal.resolved.views.full;
    let nozzle = settings
        .project
        .print
        .nozzle_diameter
        .0
        .first()
        .map_or(0.4, |value| value.0);
    let object_options = &object.object;
    let region = object
        .layer_candidates
        .first()
        .and_then(|layer| layer.model_parts.first().map(|part| &part.region))
        .expect("validated object has a model-part region");
    let widths = [
        resolved_width(
            region.outer_wall_line_width,
            object_options.line_width,
            nozzle,
            1.125,
        ),
        resolved_width(
            region.inner_wall_line_width,
            object_options.line_width,
            nozzle,
            1.125,
        ),
        resolved_width(
            region.sparse_infill_line_width,
            object_options.line_width,
            nozzle,
            1.125,
        ),
        resolved_width(
            region.internal_solid_infill_line_width,
            object_options.line_width,
            nozzle,
            1.125,
        ),
        resolved_width(
            region.top_surface_line_width,
            object_options.line_width,
            nozzle,
            1.0,
        ),
    ];
    let first_layer_width = width(settings.process.print.initial_layer_line_width, nozzle);
    let labels = [
        "external perimeters",
        "perimeters",
        "infill",
        "solid infill",
        "top infill",
    ];
    for (index, label) in labels.into_iter().enumerate() {
        output.extend_from_slice(
            format!("; {label} extrusion width = {:.2}mm\n", widths[index]).as_bytes(),
        );
    }
    let support_width = if !object_options.enable_support.0
        && object_options.enforce_support_layers.0 <= 0
        && object_options.raft_layers.0 <= 0
    {
        None
    } else {
        let index = object_options.support_filament.0.saturating_sub(1) as usize;
        let support_nozzle = settings
            .project
            .print
            .nozzle_diameter
            .0
            .get(index)
            .or_else(|| settings.project.print.nozzle_diameter.0.first())
            .map_or(nozzle, |value| value.0);
        Some(resolved_width(
            object_options.support_line_width,
            object_options.line_width,
            support_nozzle,
            1.0,
        ))
    };
    if let Some(width) = support_width {
        output.extend_from_slice(
            format!("; support material extrusion width = {width:.2}mm\n").as_bytes(),
        );
    }
    if let Some(width) = first_layer_width {
        output.extend_from_slice(
            format!("; first layer extrusion width = {width:.2}mm\n").as_bytes(),
        );
    }
    output.push(b'\n');
}

fn resolved_width(
    configured: crate::FloatOrPercent,
    fallback: crate::FloatOrPercent,
    nozzle: f64,
    automatic_ratio: f64,
) -> f32 {
    width(configured, nozzle)
        .or_else(|| width(fallback, nozzle))
        .unwrap_or_else(|| auto_width(automatic_ratio, nozzle))
}

fn width(value: crate::FloatOrPercent, nozzle: f64) -> Option<f32> {
    match value {
        crate::FloatOrPercent::Float(value) if value > 0.0 => Some(value as f32),
        crate::FloatOrPercent::Percent(value) if value.0 > 0.0 => {
            // `Flow::new_from_config_width` (`Flow.cpp:129-144`) takes the
            // nozzle as FLOAT and resolves the percent through
            // `get_abs_value(double)` — the nozzle f32 round-trip moves
            // boundary cases like 0.3×115% across the 0.345 rounding edge
            // (0.34500001 → "0.35" instead of 0.345 → "0.34").
            Some((value.0 * f64::from(nozzle as f32) / 100.0) as f32)
        }
        _ => None,
    }
}

/// `Flow::auto_extrusion_width` (`Flow.cpp`): the automatic ratio
/// multiplies in FLOAT.
fn auto_width(automatic_ratio: f64, nozzle: f64) -> f32 {
    (automatic_ratio as f32) * (nozzle as f32)
}

#[cfg(test)]
mod tests {
    #[test]
    fn automatic_role_widths_match_upstream_defaults() {
        let auto = crate::FloatOrPercent::Float(0.0);

        // `Flow::auto_extrusion_width` multiplies in FLOAT: 1.125f × 0.4f
        // = 0.45000002, not the f64 0.45.
        assert_eq!(super::resolved_width(auto, auto, 0.4, 1.125), 0.45000002);
        assert_eq!(super::resolved_width(auto, auto, 0.4, 1.0), 0.4);
        assert_eq!(super::width(auto, 0.4), None);
    }

    #[test]
    fn header_values_trim_fractional_trailing_zeroes() {
        let values = [
            crate::OrcaFloat(1.3),
            crate::OrcaFloat(1.24),
            crate::OrcaFloat("1.12838".parse().unwrap()),
            crate::OrcaFloat(1.0),
        ];

        assert_eq!(super::format_values(&values), "1.3,1.24,1.12838,1");
    }
}
