import { spawnSync } from "node:child_process";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { expect, test } from "@playwright/test";

const repositoryRoot = fileURLToPath(new URL("../../../../", import.meta.url));

async function expectSemanticParity(gcode) {
  const directory = await mkdtemp(join(tmpdir(), "ares-wasm-gcode-"));
  const output = join(directory, "browser.gcode");
  try {
    await writeFile(output, gcode, "utf8");
    const comparison = spawnSync(
      "cargo",
      [
        "nextest",
        "run",
        "-p",
        "ares-cli",
        "browser_output_matches_orca_242_semantically",
        "--run-ignored",
        "all",
      ],
      {
        cwd: repositoryRoot,
        encoding: "utf8",
        env: { ...process.env, ARES_BROWSER_GCODE: output },
        timeout: 300_000,
      },
    );
    expect(
      comparison.status,
      `${comparison.stdout ?? ""}\n${comparison.stderr ?? ""}`,
    ).toBe(0);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}

async function openFixturePage(page) {
  await page.goto("/");
  await page.waitForFunction(
    () => window.aresReady === true || window.aresError !== undefined,
    undefined,
    { timeout: 10_000 },
  );
  const state = await page.evaluate(() => ({ ready: window.aresReady, error: window.aresError }));
  expect(state.error).toBeUndefined();
  expect(state.ready).toBe(true);
}

test("browser project route emits complete finite KSR G-code", async ({ page }) => {
  test.setTimeout(180_000);
  await openFixturePage(page);

  const result = await page.evaluate(() => window.sliceFixtureProject());

  expect(result.gcode).toContain("; HEADER_BLOCK_START\n");
  expect(result.byteLength).toBeGreaterThan(6_000_000);
  expect(result.generator).toMatch(
    /^; generated by Ares 2\.4\.2 on \d{4}-\d{2}-\d{2} at \d{2}:\d{2}:\d{2}$/,
  );
  expect(result.layers).toBe(460);
  expect(result.hasHeader).toBe(true);
  expect(result.hasFooter).toBe(true);
  expect(result.hasNonFiniteMotion).toBe(false);
  await expectSemanticParity(result.gcode);
});

test("browser bindings expose no internal checkpoint hooks", async ({ page }) => {
  await openFixturePage(page);

  const exports = await page.evaluate(() => window.bindingExports);
  expect(exports.filter((name) => name.startsWith("task22"))).toEqual([]);
});
