import { expect, test } from "@playwright/test";

async function openFixturePage(page) {
  await page.goto("/");
  await page.waitForFunction(
    () => window.aresReady === true || window.aresError !== undefined,
    undefined,
    { timeout: 10_000 },
  );
  const state = await page.evaluate(() => ({ ready: window.aresReady, error: window.aresError }));
  expect(state.error).toBeUndefined();
  expect(state.ready).toBe(true);
}

test("browser project route emits complete finite KSR G-code", async ({ page }) => {
  test.setTimeout(180_000);
  await openFixturePage(page);

  const result = await page.evaluate(() => window.sliceFixtureProject());

  expect(result.byteLength).toBeGreaterThan(6_000_000);
  expect(result.generator).toMatch(
    /^; generated by Ares 2\.4\.2 on \d{4}-\d{2}-\d{2} at \d{2}:\d{2}:\d{2}$/,
  );
  expect(result.layers).toBe(460);
  expect(result.hasHeader).toBe(true);
  expect(result.hasFooter).toBe(true);
  expect(result.hasNonFiniteMotion).toBe(false);
});

test("browser bindings expose no internal checkpoint hooks", async ({ page }) => {
  await openFixturePage(page);

  const exports = await page.evaluate(() => window.bindingExports);
  expect(exports.filter((name) => name.startsWith("task22"))).toEqual([]);
});
