#[test]
fn exposes_strength_option_definition_lookup() {
    for (key, kind, default_value) in [
        (
            "align_infill_direction_to_model",
            crate::OptionValueKind::Bool,
            "false",
        ),
        (
            "extra_solid_infills",
            crate::OptionValueKind::String,
            "",
        ),
        (
            "fill_multiline",
            crate::OptionValueKind::Int,
            "1",
        ),
        (
            "gyroid_optimized",
            crate::OptionValueKind::Bool,
            "false",
        ),
        (
            "infill_direction",
            crate::OptionValueKind::Float,
            "45",
        ),
        (
            "infill_anchor",
            crate::OptionValueKind::FloatOrPercent,
            "400%",
        ),
        (
            "infill_anchor_max",
            crate::OptionValueKind::FloatOrPercent,
            "20",
        ),
        (
            "infill_overhang_angle",
            crate::OptionValueKind::Float,
            "60",
        ),
        (
            "lateral_lattice_angle_1",
            crate::OptionValueKind::Float,
            "-45",
        ),
        (
            "lateral_lattice_angle_2",
            crate::OptionValueKind::Float,
            "45",
        ),
        (
            "solid_infill_direction",
            crate::OptionValueKind::Float,
            "45",
        ),
        (
            "sparse_infill_density",
            crate::OptionValueKind::Percent,
            "20",
        ),
        (
            "sparse_infill_pattern",
            crate::OptionValueKind::Enum,
            "crosshatch",
        ),
    ] {
        let definition = crate::option_definition(key).unwrap();
        assert_eq!(definition.kind, kind);
        assert_eq!(definition.default_value, default_value);
    }
}
