#[test]
fn exposes_fuzzy_skin_option_definition_lookup() {
    for (key, kind, default_value) in [
        (
            "fuzzy_skin",
            crate::OptionValueKind::Enum,
            "disabled_fuzzy",
        ),
        (
            "fuzzy_skin_first_layer",
            crate::OptionValueKind::Bool,
            "false",
        ),
        (
            "fuzzy_skin_layers_between_ripple_offset",
            crate::OptionValueKind::Int,
            "1",
        ),
        (
            "fuzzy_skin_mode",
            crate::OptionValueKind::Enum,
            "displacement",
        ),
        (
            "fuzzy_skin_noise_type",
            crate::OptionValueKind::Enum,
            "classic",
        ),
        (
            "fuzzy_skin_octaves",
            crate::OptionValueKind::Int,
            "4",
        ),
        (
            "fuzzy_skin_persistence",
            crate::OptionValueKind::Float,
            "0.5",
        ),
        (
            "fuzzy_skin_point_distance",
            crate::OptionValueKind::Float,
            "0.3",
        ),
        (
            "fuzzy_skin_ripple_offset",
            crate::OptionValueKind::Percent,
            "50",
        ),
        (
            "fuzzy_skin_ripples_per_layer",
            crate::OptionValueKind::Int,
            "15",
        ),
        (
            "fuzzy_skin_scale",
            crate::OptionValueKind::Float,
            "1",
        ),
        (
            "fuzzy_skin_thickness",
            crate::OptionValueKind::Float,
            "0.2",
        ),
    ] {
        let definition = crate::option_definition(key).unwrap();
        assert_eq!(definition.kind, kind);
        assert_eq!(definition.default_value, default_value);
    }
}
