#[test]
fn exposes_fan_and_filament_color_note_option_definition_lookup() {
    for (key, kind, default_value) in [
        (
            "default_filament_colour",
            crate::OptionValueKind::Strings,
            "",
        ),
        (
            "fan_cooling_layer_time",
            crate::OptionValueKind::Floats,
            "60",
        ),
        (
            "filament_adaptive_volumetric_speed",
            crate::OptionValueKind::BoolsNullable,
            "false",
        ),
        (
            "filament_adhesiveness_category",
            crate::OptionValueKind::Ints,
            "0",
        ),
        (
            "filament_change_length",
            crate::OptionValueKind::Floats,
            "10",
        ),
        (
            "filament_colour",
            crate::OptionValueKind::Strings,
            "#F2754E",
        ),
        (
            "filament_colour_type",
            crate::OptionValueKind::Strings,
            "1",
        ),
        (
            "filament_cooling_before_tower",
            crate::OptionValueKind::FloatsNullable,
            "10",
        ),
        (
            "filament_cooling_final_speed",
            crate::OptionValueKind::Floats,
            "3.4",
        ),
        (
            "filament_cooling_initial_speed",
            crate::OptionValueKind::Floats,
            "2.2",
        ),
        (
            "filament_cooling_moves",
            crate::OptionValueKind::Ints,
            "4",
        ),
        (
            "filament_cost",
            crate::OptionValueKind::Floats,
            "0",
        ),
        (
            "filament_density",
            crate::OptionValueKind::Floats,
            "0",
        ),
        (
            "filament_flush_temp",
            crate::OptionValueKind::IntsNullable,
            "0",
        ),
        (
            "filament_flush_volumetric_speed",
            crate::OptionValueKind::FloatsNullable,
            "0",
        ),
        (
            "filament_ids",
            crate::OptionValueKind::Strings,
            "",
        ),
        (
            "filament_ironing_flow",
            crate::OptionValueKind::PercentsNullable,
            "nil",
        ),
        (
            "filament_ironing_inset",
            crate::OptionValueKind::FloatsNullable,
            "nil",
        ),
        (
            "filament_ironing_spacing",
            crate::OptionValueKind::FloatsNullable,
            "nil",
        ),
        (
            "filament_ironing_speed",
            crate::OptionValueKind::FloatsNullable,
            "nil",
        ),
        (
            "filament_is_support",
            crate::OptionValueKind::Bools,
            "false",
        ),
        (
            "filament_loading_speed",
            crate::OptionValueKind::Floats,
            "28",
        ),
        (
            "filament_loading_speed_start",
            crate::OptionValueKind::Floats,
            "3",
        ),
        (
            "filament_diameter",
            crate::OptionValueKind::Floats,
            "1.75",
        ),
        (
            "filament_map",
            crate::OptionValueKind::Ints,
            "1",
        ),
        (
            "filament_map_mode",
            crate::OptionValueKind::Enum,
            "Auto For Flush",
        ),
        (
            "filament_max_volumetric_speed",
            crate::OptionValueKind::Floats,
            "2",
        ),
        (
            "filament_minimal_purge_on_wipe_tower",
            crate::OptionValueKind::Floats,
            "15",
        ),
        (
            "filament_multi_colour",
            crate::OptionValueKind::Strings,
            "",
        ),
        (
            "filament_multitool_ramming",
            crate::OptionValueKind::Bools,
            "false",
        ),
        (
            "filament_multitool_ramming_flow",
            crate::OptionValueKind::Floats,
            "10",
        ),
        (
            "filament_multitool_ramming_volume",
            crate::OptionValueKind::Floats,
            "10",
        ),
        (
            "filament_notes",
            crate::OptionValueKind::Strings,
            "",
        ),
        (
            "filament_printable",
            crate::OptionValueKind::Ints,
            "3",
        ),
        (
            "filament_ramming_parameters",
            crate::OptionValueKind::Strings,
            "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6",
        ),
        (
            "filament_settings_id",
            crate::OptionValueKind::Strings,
            "",
        ),
        (
            "filament_shrink",
            crate::OptionValueKind::Percents,
            "100",
        ),
        (
            "filament_shrinkage_compensation_z",
            crate::OptionValueKind::Percents,
            "100",
        ),
        (
            "filament_soluble",
            crate::OptionValueKind::Bools,
            "false",
        ),
        (
            "filament_stamping_distance",
            crate::OptionValueKind::Floats,
            "0",
        ),
        (
            "filament_stamping_loading_speed",
            crate::OptionValueKind::Floats,
            "0",
        ),
        (
            "filament_toolchange_delay",
            crate::OptionValueKind::Floats,
            "0",
        ),
        (
            "filament_tower_interface_pre_extrusion_dist",
            crate::OptionValueKind::Floats,
            "10",
        ),
        (
            "filament_tower_interface_pre_extrusion_length",
            crate::OptionValueKind::Floats,
            "0",
        ),
        (
            "filament_tower_interface_print_temp",
            crate::OptionValueKind::Ints,
            "-1",
        ),
        (
            "filament_tower_interface_purge_volume",
            crate::OptionValueKind::Floats,
            "20",
        ),
        (
            "filament_tower_ironing_area",
            crate::OptionValueKind::Floats,
            "4",
        ),
        (
            "filament_type",
            crate::OptionValueKind::Strings,
            "PLA",
        ),
        (
            "filament_unloading_speed",
            crate::OptionValueKind::Floats,
            "90",
        ),
        (
            "filament_unloading_speed_start",
            crate::OptionValueKind::Floats,
            "100",
        ),
        (
            "filament_vendor",
            crate::OptionValueKind::Strings,
            "(Undefined)",
        ),
        (
            "temperature_vitrification",
            crate::OptionValueKind::Ints,
            "100",
        ),
        (
            "enable_filament_dynamic_map",
            crate::OptionValueKind::Bool,
            "false",
        ),
        (
            "has_filament_switcher",
            crate::OptionValueKind::Bool,
            "false",
        ),
        (
            "physical_extruder_map",
            crate::OptionValueKind::Ints,
            "0",
        ),
        (
            "required_nozzle_HRC",
            crate::OptionValueKind::Ints,
            "0",
        ),
    ] {
        let definition = crate::option_definition(key).unwrap();
        assert_eq!(definition.kind, kind);
        assert_eq!(definition.default_value, default_value);
    }
}
