#[test]
fn exposes_speed_option_definition_lookup() {
    for (key, kind, default_value) in [
        (
            "accel_to_decel_enable",
            crate::OptionValueKind::Bool,
            "true",
        ),
        (
            "accel_to_decel_factor",
            crate::OptionValueKind::Percent,
            "50",
        ),
        (
            "bridge_acceleration",
            crate::OptionValueKind::FloatOrPercent,
            "50%",
        ),
        (
            "default_jerk",
            crate::OptionValueKind::Float,
            "0",
        ),
        (
            "default_junction_deviation",
            crate::OptionValueKind::Float,
            "0",
        ),
        (
            "infill_jerk",
            crate::OptionValueKind::Float,
            "9",
        ),
        (
            "initial_layer_acceleration",
            crate::OptionValueKind::Float,
            "300",
        ),
        (
            "initial_layer_infill_speed",
            crate::OptionValueKind::Float,
            "60",
        ),
        (
            "initial_layer_jerk",
            crate::OptionValueKind::Float,
            "9",
        ),
        (
            "initial_layer_line_width",
            crate::OptionValueKind::FloatOrPercent,
            "0",
        ),
        (
            "initial_layer_print_height",
            crate::OptionValueKind::Float,
            "0.2",
        ),
        (
            "initial_layer_speed",
            crate::OptionValueKind::Float,
            "30",
        ),
        (
            "initial_layer_travel_acceleration",
            crate::OptionValueKind::FloatOrPercent,
            "100%",
        ),
        (
            "initial_layer_travel_jerk",
            crate::OptionValueKind::FloatOrPercent,
            "100%",
        ),
        (
            "initial_layer_travel_speed",
            crate::OptionValueKind::FloatOrPercent,
            "100%",
        ),
        (
            "inner_wall_acceleration",
            crate::OptionValueKind::Float,
            "10000",
        ),
        (
            "inner_wall_jerk",
            crate::OptionValueKind::Float,
            "9",
        ),
        (
            "internal_solid_infill_acceleration",
            crate::OptionValueKind::FloatOrPercent,
            "100%",
        ),
        (
            "outer_wall_acceleration",
            crate::OptionValueKind::Float,
            "500",
        ),
        (
            "outer_wall_jerk",
            crate::OptionValueKind::Float,
            "9",
        ),
        (
            "pellet_flow_coefficient",
            crate::OptionValueKind::Floats,
            "0.4157",
        ),
        (
            "sparse_infill_acceleration",
            crate::OptionValueKind::FloatOrPercent,
            "100%",
        ),
        (
            "slow_down_layers",
            crate::OptionValueKind::Int,
            "0",
        ),
        (
            "top_surface_acceleration",
            crate::OptionValueKind::Float,
            "500",
        ),
        (
            "top_surface_jerk",
            crate::OptionValueKind::Float,
            "9",
        ),
        (
            "travel_acceleration",
            crate::OptionValueKind::Float,
            "10000",
        ),
        (
            "travel_jerk",
            crate::OptionValueKind::Float,
            "12",
        ),
        (
            "volumetric_speed_coefficients",
            crate::OptionValueKind::Strings,
            "",
        ),
    ] {
        let definition = crate::option_definition(key).unwrap();
        assert_eq!(definition.kind, kind);
        assert_eq!(definition.default_value, default_value);
    }
}
