use crate::{OptionValueKind, option_definition};

#[test]
fn infill_combination_and_rotation_lookup_preserves_registry_contract() {
    for (key, kind, default_value) in [
        (
            "infill_combination",
            OptionValueKind::Bool,
            "false",
        ),
        (
            "infill_shift_step",
            OptionValueKind::Float,
            "0.4",
        ),
        (
            "infill_wall_overlap",
            OptionValueKind::Percent,
            "15",
        ),
        (
            "sparse_infill_filament",
            OptionValueKind::Int,
            "1",
        ),
        (
            "sparse_infill_line_width",
            OptionValueKind::FloatOrPercent,
            "0",
        ),
        (
            "sparse_infill_speed",
            OptionValueKind::Float,
            "100",
        ),
        (
            "top_bottom_infill_wall_overlap",
            OptionValueKind::Percent,
            "25",
        ),
        (
            "infill_combination_max_layer_height",
            OptionValueKind::FloatOrPercent,
            "100%",
        ),
        (
            "infill_lock_depth",
            OptionValueKind::Float,
            "1",
        ),
        (
            "skeleton_infill_density",
            OptionValueKind::Percent,
            "25",
        ),
        (
            "skeleton_infill_line_width",
            OptionValueKind::FloatOrPercent,
            "100%",
        ),
        (
            "skin_infill_density",
            OptionValueKind::Percent,
            "25",
        ),
        (
            "skin_infill_depth",
            OptionValueKind::Float,
            "2",
        ),
        (
            "skin_infill_line_width",
            OptionValueKind::FloatOrPercent,
            "100%",
        ),
        (
            "symmetric_infill_y_axis",
            OptionValueKind::Bool,
            "false",
        ),
        (
            "solid_infill_rotate_template",
            OptionValueKind::String,
            "",
        ),
        (
            "sparse_infill_rotate_template",
            OptionValueKind::String,
            "",
        ),
    ] {
        let definition = option_definition(key).unwrap();
        assert_eq!(definition.kind, kind);
        assert_eq!(definition.default_value, default_value);
    }
}
