#[test]
fn exposes_filament_extruder_override_option_definition_lookup() {
    for (key, kind, default_value) in [
        (
            "filament_deretraction_speed",
            crate::OptionValueKind::FloatsNullable,
            "0",
        ),
        (
            "filament_long_retractions_when_cut",
            crate::OptionValueKind::BoolsNullable,
            "false",
        ),
        (
            "filament_retract_before_wipe",
            crate::OptionValueKind::PercentsNullable,
            "100",
        ),
        (
            "filament_retract_lift_above",
            crate::OptionValueKind::FloatsNullable,
            "0",
        ),
        (
            "filament_retract_lift_below",
            crate::OptionValueKind::FloatsNullable,
            "0",
        ),
        (
            "filament_retract_lift_enforce",
            crate::OptionValueKind::EnumsNullable,
            "All Surfaces",
        ),
        (
            "filament_retract_restart_extra",
            crate::OptionValueKind::FloatsNullable,
            "0",
        ),
        (
            "filament_retract_when_changing_layer",
            crate::OptionValueKind::BoolsNullable,
            "false",
        ),
        (
            "filament_retraction_distances_when_cut",
            crate::OptionValueKind::FloatsNullable,
            "18",
        ),
        (
            "filament_retraction_length",
            crate::OptionValueKind::FloatsNullable,
            "0.8",
        ),
        (
            "filament_retraction_minimum_travel",
            crate::OptionValueKind::FloatsNullable,
            "2",
        ),
        (
            "filament_retraction_speed",
            crate::OptionValueKind::FloatsNullable,
            "30",
        ),
        (
            "filament_wipe",
            crate::OptionValueKind::BoolsNullable,
            "false",
        ),
        (
            "filament_wipe_distance",
            crate::OptionValueKind::FloatsNullable,
            "1",
        ),
        (
            "filament_z_hop",
            crate::OptionValueKind::FloatsNullable,
            "0.4",
        ),
        (
            "filament_z_hop_types",
            crate::OptionValueKind::EnumsNullable,
            "Slope Lift",
        ),
    ] {
        let definition = crate::option_definition(key).unwrap();
        assert_eq!(definition.kind, kind);
        assert_eq!(definition.default_value, default_value);
    }
}
