#[derive(Clone, Copy)]
pub(super) struct ExpectedField {
    pub(super) key: &'static str,
    pub(super) option_type: &'static str,
    pub(super) default: &'static str,
    pub(super) semantic_default_json: &'static str,
    pub(super) wire_shape: &'static str,
    pub(super) nullable: bool,
}

macro_rules! field {
    ($key:expr, $option_type:expr, $default:expr, $semantic_default_json:expr, $wire_shape:expr, $nullable:expr) => {
        ExpectedField {
            key: $key,
            option_type: $option_type,
            default: $default,
            semantic_default_json: $semantic_default_json,
            wire_shape: $wire_shape,
            nullable: $nullable,
        }
    };
}

pub(super) const EXPECTED_FIELDS: [ExpectedField; 62] = [
    field!("auxiliary_fan", "coBool", "0", r#""0""#, "scalar_string", false),
    field!("bed_temperature_formula", "coEnum", "by_highest_temp", r#""by_highest_temp""#, "scalar_string", false),
    field!("before_layer_change_gcode", "coString", "", r#""""#, "scalar_string", false),
    field!("change_extrusion_role_gcode", "coString", "", r#""""#, "scalar_string", false),
    field!("change_filament_gcode", "coString", "", r#""""#, "scalar_string", false),
    field!("cooling_tube_length", "coFloat", "5", r#""5""#, "scalar_string", false),
    field!("cooling_tube_retraction", "coFloat", "91.5", r#""91.5""#, "scalar_string", false),
    field!("disable_m73", "coBool", "0", r#""0""#, "scalar_string", false),
    field!("enable_filament_ramming", "coBool", "1", r#""1""#, "scalar_string", false),
    field!("enable_long_retraction_when_cut", "coInt", "0", r#""0""#, "scalar_string", false),
    field!("enable_power_loss_recovery", "coEnum", "printer_configuration", r#""printer_configuration""#, "scalar_string", false),
    field!("extra_loading_move", "coFloat", "-2", r#""-2""#, "scalar_string", false),
    field!("extruder_type", "coEnums", "Direct Drive", r#"["Direct Drive"]"#, "array", false),
    field!("fan_kickstart", "coFloat", "0", r#""0""#, "scalar_string", false),
    field!("fan_speedup_overhangs", "coBool", "1", r#""1""#, "scalar_string", false),
    field!("fan_speedup_time", "coFloat", "0", r#""0""#, "scalar_string", false),
    field!("file_start_gcode", "coString", "", r#""""#, "scalar_string", false),
    field!("gcode_flavor", "coEnum", "marlin", r#""marlin""#, "scalar_string", false),
    field!("high_current_on_filament_swap", "coBool", "0", r#""0""#, "scalar_string", false),
    field!("layer_change_gcode", "coString", "", r#""""#, "scalar_string", false),
    field!("long_retractions_when_cut", "coBools", "0", r#"["0"]"#, "array", false),
    field!("machine_end_gcode", "coString", "M104 S0 ; turn off temperature\\nG28 X0  ; home X axis\\nM84     ; disable motors\\n", r#""M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n""#, "scalar_string", false),
    field!("machine_load_filament_time", "coFloat", "0", r#""0""#, "scalar_string", false),
    field!("machine_pause_gcode", "coString", "", r#""""#, "scalar_string", false),
    field!("machine_start_gcode", "coString", "G28 ; home all axes\\nG1 Z5 F5000 ; lift nozzle\\n", r#""G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n""#, "scalar_string", false),
    field!("machine_tool_change_time", "coFloat", "0", r#""0""#, "scalar_string", false),
    field!("machine_unload_filament_time", "coFloat", "0", r#""0""#, "scalar_string", false),
    field!("manual_filament_change", "coBool", "0", r#""0""#, "scalar_string", false),
    field!("master_extruder_id", "coInt", "1", r#""1""#, "scalar_string", false),
    field!("nozzle_flush_dataset", "coInts", "0", r#"["0"]"#, "array", true),
    field!("nozzle_hrc", "coInt", "0", r#""0""#, "scalar_string", false),
    field!("nozzle_type", "coEnums", "undefine", r#"["undefine"]"#, "array", true),
    field!("parking_pos_retraction", "coFloat", "92", r#""92""#, "scalar_string", false),
    field!("part_cooling_fan_min_pwm", "coInt", "0", r#""0""#, "scalar_string", false),
    field!("physical_extruder_map", "coInts", "0", r#"["0"]"#, "array", false),
    field!("printer_extruder_id", "coInts", "1", r#"["1"]"#, "array", false),
    field!("printer_extruder_variant", "coStrings", "\"Direct Drive Standard\"", r#"["Direct Drive Standard"]"#, "array", false),
    field!("printer_structure", "coEnum", "undefine", r#""undefine""#, "scalar_string", false),
    field!("printing_by_object_gcode", "coString", "", r#""""#, "scalar_string", false),
    field!("purge_in_prime_tower", "coBool", "1", r#""1""#, "scalar_string", false),
    field!("retract_lift_enforce", "coEnums", "All Surfaces", r#"["All Surfaces"]"#, "array", false),
    field!("retraction_distances_when_cut", "coFloats", "18", r#"["18"]"#, "array", false),
    field!("scan_first_layer", "coBool", "0", r#""0""#, "scalar_string", false),
    field!("silent_mode", "coBool", "0", r#""0""#, "scalar_string", false),
    field!("single_extruder_multi_material", "coBool", "1", r#""1""#, "scalar_string", false),
    field!("support_air_filtration", "coBool", "1", r#""1""#, "scalar_string", false),
    field!("support_chamber_temp_control", "coBool", "1", r#""1""#, "scalar_string", false),
    field!("support_multi_bed_types", "coBool", "0", r#""0""#, "scalar_string", false),
    field!("support_object_skip_flush", "coBool", "0", r#""0""#, "scalar_string", false),
    field!("template_custom_gcode", "coString", "", r#""""#, "scalar_string", false),
    field!("time_cost", "coFloat", "0", r#""0""#, "scalar_string", false),
    field!("time_lapse_gcode", "coString", "", r#""""#, "scalar_string", false),
    field!("tool_change_on_wipe_tower", "coBool", "0", r#""0""#, "scalar_string", false),
    field!("travel_slope", "coFloats", "3", r#"["3"]"#, "array", false),
    field!("use_3mf", "coBool", "0", r#""0""#, "scalar_string", false),
    field!("use_firmware_retraction", "coBool", "0", r#""0""#, "scalar_string", false),
    field!("use_relative_e_distances", "coBool", "1", r#""1""#, "scalar_string", false),
    field!("wipe_tower_type", "coEnum", "type2", r#""type2""#, "scalar_string", false),
    field!("wrapping_detection_gcode", "coString", "", r#""""#, "scalar_string", false),
    field!("wrapping_detection_layers", "coInt", "20", r#""20""#, "scalar_string", false),
    field!("wrapping_exclude_area", "coPoints", "", "[]", "array", false),
    field!("z_hop_types", "coEnums", "Slope Lift", r#"["Slope Lift"]"#, "array", false),
];

pub(super) const DECLARATION_ORDER: [&str; 62] = [
    "before_layer_change_gcode", "printing_by_object_gcode", "machine_end_gcode",
    "fan_kickstart", "fan_speedup_overhangs", "fan_speedup_time",
    "part_cooling_fan_min_pwm", "support_object_skip_flush", "bed_temperature_formula",
    "physical_extruder_map", "nozzle_flush_dataset", "scan_first_layer",
    "enable_power_loss_recovery", "wrapping_detection_layers", "wrapping_exclude_area",
    "gcode_flavor", "time_cost", "layer_change_gcode", "time_lapse_gcode",
    "wrapping_detection_gcode", "enable_long_retraction_when_cut",
    "retraction_distances_when_cut", "long_retractions_when_cut", "z_hop_types",
    "travel_slope", "retract_lift_enforce", "file_start_gcode", "machine_start_gcode",
    "single_extruder_multi_material", "manual_filament_change", "change_filament_gcode",
    "change_extrusion_role_gcode", "silent_mode", "machine_pause_gcode",
    "template_custom_gcode", "nozzle_type", "nozzle_hrc", "auxiliary_fan",
    "support_air_filtration", "printer_structure", "support_chamber_temp_control",
    "extruder_type", "printer_extruder_id", "master_extruder_id",
    "printer_extruder_variant", "use_firmware_retraction", "use_relative_e_distances",
    "disable_m73", "cooling_tube_retraction", "cooling_tube_length",
    "high_current_on_filament_swap", "parking_pos_retraction", "extra_loading_move",
    "machine_load_filament_time", "machine_tool_change_time", "machine_unload_filament_time",
    "wipe_tower_type", "purge_in_prime_tower", "enable_filament_ramming",
    "tool_change_on_wipe_tower", "support_multi_bed_types", "use_3mf",
];
